//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Data;

using CMS.Base;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.Helpers;

namespace ETG.Core.PageTypes.Providers
{
    /// <summary>
    /// Provides methods for retrieving pages of type Tour.
    /// </summary>
    public partial class ExperienceProvider
    {
        /// <summary>
        /// Returns a query that selects published pages of type Tour.
        /// </summary>
        public static DocumentQuery<Experience> GetPreviewableExperiences()
        {
            return DocumentHelper.GetDocuments<Experience>();
        }
    }
}