import(/* webpackMode: "eager" */ '../widgets/header/header')
import(/* webpackMode: "eager" */ '../widgets/new-header/new-header')
import(/* webpackMode: "eager" */ '../widgets/header-spacer/header-spacer')
import(/* webpackMode: "eager" */ '../widgets/gdpr-consent/gdpr-consent')
import('../widgets/footer/footer')
import('../widgets/new-footer/new-footer')
import('../widgets/footer-brands/footer-brands')

// Common page components
import('../widgets/breadcrumbs/breadcrumbs')

// (Kentico) /Views/Shared/Widgets/
import('../widgets/cta-panel/cta-panel')
import('../widgets/package-accordion/package-accordion')
import('../widgets/experience-cta/experience-cta')
import('../widgets/full-width-image/full-width-image')
import('../widgets/iconigraphical-content/iconigraphical-content')
import('../widgets/landing-gallery/landing-gallery')
import('../widgets/partnership-with/partnership-with')
import('../widgets/partnership-with-new/partnership-with-new')
import('../widgets/partnership-with-updated/partnership-with-updated')
import('../widgets/new-featured-packages/new-featured-packages')
import('../widgets/single-column-richtext/single-column-richtext')
import('../widgets/new-covered/new-covered')
import('../widgets/spacer/spacer')
import('../widgets/table/table')
import('../widgets/testimonial/testimonial')
import('../widgets/callouts/callouts')
import('../widgets/side-by-side-images/side-by-side-images')
import('../widgets/static-video/static-video')
import('../widgets/video/video')
import('../widgets/photo-slider/photo-slider')

// Others
import('../widgets/related-articles/related-articles')
import('../widgets/view-all-cta/view-all-cta')
import('../widgets/feefo/feefo')
import('../widgets/product-tile/product-tile')
import('../widgets/brochure-gate-popup/brochure-gate-popup')
import('../widgets/subscription-bar/subscription-bar')
import('../widgets/subscribe-to-win-widget/subscribe-to-win-widget')
import('../widgets/subscribe-to-win-modal/subscribe-to-win-modal')
import('../widgets/nz-redirect-modal/nz-redirect-modal')
import('../widgets/faqs/faqs')
import('../widgets/page-hero/page-hero')
import('../widgets/hotel-builder/hotel-builder')
import('../widgets/customer-reviews/customer-reviews')
import('../widgets/blog-carousel/blog-carousel')
import('../widgets/experience-ticker/experience-ticker')
import('../widgets/new-hero/new-hero')
import('../widgets/new-destination-page/new-destination-page')
import('../widgets/featured-carousel/featured-carousel')
import('../widgets/theme-carousel/theme-carousel')
import('../widgets/tour-tiles-collection/tour-tiles-collection')
import('../widgets/tour-tiles-slider/tour-tiles-slider')
import('../widgets/why-we-love-it/why-we-love-it')
import('../widgets/package-enquiry/package-enquiry')
import('../widgets/package-detail-title/package-detail-title')
