//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.CustomTables;
using CMS.CustomTables;

[assembly: RegisterCustomTable(GoogleReviewsItem.CLASS_NAME, typeof(GoogleReviewsItem))]

namespace ETG.Core.CustomTables
{
	/// <summary>
	/// Represents a content item of type GoogleReviewsItem.
	/// </summary>
	public partial class GoogleReviewsItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.GoogleReviews";


		/// <summary>
		/// The instance of the class that provides extended API for working with GoogleReviewsItem fields.
		/// </summary>
		private readonly GoogleReviewsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Reviews.
		/// </summary>
		[DatabaseField]
		public string Reviews
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Reviews"), @"");
			}
			set
			{
				SetValue("Reviews", value);
			}
		}


		/// <summary>
		/// Date Extracted.
		/// </summary>
		[DatabaseField]
		public DateTime DateExtracted
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("DateExtracted"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("DateExtracted", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with GoogleReviewsItem fields.
		/// </summary>
		[RegisterProperty]
		public GoogleReviewsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with GoogleReviewsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GoogleReviewsItemFields : AbstractHierarchicalObject<GoogleReviewsItemFields>
		{
			/// <summary>
			/// The content item of type GoogleReviewsItem that is a target of the extended API.
			/// </summary>
			private readonly GoogleReviewsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GoogleReviewsItemFields" /> class with the specified content item of type GoogleReviewsItem.
			/// </summary>
			/// <param name="instance">The content item of type GoogleReviewsItem that is a target of the extended API.</param>
			public GoogleReviewsItemFields(GoogleReviewsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Reviews.
			/// </summary>
			public string Reviews
			{
				get
				{
					return mInstance.Reviews;
				}
				set
				{
					mInstance.Reviews = value;
				}
			}


			/// <summary>
			/// Date Extracted.
			/// </summary>
			public DateTime DateExtracted
			{
				get
				{
					return mInstance.DateExtracted;
				}
				set
				{
					mInstance.DateExtracted = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="GoogleReviewsItem" /> class.
		/// </summary>
		public GoogleReviewsItem() : base(CLASS_NAME)
		{
			mFields = new GoogleReviewsItemFields(this);
		}

		#endregion
	}
}