//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.CustomTables;
using CMS.CustomTables;

[assembly: RegisterCustomTable(RestrictedDomainItem.CLASS_NAME, typeof(RestrictedDomainItem))]

namespace ETG.Core.CustomTables
{
	/// <summary>
	/// Represents a content item of type RestrictedDomainItem.
	/// </summary>
	public partial class RestrictedDomainItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.RestrictedDomain";


		/// <summary>
		/// The instance of the class that provides extended API for working with RestrictedDomainItem fields.
		/// </summary>
		private readonly RestrictedDomainItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Domain name.
		/// </summary>
		[DatabaseField]
		public string DomainName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DomainName"), @"");
			}
			set
			{
				SetValue("DomainName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with RestrictedDomainItem fields.
		/// </summary>
		[RegisterProperty]
		public RestrictedDomainItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with RestrictedDomainItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class RestrictedDomainItemFields : AbstractHierarchicalObject<RestrictedDomainItemFields>
		{
			/// <summary>
			/// The content item of type RestrictedDomainItem that is a target of the extended API.
			/// </summary>
			private readonly RestrictedDomainItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="RestrictedDomainItemFields" /> class with the specified content item of type RestrictedDomainItem.
			/// </summary>
			/// <param name="instance">The content item of type RestrictedDomainItem that is a target of the extended API.</param>
			public RestrictedDomainItemFields(RestrictedDomainItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Domain name.
			/// </summary>
			public string DomainName
			{
				get
				{
					return mInstance.DomainName;
				}
				set
				{
					mInstance.DomainName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="RestrictedDomainItem" /> class.
		/// </summary>
		public RestrictedDomainItem() : base(CLASS_NAME)
		{
			mFields = new RestrictedDomainItemFields(this);
		}

		#endregion
	}
}