//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using ETG.Core.CustomTables;

[assembly: RegisterCustomTable(UnsubscribeReasonsItem.CLASS_NAME, typeof(UnsubscribeReasonsItem))]

namespace ETG.Core.CustomTables
{
    /// <summary>
    /// Represents a content item of type UnsubscribeReasonsItem.
    /// </summary>
    public partial class UnsubscribeReasonsItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.UnsubscribeReasons";


        /// <summary>
        /// The instance of the class that provides extended API for working with UnsubscribeReasonsItem fields.
        /// </summary>
        private readonly UnsubscribeReasonsItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Reason.
        /// </summary>
        [DatabaseField]
        public string Reason
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Reason"), @"");
            }
            set
            {
                SetValue("Reason", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with UnsubscribeReasonsItem fields.
        /// </summary>
        [RegisterProperty]
        public UnsubscribeReasonsItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with UnsubscribeReasonsItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class UnsubscribeReasonsItemFields : AbstractHierarchicalObject<UnsubscribeReasonsItemFields>
        {
            /// <summary>
            /// The content item of type UnsubscribeReasonsItem that is a target of the extended API.
            /// </summary>
            private readonly UnsubscribeReasonsItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="UnsubscribeReasonsItemFields" /> class with the specified content item of type UnsubscribeReasonsItem.
            /// </summary>
            /// <param name="instance">The content item of type UnsubscribeReasonsItem that is a target of the extended API.</param>
            public UnsubscribeReasonsItemFields(UnsubscribeReasonsItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Reason.
            /// </summary>
            public string Reason
            {
                get
                {
                    return mInstance.Reason;
                }
                set
                {
                    mInstance.Reason = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="UnsubscribeReasonsItem" /> class.
        /// </summary>
        public UnsubscribeReasonsItem() : base(CLASS_NAME)
        {
            mFields = new UnsubscribeReasonsItemFields(this);
        }

        #endregion
    }
}