//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Module.Booking.CustomTables;
using CMS.CustomTables;

[assembly: RegisterCustomTable(BookingPricingImportLogItem.CLASS_NAME, typeof(BookingPricingImportLogItem))]

namespace ETG.Module.Booking.CustomTables
{
	/// <summary>
	/// Represents a content item of type BookingPricingImportLogItem.
	/// </summary>
	public partial class BookingPricingImportLogItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.BookingPricingImportLog";


		/// <summary>
		/// The instance of the class that provides extended API for working with BookingPricingImportLogItem fields.
		/// </summary>
		private readonly BookingPricingImportLogItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Log Data.
		/// </summary>
		[DatabaseField]
		public string LogData
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LogData"), @"");
			}
			set
			{
				SetValue("LogData", value);
			}
		}


		/// <summary>
		/// LogDetails.
		/// </summary>
		[DatabaseField]
		public string LogDetails
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LogDetails"), @"");
			}
			set
			{
				SetValue("LogDetails", value);
			}
		}


		/// <summary>
		/// Status.
		/// </summary>
		[DatabaseField]
		public string LogStatus
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LogStatus"), @"");
			}
			set
			{
				SetValue("LogStatus", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BookingPricingImportLogItem fields.
		/// </summary>
		[RegisterProperty]
		public BookingPricingImportLogItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BookingPricingImportLogItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BookingPricingImportLogItemFields : AbstractHierarchicalObject<BookingPricingImportLogItemFields>
		{
			/// <summary>
			/// The content item of type BookingPricingImportLogItem that is a target of the extended API.
			/// </summary>
			private readonly BookingPricingImportLogItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BookingPricingImportLogItemFields" /> class with the specified content item of type BookingPricingImportLogItem.
			/// </summary>
			/// <param name="instance">The content item of type BookingPricingImportLogItem that is a target of the extended API.</param>
			public BookingPricingImportLogItemFields(BookingPricingImportLogItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Log Data.
			/// </summary>
			public string LogData
			{
				get
				{
					return mInstance.LogData;
				}
				set
				{
					mInstance.LogData = value;
				}
			}


			/// <summary>
			/// LogDetails.
			/// </summary>
			public string LogDetails
			{
				get
				{
					return mInstance.LogDetails;
				}
				set
				{
					mInstance.LogDetails = value;
				}
			}


			/// <summary>
			/// Status.
			/// </summary>
			public string LogStatus
			{
				get
				{
					return mInstance.LogStatus;
				}
				set
				{
					mInstance.LogStatus = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BookingPricingImportLogItem" /> class.
		/// </summary>
		public BookingPricingImportLogItem() : base(CLASS_NAME)
		{
			mFields = new BookingPricingImportLogItemFields(this);
		}

		#endregion
	}
}