//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.Forms;
using CMS.OnlineForms;

[assembly: RegisterBizForm(BrochureSignupItem.CLASS_NAME, typeof(BrochureSignupItem))]

namespace ETG.Core.Forms
{
    /// <summary>
    /// Represents a content item of type BrochureSignupItem.
    /// </summary>
    public partial class BrochureSignupItem : BizFormItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BizForm.BrochureSignup";


        /// <summary>
        /// The instance of the class that provides extended API for working with BrochureSignupItem fields.
        /// </summary>
        private readonly BrochureSignupItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Name.
        /// </summary>
        [DatabaseField]
        public string Name
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Name"), @"");
            }
            set
            {
                SetValue("Name", value);
            }
        }


        /// <summary>
        /// Email.
        /// </summary>
        [DatabaseField]
        public string Email
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Email"), @"");
            }
            set
            {
                SetValue("Email", value);
            }
        }


        /// <summary>
        /// Brochure Name.
        /// </summary>
        [DatabaseField]
        public string BrochureName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BrochureName"), @"");
            }
            set
            {
                SetValue("BrochureName", value);
            }
        }


        /// <summary>
        /// Url.
        /// </summary>
        [DatabaseField]
        public string Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Url"), @"");
            }
            set
            {
                SetValue("Url", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with BrochureSignupItem fields.
        /// </summary>
        [RegisterProperty]
        public BrochureSignupItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with BrochureSignupItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class BrochureSignupItemFields : AbstractHierarchicalObject<BrochureSignupItemFields>
        {
            /// <summary>
            /// The content item of type BrochureSignupItem that is a target of the extended API.
            /// </summary>
            private readonly BrochureSignupItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="BrochureSignupItemFields" /> class with the specified content item of type BrochureSignupItem.
            /// </summary>
            /// <param name="instance">The content item of type BrochureSignupItem that is a target of the extended API.</param>
            public BrochureSignupItemFields(BrochureSignupItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Name.
            /// </summary>
            public string Name
            {
                get
                {
                    return mInstance.Name;
                }
                set
                {
                    mInstance.Name = value;
                }
            }


            /// <summary>
            /// Email.
            /// </summary>
            public string Email
            {
                get
                {
                    return mInstance.Email;
                }
                set
                {
                    mInstance.Email = value;
                }
            }


            /// <summary>
            /// Brochure Name.
            /// </summary>
            public string BrochureName
            {
                get
                {
                    return mInstance.BrochureName;
                }
                set
                {
                    mInstance.BrochureName = value;
                }
            }


            /// <summary>
            /// Url.
            /// </summary>
            public string Url
            {
                get
                {
                    return mInstance.Url;
                }
                set
                {
                    mInstance.Url = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="BrochureSignupItem" /> class.
        /// </summary>
        public BrochureSignupItem() : base(CLASS_NAME)
        {
            mFields = new BrochureSignupItemFields(this);
        }

        #endregion
    }
}