//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.Forms;
using CMS.OnlineForms;

[assembly: RegisterBizForm(BrochureOrderItem.CLASS_NAME, typeof(BrochureOrderItem))]

namespace ETG.Core.Forms
{
    /// <summary>
    /// Represents a content item of type BrochureOrderItem.
    /// </summary>
    public partial class BrochureOrderItem : BizFormItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BizForm.BrochureOrder";


        /// <summary>
        /// The instance of the class that provides extended API for working with BrochureOrderItem fields.
        /// </summary>
        private readonly BrochureOrderItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// First Name.
        /// </summary>
        [DatabaseField]
        public string FirstName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FirstName"), @"");
            }
            set
            {
                SetValue("FirstName", value);
            }
        }


        /// <summary>
        /// Last Name.
        /// </summary>
        [DatabaseField]
        public string LastName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LastName"), @"");
            }
            set
            {
                SetValue("LastName", value);
            }
        }


        /// <summary>
        /// Phone.
        /// </summary>
        [DatabaseField]
        public string Phone
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Phone"), @"");
            }
            set
            {
                SetValue("Phone", value);
            }
        }


        /// <summary>
        /// Email.
        /// </summary>
        [DatabaseField]
        public string Email
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Email"), @"");
            }
            set
            {
                SetValue("Email", value);
            }
        }


        /// <summary>
        /// Message.
        /// </summary>
        [DatabaseField]
        public string Message
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Message"), @"");
            }
            set
            {
                SetValue("Message", value);
            }
        }


        /// <summary>
        /// Brochure Orders.
        /// </summary>
        [DatabaseField]
        public string BrochureOrders
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BrochureOrders"), @"");
            }
            set
            {
                SetValue("BrochureOrders", value);
            }
        }


        /// <summary>
        /// Brochure Orders Guid.
        /// </summary>
        [DatabaseField]
        public string BrochureOrdersGUIDs
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BrochureOrdersGUIDs"), @"");
            }
            set
            {
                SetValue("BrochureOrdersGUIDs", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with BrochureOrderItem fields.
        /// </summary>
        [RegisterProperty]
        public BrochureOrderItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with BrochureOrderItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class BrochureOrderItemFields : AbstractHierarchicalObject<BrochureOrderItemFields>
        {
            /// <summary>
            /// The content item of type BrochureOrderItem that is a target of the extended API.
            /// </summary>
            private readonly BrochureOrderItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="BrochureOrderItemFields" /> class with the specified content item of type BrochureOrderItem.
            /// </summary>
            /// <param name="instance">The content item of type BrochureOrderItem that is a target of the extended API.</param>
            public BrochureOrderItemFields(BrochureOrderItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// First Name.
            /// </summary>
            public string FirstName
            {
                get
                {
                    return mInstance.FirstName;
                }
                set
                {
                    mInstance.FirstName = value;
                }
            }


            /// <summary>
            /// Last Name.
            /// </summary>
            public string LastName
            {
                get
                {
                    return mInstance.LastName;
                }
                set
                {
                    mInstance.LastName = value;
                }
            }


            /// <summary>
            /// Phone.
            /// </summary>
            public string Phone
            {
                get
                {
                    return mInstance.Phone;
                }
                set
                {
                    mInstance.Phone = value;
                }
            }


            /// <summary>
            /// Email.
            /// </summary>
            public string Email
            {
                get
                {
                    return mInstance.Email;
                }
                set
                {
                    mInstance.Email = value;
                }
            }


            /// <summary>
            /// Message.
            /// </summary>
            public string Message
            {
                get
                {
                    return mInstance.Message;
                }
                set
                {
                    mInstance.Message = value;
                }
            }


            /// <summary>
            /// Brochure Orders.
            /// </summary>
            public string BrochureOrders
            {
                get
                {
                    return mInstance.BrochureOrders;
                }
                set
                {
                    mInstance.BrochureOrders = value;
                }
            }


            /// <summary>
            /// Brochure Orders Guid.
            /// </summary>
            public string BrochureOrdersGUIDs
            {
                get
                {
                    return mInstance.BrochureOrdersGUIDs;
                }
                set
                {
                    mInstance.BrochureOrdersGUIDs = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="BrochureOrderItem" /> class.
        /// </summary>
        public BrochureOrderItem() : base(CLASS_NAME)
        {
            mFields = new BrochureOrderItemFields(this);
        }

        #endregion
    }
}