//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.Forms;
using CMS.OnlineForms;

[assembly: RegisterBizForm(CareerRoleApplicationItem.CLASS_NAME, typeof(CareerRoleApplicationItem))]

namespace ETG.Core.Forms
{
    /// <summary>
    /// Represents a content item of type CareerRoleApplicationItem.
    /// </summary>
    public partial class CareerRoleApplicationItem : BizFormItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BizForm.CareerRoleApplication";


        /// <summary>
        /// The instance of the class that provides extended API for working with CareerRoleApplicationItem fields.
        /// </summary>
        private readonly CareerRoleApplicationItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// First Name.
        /// </summary>
        [DatabaseField]
        public string FirstName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FirstName"), @"");
            }
            set
            {
                SetValue("FirstName", value);
            }
        }


        /// <summary>
        /// Last Name.
        /// </summary>
        [DatabaseField]
        public string LastName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LastName"), @"");
            }
            set
            {
                SetValue("LastName", value);
            }
        }


        /// <summary>
        /// Phone.
        /// </summary>
        [DatabaseField]
        public string Phone
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Phone"), @"");
            }
            set
            {
                SetValue("Phone", value);
            }
        }


        /// <summary>
        /// Email.
        /// </summary>
        [DatabaseField]
        public string Email
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Email"), @"");
            }
            set
            {
                SetValue("Email", value);
            }
        }


        /// <summary>
        /// Preferred Contact Method.
        /// </summary>
        [DatabaseField]
        public string PreferredContactMethod
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PreferredContactMethod"), @"");
            }
            set
            {
                SetValue("PreferredContactMethod", value);
            }
        }


        /// <summary>
        /// Question or Comments.
        /// </summary>
        [DatabaseField]
        public string Comments
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Comments"), @"");
            }
            set
            {
                SetValue("Comments", value);
            }
        }


        /// <summary>
        /// CVFilePath.
        /// </summary>
        [DatabaseField]
        public string CVFilePath
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CVFilePath"), @"");
            }
            set
            {
                SetValue("CVFilePath", value);
            }
        }


        /// <summary>
        /// Role.
        /// </summary>
        [DatabaseField]
        public string Role
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Role"), @"");
            }
            set
            {
                SetValue("Role", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CareerRoleApplicationItem fields.
        /// </summary>
        [RegisterProperty]
        public CareerRoleApplicationItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CareerRoleApplicationItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CareerRoleApplicationItemFields : AbstractHierarchicalObject<CareerRoleApplicationItemFields>
        {
            /// <summary>
            /// The content item of type CareerRoleApplicationItem that is a target of the extended API.
            /// </summary>
            private readonly CareerRoleApplicationItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CareerRoleApplicationItemFields" /> class with the specified content item of type CareerRoleApplicationItem.
            /// </summary>
            /// <param name="instance">The content item of type CareerRoleApplicationItem that is a target of the extended API.</param>
            public CareerRoleApplicationItemFields(CareerRoleApplicationItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// First Name.
            /// </summary>
            public string FirstName
            {
                get
                {
                    return mInstance.FirstName;
                }
                set
                {
                    mInstance.FirstName = value;
                }
            }


            /// <summary>
            /// Last Name.
            /// </summary>
            public string LastName
            {
                get
                {
                    return mInstance.LastName;
                }
                set
                {
                    mInstance.LastName = value;
                }
            }


            /// <summary>
            /// Phone.
            /// </summary>
            public string Phone
            {
                get
                {
                    return mInstance.Phone;
                }
                set
                {
                    mInstance.Phone = value;
                }
            }


            /// <summary>
            /// Email.
            /// </summary>
            public string Email
            {
                get
                {
                    return mInstance.Email;
                }
                set
                {
                    mInstance.Email = value;
                }
            }


            /// <summary>
            /// Preferred Contact Method.
            /// </summary>
            public string PreferredContactMethod
            {
                get
                {
                    return mInstance.PreferredContactMethod;
                }
                set
                {
                    mInstance.PreferredContactMethod = value;
                }
            }


            /// <summary>
            /// Question or Comments.
            /// </summary>
            public string Comments
            {
                get
                {
                    return mInstance.Comments;
                }
                set
                {
                    mInstance.Comments = value;
                }
            }


            /// <summary>
            /// CVFilePath.
            /// </summary>
            public string CVFilePath
            {
                get
                {
                    return mInstance.CVFilePath;
                }
                set
                {
                    mInstance.CVFilePath = value;
                }
            }


            /// <summary>
            /// Role.
            /// </summary>
            public string Role
            {
                get
                {
                    return mInstance.Role;
                }
                set
                {
                    mInstance.Role = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CareerRoleApplicationItem" /> class.
        /// </summary>
        public CareerRoleApplicationItem() : base(CLASS_NAME)
        {
            mFields = new CareerRoleApplicationItemFields(this);
        }

        #endregion
    }
}