//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.Forms;
using CMS.OnlineForms;

[assembly: RegisterBizForm(CompetitionItem.CLASS_NAME, typeof(CompetitionItem))]

namespace ETG.Core.Forms
{
	/// <summary>
	/// Represents a content item of type CompetitionItem.
	/// </summary>
	public partial class CompetitionItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.Competition";


		/// <summary>
		/// The instance of the class that provides extended API for working with CompetitionItem fields.
		/// </summary>
		private readonly CompetitionItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// First name.
		/// </summary>
		[DatabaseField]
		public string FirstName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FirstName"), @"");
			}
			set
			{
				SetValue("FirstName", value);
			}
		}


		/// <summary>
		/// Last name.
		/// </summary>
		[DatabaseField]
		public string LastName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LastName"), @"");
			}
			set
			{
				SetValue("LastName", value);
			}
		}


		/// <summary>
		/// Email Address.
		/// </summary>
		[DatabaseField]
		public string EmailAddress
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EmailAddress"), @"");
			}
			set
			{
				SetValue("EmailAddress", value);
			}
		}


		/// <summary>
		/// Is Travel Agent?.
		/// </summary>
		[DatabaseField]
		public bool IsTravelAgent
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsTravelAgent"), false);
			}
			set
			{
				SetValue("IsTravelAgent", value);
			}
		}


		/// <summary>
		/// Has Previously Subscribed.
		/// </summary>
		[DatabaseField]
		public bool HasPreviouslySubscribed
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("HasPreviouslySubscribed"), false);
			}
			set
			{
				SetValue("HasPreviouslySubscribed", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CompetitionItem fields.
		/// </summary>
		[RegisterProperty]
		public CompetitionItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CompetitionItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CompetitionItemFields : AbstractHierarchicalObject<CompetitionItemFields>
		{
			/// <summary>
			/// The content item of type CompetitionItem that is a target of the extended API.
			/// </summary>
			private readonly CompetitionItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CompetitionItemFields" /> class with the specified content item of type CompetitionItem.
			/// </summary>
			/// <param name="instance">The content item of type CompetitionItem that is a target of the extended API.</param>
			public CompetitionItemFields(CompetitionItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// First name.
			/// </summary>
			public string FirstName
			{
				get
				{
					return mInstance.FirstName;
				}
				set
				{
					mInstance.FirstName = value;
				}
			}


			/// <summary>
			/// Last name.
			/// </summary>
			public string LastName
			{
				get
				{
					return mInstance.LastName;
				}
				set
				{
					mInstance.LastName = value;
				}
			}


			/// <summary>
			/// Email Address.
			/// </summary>
			public string EmailAddress
			{
				get
				{
					return mInstance.EmailAddress;
				}
				set
				{
					mInstance.EmailAddress = value;
				}
			}


			/// <summary>
			/// Is Travel Agent?.
			/// </summary>
			public bool IsTravelAgent
			{
				get
				{
					return mInstance.IsTravelAgent;
				}
				set
				{
					mInstance.IsTravelAgent = value;
				}
			}


			/// <summary>
			/// Has Previously Subscribed.
			/// </summary>
			public bool HasPreviouslySubscribed
			{
				get
				{
					return mInstance.HasPreviouslySubscribed;
				}
				set
				{
					mInstance.HasPreviouslySubscribed = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CompetitionItem" /> class.
		/// </summary>
		public CompetitionItem() : base(CLASS_NAME)
		{
			mFields = new CompetitionItemFields(this);
		}

		#endregion
	}
}