//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using ETG.Core.Forms;

[assembly: RegisterBizForm(FacebookLeadsItem.CLASS_NAME, typeof(FacebookLeadsItem))]

namespace ETG.Core.Forms
{
    /// <summary>
    /// Represents a content item of type FacebookLeadsItem.
    /// </summary>
    public partial class FacebookLeadsItem : BizFormItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BizForm.FacebookLeads";


        /// <summary>
        /// The instance of the class that provides extended API for working with FacebookLeadsItem fields.
        /// </summary>
        private readonly FacebookLeadsItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// First Name.
        /// </summary>
        [DatabaseField]
        public string FirstName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FirstName"), @"");
            }
            set
            {
                SetValue("FirstName", value);
            }
        }


        /// <summary>
        /// Last Name.
        /// </summary>
        [DatabaseField]
        public string LastName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LastName"), @"");
            }
            set
            {
                SetValue("LastName", value);
            }
        }


        /// <summary>
        /// Email.
        /// </summary>
        [DatabaseField]
        public string Email
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Email"), @"");
            }
            set
            {
                SetValue("Email", value);
            }
        }


        /// <summary>
        /// Travel Agent?.
        /// </summary>
        [DatabaseField]
        public string TravelAgent
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TravelAgent"), @"");
            }
            set
            {
                SetValue("TravelAgent", value);
            }
        }


        /// <summary>
        /// Ad Name.
        /// </summary>
        [DatabaseField]
        public string AdName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AdName"), @"");
            }
            set
            {
                SetValue("AdName", value);
            }
        }


        /// <summary>
        /// Adset Name.
        /// </summary>
        [DatabaseField]
        public string AdsetName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AdsetName"), @"");
            }
            set
            {
                SetValue("AdsetName", value);
            }
        }


        /// <summary>
        /// Ad Id.
        /// </summary>
        [DatabaseField]
        public string AdId
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AdId"), @"");
            }
            set
            {
                SetValue("AdId", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with FacebookLeadsItem fields.
        /// </summary>
        [RegisterProperty]
        public FacebookLeadsItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with FacebookLeadsItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class FacebookLeadsItemFields : AbstractHierarchicalObject<FacebookLeadsItemFields>
        {
            /// <summary>
            /// The content item of type FacebookLeadsItem that is a target of the extended API.
            /// </summary>
            private readonly FacebookLeadsItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="FacebookLeadsItemFields" /> class with the specified content item of type FacebookLeadsItem.
            /// </summary>
            /// <param name="instance">The content item of type FacebookLeadsItem that is a target of the extended API.</param>
            public FacebookLeadsItemFields(FacebookLeadsItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// First Name.
            /// </summary>
            public string FirstName
            {
                get
                {
                    return mInstance.FirstName;
                }
                set
                {
                    mInstance.FirstName = value;
                }
            }


            /// <summary>
            /// Last Name.
            /// </summary>
            public string LastName
            {
                get
                {
                    return mInstance.LastName;
                }
                set
                {
                    mInstance.LastName = value;
                }
            }


            /// <summary>
            /// Email.
            /// </summary>
            public string Email
            {
                get
                {
                    return mInstance.Email;
                }
                set
                {
                    mInstance.Email = value;
                }
            }


            /// <summary>
            /// Travel Agent?.
            /// </summary>
            public string TravelAgent
            {
                get
                {
                    return mInstance.TravelAgent;
                }
                set
                {
                    mInstance.TravelAgent = value;
                }
            }


            /// <summary>
            /// Ad Name.
            /// </summary>
            public string AdName
            {
                get
                {
                    return mInstance.AdName;
                }
                set
                {
                    mInstance.AdName = value;
                }
            }


            /// <summary>
            /// Adset Name.
            /// </summary>
            public string AdsetName
            {
                get
                {
                    return mInstance.AdsetName;
                }
                set
                {
                    mInstance.AdsetName = value;
                }
            }


            /// <summary>
            /// Ad Id.
            /// </summary>
            public string AdId
            {
                get
                {
                    return mInstance.AdId;
                }
                set
                {
                    mInstance.AdId = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="FacebookLeadsItem" /> class.
        /// </summary>
        public FacebookLeadsItem() : base(CLASS_NAME)
        {
            mFields = new FacebookLeadsItemFields(this);
        }

        #endregion
    }
}