//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(AccordionItem.CLASS_NAME, typeof(AccordionItem))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type AccordionItem.
    /// </summary>
    public partial class AccordionItem : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.AccordionItem";


        /// <summary>
        /// The instance of the class that provides extended API for working with AccordionItem fields.
        /// </summary>
        private readonly AccordionItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// AccordionItemID.
        /// </summary>
        [DatabaseIDField]
        public int AccordionItemID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("AccordionItemID"), 0);
            }
            set
            {
                SetValue("AccordionItemID", value);
            }
        }


        /// <summary>
        /// Heading.
        /// </summary>
        [DatabaseField]
        public string AccordionHeading
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AccordionHeading"), @"");
            }
            set
            {
                SetValue("AccordionHeading", value);
            }
        }


        /// <summary>
        /// Contents.
        /// </summary>
        [DatabaseField]
        public string AccordionContents
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AccordionContents"), @"");
            }
            set
            {
                SetValue("AccordionContents", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with AccordionItem fields.
        /// </summary>
        [RegisterProperty]
        public AccordionItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with AccordionItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class AccordionItemFields : AbstractHierarchicalObject<AccordionItemFields>
        {
            /// <summary>
            /// The content item of type AccordionItem that is a target of the extended API.
            /// </summary>
            private readonly AccordionItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="AccordionItemFields" /> class with the specified content item of type AccordionItem.
            /// </summary>
            /// <param name="instance">The content item of type AccordionItem that is a target of the extended API.</param>
            public AccordionItemFields(AccordionItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// AccordionItemID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.AccordionItemID;
                }
                set
                {
                    mInstance.AccordionItemID = value;
                }
            }


            /// <summary>
            /// Heading.
            /// </summary>
            public string AccordionHeading
            {
                get
                {
                    return mInstance.AccordionHeading;
                }
                set
                {
                    mInstance.AccordionHeading = value;
                }
            }


            /// <summary>
            /// Contents.
            /// </summary>
            public string AccordionContents
            {
                get
                {
                    return mInstance.AccordionContents;
                }
                set
                {
                    mInstance.AccordionContents = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="AccordionItem" /> class.
        /// </summary>
        public AccordionItem() : base(CLASS_NAME)
        {
            mFields = new AccordionItemFields(this);
        }

        #endregion
    }
}