//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(AgentPortalMainPage.CLASS_NAME, typeof(AgentPortalMainPage))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type AgentPortalMainPage.
	/// </summary>
	public partial class AgentPortalMainPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.AgentPortalMainPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with AgentPortalMainPage fields.
		/// </summary>
		private readonly AgentPortalMainPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AgentPortalMainPageID.
		/// </summary>
		[DatabaseIDField]
		public int AgentPortalMainPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AgentPortalMainPageID"), 0);
			}
			set
			{
				SetValue("AgentPortalMainPageID", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string AgentPortalHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalHeading"), @"");
			}
			set
			{
				SetValue("AgentPortalHeading", value);
			}
		}


		/// <summary>
		/// Main Description.
		/// </summary>
		[DatabaseField]
		public string AgentPortalMainDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalMainDescription"), @"");
			}
			set
			{
				SetValue("AgentPortalMainDescription", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string AgentPortalPaymentsHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalPaymentsHeading"), @"");
			}
			set
			{
				SetValue("AgentPortalPaymentsHeading", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string AgentPortalPaymentsDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalPaymentsDescription"), @"");
			}
			set
			{
				SetValue("AgentPortalPaymentsDescription", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string AgentPortalTookitHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalTookitHeading"), @"");
			}
			set
			{
				SetValue("AgentPortalTookitHeading", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string AgentPortalToolkitDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalToolkitDescription"), @"");
			}
			set
			{
				SetValue("AgentPortalToolkitDescription", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string AgentPortalIncentiveHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalIncentiveHeading"), @"");
			}
			set
			{
				SetValue("AgentPortalIncentiveHeading", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string AgentPortalIncentiveDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalIncentiveDescription"), @"");
			}
			set
			{
				SetValue("AgentPortalIncentiveDescription", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string AgentPortalWebinarHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalWebinarHeading"), @"");
			}
			set
			{
				SetValue("AgentPortalWebinarHeading", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string AgentPortalWebinarDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalWebinarDescription"), @"");
			}
			set
			{
				SetValue("AgentPortalWebinarDescription", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string AgentPortalBookingHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalBookingHeading"), @"");
			}
			set
			{
				SetValue("AgentPortalBookingHeading", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string AgentPortalBookingDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalBookingDescription"), @"");
			}
			set
			{
				SetValue("AgentPortalBookingDescription", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string AgentPortalBookingOptionsHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalBookingOptionsHeading"), @"");
			}
			set
			{
				SetValue("AgentPortalBookingOptionsHeading", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string AgentPortalBookingOptionsDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalBookingOptionsDescription"), @"");
			}
			set
			{
				SetValue("AgentPortalBookingOptionsDescription", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string AgentPortalInstructionHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalInstructionHeading"), @"");
			}
			set
			{
				SetValue("AgentPortalInstructionHeading", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string AgentPortalInstructionDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AgentPortalInstructionDescription"), @"");
			}
			set
			{
				SetValue("AgentPortalInstructionDescription", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AgentPortalMainPage fields.
		/// </summary>
		[RegisterProperty]
		public AgentPortalMainPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AgentPortalMainPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AgentPortalMainPageFields : AbstractHierarchicalObject<AgentPortalMainPageFields>
		{
			/// <summary>
			/// The content item of type AgentPortalMainPage that is a target of the extended API.
			/// </summary>
			private readonly AgentPortalMainPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AgentPortalMainPageFields" /> class with the specified content item of type AgentPortalMainPage.
			/// </summary>
			/// <param name="instance">The content item of type AgentPortalMainPage that is a target of the extended API.</param>
			public AgentPortalMainPageFields(AgentPortalMainPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AgentPortalMainPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AgentPortalMainPageID;
				}
				set
				{
					mInstance.AgentPortalMainPageID = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string AgentPortalHeading
			{
				get
				{
					return mInstance.AgentPortalHeading;
				}
				set
				{
					mInstance.AgentPortalHeading = value;
				}
			}


			/// <summary>
			/// Main Description.
			/// </summary>
			public string AgentPortalMainDescription
			{
				get
				{
					return mInstance.AgentPortalMainDescription;
				}
				set
				{
					mInstance.AgentPortalMainDescription = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string AgentPortalPaymentsHeading
			{
				get
				{
					return mInstance.AgentPortalPaymentsHeading;
				}
				set
				{
					mInstance.AgentPortalPaymentsHeading = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string AgentPortalPaymentsDescription
			{
				get
				{
					return mInstance.AgentPortalPaymentsDescription;
				}
				set
				{
					mInstance.AgentPortalPaymentsDescription = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string AgentPortalTookitHeading
			{
				get
				{
					return mInstance.AgentPortalTookitHeading;
				}
				set
				{
					mInstance.AgentPortalTookitHeading = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string AgentPortalToolkitDescription
			{
				get
				{
					return mInstance.AgentPortalToolkitDescription;
				}
				set
				{
					mInstance.AgentPortalToolkitDescription = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string AgentPortalIncentiveHeading
			{
				get
				{
					return mInstance.AgentPortalIncentiveHeading;
				}
				set
				{
					mInstance.AgentPortalIncentiveHeading = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string AgentPortalIncentiveDescription
			{
				get
				{
					return mInstance.AgentPortalIncentiveDescription;
				}
				set
				{
					mInstance.AgentPortalIncentiveDescription = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string AgentPortalWebinarHeading
			{
				get
				{
					return mInstance.AgentPortalWebinarHeading;
				}
				set
				{
					mInstance.AgentPortalWebinarHeading = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string AgentPortalWebinarDescription
			{
				get
				{
					return mInstance.AgentPortalWebinarDescription;
				}
				set
				{
					mInstance.AgentPortalWebinarDescription = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string AgentPortalBookingHeading
			{
				get
				{
					return mInstance.AgentPortalBookingHeading;
				}
				set
				{
					mInstance.AgentPortalBookingHeading = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string AgentPortalBookingDescription
			{
				get
				{
					return mInstance.AgentPortalBookingDescription;
				}
				set
				{
					mInstance.AgentPortalBookingDescription = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string AgentPortalBookingOptionsHeading
			{
				get
				{
					return mInstance.AgentPortalBookingOptionsHeading;
				}
				set
				{
					mInstance.AgentPortalBookingOptionsHeading = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string AgentPortalBookingOptionsDescription
			{
				get
				{
					return mInstance.AgentPortalBookingOptionsDescription;
				}
				set
				{
					mInstance.AgentPortalBookingOptionsDescription = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string AgentPortalInstructionHeading
			{
				get
				{
					return mInstance.AgentPortalInstructionHeading;
				}
				set
				{
					mInstance.AgentPortalInstructionHeading = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string AgentPortalInstructionDescription
			{
				get
				{
					return mInstance.AgentPortalInstructionDescription;
				}
				set
				{
					mInstance.AgentPortalInstructionDescription = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AgentPortalMainPage" /> class.
		/// </summary>
		public AgentPortalMainPage() : base(CLASS_NAME)
		{
			mFields = new AgentPortalMainPageFields(this);
		}

		#endregion
	}
}