//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Article.CLASS_NAME, typeof(Article))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type Article.
	/// </summary>
	public partial class Article : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.Article";


		/// <summary>
		/// The instance of the class that provides extended API for working with Article fields.
		/// </summary>
		private readonly ArticleFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ArticleID.
		/// </summary>
		[DatabaseIDField]
		public int ArticleID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ArticleID"), 0);
			}
			set
			{
				SetValue("ArticleID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string ArticleTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ArticleTitle"), @"");
			}
			set
			{
				SetValue("ArticleTitle", value);
			}
		}


		/// <summary>
		/// Summary.
		/// </summary>
		[DatabaseField]
		public string ArticleSummary
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ArticleSummary"), @"");
			}
			set
			{
				SetValue("ArticleSummary", value);
			}
		}


		/// <summary>
		/// Hero Image.
		/// </summary>
		[DatabaseField]
		public string ArticleHeroImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ArticleHeroImage"), @"");
			}
			set
			{
				SetValue("ArticleHeroImage", value);
			}
		}


		/// <summary>
		/// Hero alt tag.
		/// </summary>
		[DatabaseField]
		public string ArticleHeroImageAltTag
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ArticleHeroImageAltTag"), @"");
			}
			set
			{
				SetValue("ArticleHeroImageAltTag", value);
			}
		}


		/// <summary>
		/// Author.
		/// </summary>
		[DatabaseField]
		public Guid ArticleAuthor
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("ArticleAuthor"), Guid.Empty);
			}
			set
			{
				SetValue("ArticleAuthor", value);
			}
		}


		/// <summary>
		/// Categories.
		/// </summary>
		[DatabaseField]
		public string ArticleCategories
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ArticleCategories"), @"");
			}
			set
			{
				SetValue("ArticleCategories", value);
			}
		}


		/// <summary>
		/// Destinations.
		/// </summary>
		[DatabaseField]
		public string ArticleDestinations
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ArticleDestinations"), @"");
			}
			set
			{
				SetValue("ArticleDestinations", value);
			}
		}


		/// <summary>
		/// Experiences.
		/// </summary>
		[DatabaseField]
		public string ArticleExperiences
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ArticleExperiences"), @"");
			}
			set
			{
				SetValue("ArticleExperiences", value);
			}
		}


		/// <summary>
		/// Publish Date.
		/// </summary>
		[DatabaseField]
		public DateTime ArticleDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("ArticleDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("ArticleDate", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Article fields.
		/// </summary>
		[RegisterProperty]
		public ArticleFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Article fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ArticleFields : AbstractHierarchicalObject<ArticleFields>
		{
			/// <summary>
			/// The content item of type Article that is a target of the extended API.
			/// </summary>
			private readonly Article mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ArticleFields" /> class with the specified content item of type Article.
			/// </summary>
			/// <param name="instance">The content item of type Article that is a target of the extended API.</param>
			public ArticleFields(Article instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ArticleID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ArticleID;
				}
				set
				{
					mInstance.ArticleID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.ArticleTitle;
				}
				set
				{
					mInstance.ArticleTitle = value;
				}
			}


			/// <summary>
			/// Summary.
			/// </summary>
			public string Summary
			{
				get
				{
					return mInstance.ArticleSummary;
				}
				set
				{
					mInstance.ArticleSummary = value;
				}
			}


			/// <summary>
			/// Hero Image.
			/// </summary>
			public string HeroImage
			{
				get
				{
					return mInstance.ArticleHeroImage;
				}
				set
				{
					mInstance.ArticleHeroImage = value;
				}
			}


			/// <summary>
			/// Hero alt tag.
			/// </summary>
			public string HeroImageAltTag
			{
				get
				{
					return mInstance.ArticleHeroImageAltTag;
				}
				set
				{
					mInstance.ArticleHeroImageAltTag = value;
				}
			}


			/// <summary>
			/// Author.
			/// </summary>
			public Guid Author
			{
				get
				{
					return mInstance.ArticleAuthor;
				}
				set
				{
					mInstance.ArticleAuthor = value;
				}
			}


			/// <summary>
			/// Categories.
			/// </summary>
			public string Categories
			{
				get
				{
					return mInstance.ArticleCategories;
				}
				set
				{
					mInstance.ArticleCategories = value;
				}
			}


			/// <summary>
			/// Destinations.
			/// </summary>
			public string Destinations
			{
				get
				{
					return mInstance.ArticleDestinations;
				}
				set
				{
					mInstance.ArticleDestinations = value;
				}
			}


			/// <summary>
			/// Experiences.
			/// </summary>
			public string Experiences
			{
				get
				{
					return mInstance.ArticleExperiences;
				}
				set
				{
					mInstance.ArticleExperiences = value;
				}
			}


			/// <summary>
			/// Publish Date.
			/// </summary>
			public DateTime Date
			{
				get
				{
					return mInstance.ArticleDate;
				}
				set
				{
					mInstance.ArticleDate = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Article" /> class.
		/// </summary>
		public Article() : base(CLASS_NAME)
		{
			mFields = new ArticleFields(this);
		}

		#endregion
	}
}