//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Brochure.CLASS_NAME, typeof(Brochure))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type Brochure.
	/// </summary>
	public partial class Brochure : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.Brochure";


		/// <summary>
		/// The instance of the class that provides extended API for working with Brochure fields.
		/// </summary>
		private readonly BrochureFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BrochureID.
		/// </summary>
		[DatabaseIDField]
		public int BrochureID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BrochureID"), 0);
			}
			set
			{
				SetValue("BrochureID", value);
			}
		}


		/// <summary>
		/// Is ComingSoon?.
		/// </summary>
		[DatabaseField]
		public bool IsComingSoon
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsComingSoon"), false);
			}
			set
			{
				SetValue("IsComingSoon", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string BrochureName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BrochureName"), @"");
			}
			set
			{
				SetValue("BrochureName", value);
			}
		}


		/// <summary>
		/// Cover Image.
		/// </summary>
		[DatabaseField]
		public string BrochureCoverImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BrochureCoverImage"), @"");
			}
			set
			{
				SetValue("BrochureCoverImage", value);
			}
		}


		/// <summary>
		/// File.
		/// </summary>
		[DatabaseField]
		public string BrochureFile
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BrochureFile"), @"");
			}
			set
			{
				SetValue("BrochureFile", value);
			}
		}


		/// <summary>
		/// Issu Link.
		/// </summary>
		[DatabaseField]
		public string BrochureIssuuLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BrochureIssuuLink"), @"");
			}
			set
			{
				SetValue("BrochureIssuuLink", value);
			}
		}


		/// <summary>
		/// Flipsnack ID.
		/// </summary>
		[DatabaseField]
		public string BrochureFlipStackID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BrochureFlipStackID"), @"");
			}
			set
			{
				SetValue("BrochureFlipStackID", value);
			}
		}


		/// <summary>
		/// Agent Purchase Link.
		/// </summary>
		[DatabaseField]
		public string BrochureAgentPurchaseLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BrochureAgentPurchaseLink"), @"");
			}
			set
			{
				SetValue("BrochureAgentPurchaseLink", value);
			}
		}


		/// <summary>
		/// Destinations.
		/// </summary>
		[DatabaseField]
		public string Destinations
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Destinations"), @"");
			}
			set
			{
				SetValue("Destinations", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Brochure fields.
		/// </summary>
		[RegisterProperty]
		public BrochureFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Brochure fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BrochureFields : AbstractHierarchicalObject<BrochureFields>
		{
			/// <summary>
			/// The content item of type Brochure that is a target of the extended API.
			/// </summary>
			private readonly Brochure mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BrochureFields" /> class with the specified content item of type Brochure.
			/// </summary>
			/// <param name="instance">The content item of type Brochure that is a target of the extended API.</param>
			public BrochureFields(Brochure instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BrochureID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BrochureID;
				}
				set
				{
					mInstance.BrochureID = value;
				}
			}


			/// <summary>
			/// Is ComingSoon?.
			/// </summary>
			public bool IsComingSoon
			{
				get
				{
					return mInstance.IsComingSoon;
				}
				set
				{
					mInstance.IsComingSoon = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.BrochureName;
				}
				set
				{
					mInstance.BrochureName = value;
				}
			}


			/// <summary>
			/// Cover Image.
			/// </summary>
			public string CoverImage
			{
				get
				{
					return mInstance.BrochureCoverImage;
				}
				set
				{
					mInstance.BrochureCoverImage = value;
				}
			}


			/// <summary>
			/// File.
			/// </summary>
			public string File
			{
				get
				{
					return mInstance.BrochureFile;
				}
				set
				{
					mInstance.BrochureFile = value;
				}
			}


			/// <summary>
			/// Issu Link.
			/// </summary>
			public string IssuuLink
			{
				get
				{
					return mInstance.BrochureIssuuLink;
				}
				set
				{
					mInstance.BrochureIssuuLink = value;
				}
			}


			/// <summary>
			/// Flipsnack ID.
			/// </summary>
			public string FlipStackID
			{
				get
				{
					return mInstance.BrochureFlipStackID;
				}
				set
				{
					mInstance.BrochureFlipStackID = value;
				}
			}


			/// <summary>
			/// Agent Purchase Link.
			/// </summary>
			public string AgentPurchaseLink
			{
				get
				{
					return mInstance.BrochureAgentPurchaseLink;
				}
				set
				{
					mInstance.BrochureAgentPurchaseLink = value;
				}
			}


			/// <summary>
			/// Destinations.
			/// </summary>
			public string Destinations
			{
				get
				{
					return mInstance.Destinations;
				}
				set
				{
					mInstance.Destinations = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Brochure" /> class.
		/// </summary>
		public Brochure() : base(CLASS_NAME)
		{
			mFields = new BrochureFields(this);
		}

		#endregion
	}
}