//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CareerRole.CLASS_NAME, typeof(CareerRole))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type CareerRole.
    /// </summary>
    public partial class CareerRole : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.CareerRole";


        /// <summary>
        /// The instance of the class that provides extended API for working with CareerRole fields.
        /// </summary>
        private readonly CareerRoleFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// CareerRoleID.
        /// </summary>
        [DatabaseIDField]
        public int CareerRoleID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("CareerRoleID"), 0);
            }
            set
            {
                SetValue("CareerRoleID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string CareerRoleTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CareerRoleTitle"), @"");
            }
            set
            {
                SetValue("CareerRoleTitle", value);
            }
        }


        /// <summary>
        /// Location.
        /// </summary>
        [DatabaseField]
        public string CareerRoleLocation
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CareerRoleLocation"), @"");
            }
            set
            {
                SetValue("CareerRoleLocation", value);
            }
        }


        /// <summary>
        /// Position Type.
        /// </summary>
        [DatabaseField]
        public string CareerRolePositionType
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CareerRolePositionType"), @"");
            }
            set
            {
                SetValue("CareerRolePositionType", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string CareerRoleDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CareerRoleDescription"), @"");
            }
            set
            {
                SetValue("CareerRoleDescription", value);
            }
        }


        /// <summary>
        /// Summary of position.
        /// </summary>
        [DatabaseField]
        public string CareerRoleSummaryOfPosition
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CareerRoleSummaryOfPosition"), @"");
            }
            set
            {
                SetValue("CareerRoleSummaryOfPosition", value);
            }
        }


        /// <summary>
        /// Duties and Responsibilities.
        /// </summary>
        [DatabaseField]
        public string CareerRoleDutiesAndResponsibilities
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CareerRoleDutiesAndResponsibilities"), @"");
            }
            set
            {
                SetValue("CareerRoleDutiesAndResponsibilities", value);
            }
        }


        /// <summary>
        /// Address.
        /// </summary>
        [DatabaseField]
        public string CareerRoleAddress
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CareerRoleAddress"), @"");
            }
            set
            {
                SetValue("CareerRoleAddress", value);
            }
        }


        /// <summary>
        /// State.
        /// </summary>
        [DatabaseField]
        public string CareerRoleState
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CareerRoleState"), @"");
            }
            set
            {
                SetValue("CareerRoleState", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CareerRole fields.
        /// </summary>
        [RegisterProperty]
        public CareerRoleFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CareerRole fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CareerRoleFields : AbstractHierarchicalObject<CareerRoleFields>
        {
            /// <summary>
            /// The content item of type CareerRole that is a target of the extended API.
            /// </summary>
            private readonly CareerRole mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CareerRoleFields" /> class with the specified content item of type CareerRole.
            /// </summary>
            /// <param name="instance">The content item of type CareerRole that is a target of the extended API.</param>
            public CareerRoleFields(CareerRole instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// CareerRoleID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.CareerRoleID;
                }
                set
                {
                    mInstance.CareerRoleID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.CareerRoleTitle;
                }
                set
                {
                    mInstance.CareerRoleTitle = value;
                }
            }


            /// <summary>
            /// Location.
            /// </summary>
            public string Location
            {
                get
                {
                    return mInstance.CareerRoleLocation;
                }
                set
                {
                    mInstance.CareerRoleLocation = value;
                }
            }


            /// <summary>
            /// Position Type.
            /// </summary>
            public string PositionType
            {
                get
                {
                    return mInstance.CareerRolePositionType;
                }
                set
                {
                    mInstance.CareerRolePositionType = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.CareerRoleDescription;
                }
                set
                {
                    mInstance.CareerRoleDescription = value;
                }
            }


            /// <summary>
            /// Summary of position.
            /// </summary>
            public string SummaryOfPosition
            {
                get
                {
                    return mInstance.CareerRoleSummaryOfPosition;
                }
                set
                {
                    mInstance.CareerRoleSummaryOfPosition = value;
                }
            }


            /// <summary>
            /// Duties and Responsibilities.
            /// </summary>
            public string DutiesAndResponsibilities
            {
                get
                {
                    return mInstance.CareerRoleDutiesAndResponsibilities;
                }
                set
                {
                    mInstance.CareerRoleDutiesAndResponsibilities = value;
                }
            }


            /// <summary>
            /// Address.
            /// </summary>
            public string Address
            {
                get
                {
                    return mInstance.CareerRoleAddress;
                }
                set
                {
                    mInstance.CareerRoleAddress = value;
                }
            }


            /// <summary>
            /// State.
            /// </summary>
            public string State
            {
                get
                {
                    return mInstance.CareerRoleState;
                }
                set
                {
                    mInstance.CareerRoleState = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CareerRole" /> class.
        /// </summary>
        public CareerRole() : base(CLASS_NAME)
        {
            mFields = new CareerRoleFields(this);
        }

        #endregion
    }
}