//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Container.CLASS_NAME, typeof(Container))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type Container.
	/// </summary>
	public partial class Container : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.Container";


		/// <summary>
		/// The instance of the class that provides extended API for working with Container fields.
		/// </summary>
		private readonly ContainerFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContainerID.
		/// </summary>
		[DatabaseIDField]
		public int ContainerID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContainerID"), 0);
			}
			set
			{
				SetValue("ContainerID", value);
			}
		}


		/// <summary>
		/// Expiration.
		/// </summary>
		[DatabaseField]
		public DateTime ContainerExpiry
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("ContainerExpiry"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("ContainerExpiry", value);
			}
		}


		/// <summary>
		/// On expiry, redirect to.
		/// </summary>
		[DatabaseField]
		public string ContainerRedirect
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerRedirect"), @"");
			}
			set
			{
				SetValue("ContainerRedirect", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string ContainerName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerName"), @"");
			}
			set
			{
				SetValue("ContainerName", value);
			}
		}


		/// <summary>
		/// Is new campaign landing page.
		/// </summary>
		[DatabaseField]
		public bool ContainerIsNewCampaignLandingPage
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("ContainerIsNewCampaignLandingPage"), false);
			}
			set
			{
				SetValue("ContainerIsNewCampaignLandingPage", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string ContainerHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerHeading"), @"");
			}
			set
			{
				SetValue("ContainerHeading", value);
			}
		}


		/// <summary>
		/// Heading Text.
		/// </summary>
		[DatabaseField]
		public string ContainerHeadingText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerHeadingText"), @"");
			}
			set
			{
				SetValue("ContainerHeadingText", value);
			}
		}


		/// <summary>
		/// Hero Image.
		/// </summary>
		[DatabaseField]
		public string ContainerHeroImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerHeroImage"), @"");
			}
			set
			{
				SetValue("ContainerHeroImage", value);
			}
		}


		/// <summary>
		/// Hero Alt Text.
		/// </summary>
		[DatabaseField]
		public string ContainerHeroImageAltTag
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerHeroImageAltTag"), @"");
			}
			set
			{
				SetValue("ContainerHeroImageAltTag", value);
			}
		}


		/// <summary>
		/// Hero Accreditation.
		/// </summary>
		[DatabaseField]
		public string ContainerHeroAccreditation
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerHeroAccreditation"), @"");
			}
			set
			{
				SetValue("ContainerHeroAccreditation", value);
			}
		}


		/// <summary>
		/// Hide Share Button.
		/// </summary>
		[DatabaseField]
		public bool ContainerHideShareButton
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("ContainerHideShareButton"), false);
			}
			set
			{
				SetValue("ContainerHideShareButton", value);
			}
		}


		/// <summary>
		/// Hero contact us path.
		/// </summary>
		[DatabaseField]
		public string ContainerHeroContactUsCtaPath
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerHeroContactUsCtaPath"), @"");
			}
			set
			{
				SetValue("ContainerHeroContactUsCtaPath", value);
			}
		}


		/// <summary>
		/// Hero phone.
		/// </summary>
		[DatabaseField]
		public string ContainerHeroPhone
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerHeroPhone"), @"");
			}
			set
			{
				SetValue("ContainerHeroPhone", value);
			}
		}
		
		/// <summary>
		/// Json Schema.
		/// </summary>
		[DatabaseField]
		public string ContainerJsonSchema
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerJsonSchema"), @"");
			}
			set
			{
				SetValue("ContainerJsonSchema", value);
			}
		}


		/// <summary>
		/// Proof point section title.
		/// </summary>
		[DatabaseField]
		public string ContainerProofPointsTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerProofPointsTitle"), @"");
			}
			set
			{
				SetValue("ContainerProofPointsTitle", value);
			}
		}


		/// <summary>
		/// Proof point section folder (path).
		/// </summary>
		[DatabaseField]
		public string ContainerProofPointsFolder
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerProofPointsFolder"), @"");
			}
			set
			{
				SetValue("ContainerProofPointsFolder", value);
			}
		}


		/// <summary>
		/// Form enabled.
		/// </summary>
		[DatabaseField]
		public bool ContainerFormEnabled
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("ContainerFormEnabled"), false);
			}
			set
			{
				SetValue("ContainerFormEnabled", value);
			}
		}


		/// <summary>
		/// Form title.
		/// </summary>
		[DatabaseField]
		public string ContainerFormTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContainerFormTitle"), @"");
			}
			set
			{
				SetValue("ContainerFormTitle", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Container fields.
		/// </summary>
		[RegisterProperty]
		public ContainerFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Container fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContainerFields : AbstractHierarchicalObject<ContainerFields>
		{
			/// <summary>
			/// The content item of type Container that is a target of the extended API.
			/// </summary>
			private readonly Container mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContainerFields" /> class with the specified content item of type Container.
			/// </summary>
			/// <param name="instance">The content item of type Container that is a target of the extended API.</param>
			public ContainerFields(Container instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContainerID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContainerID;
				}
				set
				{
					mInstance.ContainerID = value;
				}
			}


			/// <summary>
			/// Expiration.
			/// </summary>
			public DateTime Expiry
			{
				get
				{
					return mInstance.ContainerExpiry;
				}
				set
				{
					mInstance.ContainerExpiry = value;
				}
			}


			/// <summary>
			/// On expiry, redirect to.
			/// </summary>
			public string Redirect
			{
				get
				{
					return mInstance.ContainerRedirect;
				}
				set
				{
					mInstance.ContainerRedirect = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.ContainerName;
				}
				set
				{
					mInstance.ContainerName = value;
				}
			}


			/// <summary>
			/// Is new campaign landing page.
			/// </summary>
			public bool IsNewCampaignLandingPage
			{
				get
				{
					return mInstance.ContainerIsNewCampaignLandingPage;
				}
				set
				{
					mInstance.ContainerIsNewCampaignLandingPage = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.ContainerHeading;
				}
				set
				{
					mInstance.ContainerHeading = value;
				}
			}


			/// <summary>
			/// Heading Text.
			/// </summary>
			public string HeadingText
			{
				get
				{
					return mInstance.ContainerHeadingText;
				}
				set
				{
					mInstance.ContainerHeadingText = value;
				}
			}


			/// <summary>
			/// Hero Image.
			/// </summary>
			public string HeroImage
			{
				get
				{
					return mInstance.ContainerHeroImage;
				}
				set
				{
					mInstance.ContainerHeroImage = value;
				}
			}


			/// <summary>
			/// Hero Alt Text.
			/// </summary>
			public string HeroImageAltTag
			{
				get
				{
					return mInstance.ContainerHeroImageAltTag;
				}
				set
				{
					mInstance.ContainerHeroImageAltTag = value;
				}
			}


			/// <summary>
			/// Hero Accreditation.
			/// </summary>
			public string HeroAccreditation
			{
				get
				{
					return mInstance.ContainerHeroAccreditation;
				}
				set
				{
					mInstance.ContainerHeroAccreditation = value;
				}
			}


			/// <summary>
			/// Hide Share Button.
			/// </summary>
			public bool HideShareButton
			{
				get
				{
					return mInstance.ContainerHideShareButton;
				}
				set
				{
					mInstance.ContainerHideShareButton = value;
				}
			}


			/// <summary>
			/// Hero contact us path.
			/// </summary>
			public string HeroContactUsCtaPath
			{
				get
				{
					return mInstance.ContainerHeroContactUsCtaPath;
				}
				set
				{
					mInstance.ContainerHeroContactUsCtaPath = value;
				}
			}


			/// <summary>
			/// Hero phone.
			/// </summary>
			public string HeroPhone
			{
				get
				{
					return mInstance.ContainerHeroPhone;
				}
				set
				{
					mInstance.ContainerHeroPhone = value;
				}
			}
			
			/// <summary>
			/// Json Schema.
			/// </summary>
			public string JsonSchema
			{
				get
				{
					return mInstance.ContainerJsonSchema;
				}
				set
				{
					mInstance.ContainerJsonSchema = value;
				}
			}


			/// <summary>
			/// Proof point section title.
			/// </summary>
			public string ProofPointsTitle
			{
				get
				{
					return mInstance.ContainerProofPointsTitle;
				}
				set
				{
					mInstance.ContainerProofPointsTitle = value;
				}
			}


			/// <summary>
			/// Proof point section folder (path).
			/// </summary>
			public string ProofPointsFolder
			{
				get
				{
					return mInstance.ContainerProofPointsFolder;
				}
				set
				{
					mInstance.ContainerProofPointsFolder = value;
				}
			}


			/// <summary>
			/// Form enabled.
			/// </summary>
			public bool FormEnabled
			{
				get
				{
					return mInstance.ContainerFormEnabled;
				}
				set
				{
					mInstance.ContainerFormEnabled = value;
				}
			}


			/// <summary>
			/// Form title.
			/// </summary>
			public string FormTitle
			{
				get
				{
					return mInstance.ContainerFormTitle;
				}
				set
				{
					mInstance.ContainerFormTitle = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Container" /> class.
		/// </summary>
		public Container() : base(CLASS_NAME)
		{
			mFields = new ContainerFields(this);
		}

		#endregion
	}
}