//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using ETG.Core.PageTypes;

[assembly: RegisterDocumentType(Contact.CLASS_NAME, typeof(Contact))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Contact.
    /// </summary>
    public partial class Contact : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.Contact";


        /// <summary>
        /// The instance of the class that provides extended API for working with Contact fields.
        /// </summary>
        private readonly ContactFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ContactID.
        /// </summary>
        [DatabaseIDField]
        public int ContactID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ContactID"), 0);
            }
            set
            {
                SetValue("ContactID", value);
            }
        }


        /// <summary>
        /// Opening Hours.
        /// </summary>
        [DatabaseField]
        public string ContactOpeningHours
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactOpeningHours"), @"");
            }
            set
            {
                SetValue("ContactOpeningHours", value);
            }
        }


        /// <summary>
        /// Address line 1.
        /// </summary>
        [DatabaseField]
        public string ContactAddress1
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactAddress1"), @"");
            }
            set
            {
                SetValue("ContactAddress1", value);
            }
        }


        /// <summary>
        /// Address line 2.
        /// </summary>
        [DatabaseField]
        public string ContactAddress2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactAddress2"), @"");
            }
            set
            {
                SetValue("ContactAddress2", value);
            }
        }


        /// <summary>
        /// Phone.
        /// </summary>
        [DatabaseField]
        public string ContactPhone
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactPhone"), @"");
            }
            set
            {
                SetValue("ContactPhone", value);
            }
        }


        /// <summary>
        /// Phone 2.
        /// </summary>
        [DatabaseField]
        public string ContactPhone2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactPhone2"), @"");
            }
            set
            {
                SetValue("ContactPhone2", value);
            }
        }


        /// <summary>
        /// Header Phone (NZ).
        /// </summary>
        [DatabaseField]
        public string HeaderPhoneNz
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HeaderPhoneNz"), @"");
            }
            set
            {
                SetValue("HeaderPhoneNz", value);
            }
        }


        /// <summary>
        /// Header Phone (AU).
        /// </summary>
        [DatabaseField]
        public string HeaderPhoneAu
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HeaderPhoneAu"), @"");
            }
            set
            {
                SetValue("HeaderPhoneAu", value);
            }
        }


        /// <summary>
        /// Email.
        /// </summary>
        [DatabaseField]
        public string ContactEmail
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactEmail"), @"");
            }
            set
            {
                SetValue("ContactEmail", value);
            }
        }


        /// <summary>
        /// FacebookUrl.
        /// </summary>
        [DatabaseField]
        public string ContactFacebookUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactFacebookUrl"), @"");
            }
            set
            {
                SetValue("ContactFacebookUrl", value);
            }
        }


        /// <summary>
        /// Instagram url.
        /// </summary>
        [DatabaseField]
        public string ContactInstagramUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactInstagramUrl"), @"");
            }
            set
            {
                SetValue("ContactInstagramUrl", value);
            }
        }


        /// <summary>
        /// YouTube Url.
        /// </summary>
        [DatabaseField]
        public string ContactYouTubeUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactYouTubeUrl"), @"");
            }
            set
            {
                SetValue("ContactYouTubeUrl", value);
            }
        }


        /// <summary>
        /// LinkedIn Url.
        /// </summary>
        [DatabaseField]
        public string ContactLinkedInUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactLinkedInUrl"), @"");
            }
            set
            {
                SetValue("ContactLinkedInUrl", value);
            }
        }


        /// <summary>
        /// Display Address.
        /// </summary>
        [DatabaseField]
        public string ContactDisplayAddress
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactDisplayAddress"), @"");
            }
            set
            {
                SetValue("ContactDisplayAddress", value);
            }
        }


        /// <summary>
        /// Destination Expert Instruction.
        /// </summary>
        [DatabaseField]
        public string ContactDestinationExpertInstruction
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactDestinationExpertInstruction"), @"");
            }
            set
            {
                SetValue("ContactDestinationExpertInstruction", value);
            }
        }


        /// <summary>
        /// Background Image.
        /// </summary>
        [DatabaseField]
        public string ContactPreferPhoneBackgroundImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactPreferPhoneBackgroundImage"), @"");
            }
            set
            {
                SetValue("ContactPreferPhoneBackgroundImage", value);
            }
        }


        /// <summary>
        /// Widget Description Text.
        /// </summary>
        [DatabaseField]
        public string ContactPreferPhoneDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactPreferPhoneDescription"), @"");
            }
            set
            {
                SetValue("ContactPreferPhoneDescription", value);
            }
        }


        /// <summary>
        /// Opening Hours Text.
        /// </summary>
        [DatabaseField]
        public string ContactPreferPhoneOpeningHoursText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContactPreferPhoneOpeningHoursText"), @"");
            }
            set
            {
                SetValue("ContactPreferPhoneOpeningHoursText", value);
            }
        }


        /// <summary>
        /// Peace of mind url.
        /// </summary>
        [DatabaseField]
        public string PeaceOfMindUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PeaceOfMindUrl"), @"");
            }
            set
            {
                SetValue("PeaceOfMindUrl", value);
            }
        }


        /// <summary>
        /// Safe Travel Url.
        /// </summary>
        [DatabaseField]
        public string SafeTravelUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SafeTravelUrl"), @"");
            }
            set
            {
                SetValue("SafeTravelUrl", value);
            }
        }


        /// <summary>
        /// Freedom Of Choice Url.
        /// </summary>
        [DatabaseField]
        public string FreedomOfChoiceUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FreedomOfChoiceUrl"), @"");
            }
            set
            {
                SetValue("FreedomOfChoiceUrl", value);
            }
        }


        /// <summary>
        /// Book Now Url.
        /// </summary>
        [DatabaseField]
        public string BookNowUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BookNowUrl"), @"");
            }
            set
            {
                SetValue("BookNowUrl", value);
            }
        }


        /// <summary>
        /// FAQs Url.
        /// </summary>
        [DatabaseField]
        public string FAQsUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FAQsUrl"), @"");
            }
            set
            {
                SetValue("FAQsUrl", value);
            }
        }


        /// <summary>
        /// Safe Travel Description (Tour page).
        /// </summary>
        [DatabaseField]
        public string SafeTravelDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SafeTravelDescription"), @"");
            }
            set
            {
                SetValue("SafeTravelDescription", value);
            }
        }


        /// <summary>
        /// Exclusive Product Description (Tour page).
        /// </summary>
        [DatabaseField]
        public string ExclusiveProductDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ExclusiveProductDescription"), @"");
            }
            set
            {
                SetValue("ExclusiveProductDescription", value);
            }
        }


        /// <summary>
        /// Freedom Of Choice Description.
        /// </summary>
        [DatabaseField]
        public string FreedomOfChoiceDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FreedomOfChoiceDescription"), @"");
            }
            set
            {
                SetValue("FreedomOfChoiceDescription", value);
            }
        }


        /// <summary>
        /// Peace Of Mind CheckList.
        /// </summary>
        [DatabaseField]
        public string PeaceOfMindCheckList
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PeaceOfMindCheckList"), @"");
            }
            set
            {
                SetValue("PeaceOfMindCheckList", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Contact fields.
        /// </summary>
        [RegisterProperty]
        public ContactFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Contact fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ContactFields : AbstractHierarchicalObject<ContactFields>
        {
            /// <summary>
            /// The content item of type Contact that is a target of the extended API.
            /// </summary>
            private readonly Contact mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ContactFields" /> class with the specified content item of type Contact.
            /// </summary>
            /// <param name="instance">The content item of type Contact that is a target of the extended API.</param>
            public ContactFields(Contact instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ContactID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ContactID;
                }
                set
                {
                    mInstance.ContactID = value;
                }
            }


            /// <summary>
            /// Opening Hours.
            /// </summary>
            public string OpeningHours
            {
                get
                {
                    return mInstance.ContactOpeningHours;
                }
                set
                {
                    mInstance.ContactOpeningHours = value;
                }
            }


            /// <summary>
            /// Address line 1.
            /// </summary>
            public string Address1
            {
                get
                {
                    return mInstance.ContactAddress1;
                }
                set
                {
                    mInstance.ContactAddress1 = value;
                }
            }


            /// <summary>
            /// Address line 2.
            /// </summary>
            public string Address2
            {
                get
                {
                    return mInstance.ContactAddress2;
                }
                set
                {
                    mInstance.ContactAddress2 = value;
                }
            }


            /// <summary>
            /// Phone.
            /// </summary>
            public string Phone
            {
                get
                {
                    return mInstance.ContactPhone;
                }
                set
                {
                    mInstance.ContactPhone = value;
                }
            }


            /// <summary>
            /// Phone 2.
            /// </summary>
            public string Phone2
            {
                get
                {
                    return mInstance.ContactPhone2;
                }
                set
                {
                    mInstance.ContactPhone2 = value;
                }
            }


            /// <summary>
            /// Header Phone (NZ).
            /// </summary>
            public string HeaderPhoneNz
            {
                get
                {
                    return mInstance.HeaderPhoneNz;
                }
                set
                {
                    mInstance.HeaderPhoneNz = value;
                }
            }


            /// <summary>
            /// Header Phone (AU).
            /// </summary>
            public string HeaderPhoneAu
            {
                get
                {
                    return mInstance.HeaderPhoneAu;
                }
                set
                {
                    mInstance.HeaderPhoneAu = value;
                }
            }


            /// <summary>
            /// Email.
            /// </summary>
            public string Email
            {
                get
                {
                    return mInstance.ContactEmail;
                }
                set
                {
                    mInstance.ContactEmail = value;
                }
            }


            /// <summary>
            /// FacebookUrl.
            /// </summary>
            public string FacebookUrl
            {
                get
                {
                    return mInstance.ContactFacebookUrl;
                }
                set
                {
                    mInstance.ContactFacebookUrl = value;
                }
            }


            /// <summary>
            /// Instagram url.
            /// </summary>
            public string InstagramUrl
            {
                get
                {
                    return mInstance.ContactInstagramUrl;
                }
                set
                {
                    mInstance.ContactInstagramUrl = value;
                }
            }


            /// <summary>
            /// YouTube Url.
            /// </summary>
            public string YouTubeUrl
            {
                get
                {
                    return mInstance.ContactYouTubeUrl;
                }
                set
                {
                    mInstance.ContactYouTubeUrl = value;
                }
            }


            /// <summary>
            /// LinkedIn Url.
            /// </summary>
            public string LinkedInUrl
            {
                get
                {
                    return mInstance.ContactLinkedInUrl;
                }
                set
                {
                    mInstance.ContactLinkedInUrl = value;
                }
            }


            /// <summary>
            /// Display Address.
            /// </summary>
            public string DisplayAddress
            {
                get
                {
                    return mInstance.ContactDisplayAddress;
                }
                set
                {
                    mInstance.ContactDisplayAddress = value;
                }
            }


            /// <summary>
            /// Destination Expert Instruction.
            /// </summary>
            public string DestinationExpertInstruction
            {
                get
                {
                    return mInstance.ContactDestinationExpertInstruction;
                }
                set
                {
                    mInstance.ContactDestinationExpertInstruction = value;
                }
            }


            /// <summary>
            /// Background Image.
            /// </summary>
            public string PreferPhoneBackgroundImage
            {
                get
                {
                    return mInstance.ContactPreferPhoneBackgroundImage;
                }
                set
                {
                    mInstance.ContactPreferPhoneBackgroundImage = value;
                }
            }


            /// <summary>
            /// Widget Description Text.
            /// </summary>
            public string PreferPhoneDescription
            {
                get
                {
                    return mInstance.ContactPreferPhoneDescription;
                }
                set
                {
                    mInstance.ContactPreferPhoneDescription = value;
                }
            }


            /// <summary>
            /// Opening Hours Text.
            /// </summary>
            public string PreferPhoneOpeningHoursText
            {
                get
                {
                    return mInstance.ContactPreferPhoneOpeningHoursText;
                }
                set
                {
                    mInstance.ContactPreferPhoneOpeningHoursText = value;
                }
            }


            /// <summary>
            /// Peace of mind url.
            /// </summary>
            public string PeaceOfMindUrl
            {
                get
                {
                    return mInstance.PeaceOfMindUrl;
                }
                set
                {
                    mInstance.PeaceOfMindUrl = value;
                }
            }


            /// <summary>
            /// Safe Travel Url.
            /// </summary>
            public string SafeTravelUrl
            {
                get
                {
                    return mInstance.SafeTravelUrl;
                }
                set
                {
                    mInstance.SafeTravelUrl = value;
                }
            }


            /// <summary>
            /// Freedom Of Choice Url.
            /// </summary>
            public string FreedomOfChoiceUrl
            {
                get
                {
                    return mInstance.FreedomOfChoiceUrl;
                }
                set
                {
                    mInstance.FreedomOfChoiceUrl = value;
                }
            }


            /// <summary>
            /// Book Now Url.
            /// </summary>
            public string BookNowUrl
            {
                get
                {
                    return mInstance.BookNowUrl;
                }
                set
                {
                    mInstance.BookNowUrl = value;
                }
            }


            /// <summary>
            /// FAQs Url.
            /// </summary>
            public string FAQsUrl
            {
                get
                {
                    return mInstance.FAQsUrl;
                }
                set
                {
                    mInstance.FAQsUrl = value;
                }
            }


            /// <summary>
            /// Safe Travel Description (Tour page).
            /// </summary>
            public string SafeTravelDescription
            {
                get
                {
                    return mInstance.SafeTravelDescription;
                }
                set
                {
                    mInstance.SafeTravelDescription = value;
                }
            }


            /// <summary>
            /// Exclusive Product Description (Tour page).
            /// </summary>
            public string ExclusiveProductDescription
            {
                get
                {
                    return mInstance.ExclusiveProductDescription;
                }
                set
                {
                    mInstance.ExclusiveProductDescription = value;
                }
            }


            /// <summary>
            /// Freedom Of Choice Description.
            /// </summary>
            public string FreedomOfChoiceDescription
            {
                get
                {
                    return mInstance.FreedomOfChoiceDescription;
                }
                set
                {
                    mInstance.FreedomOfChoiceDescription = value;
                }
            }


            /// <summary>
            /// Peace Of Mind CheckList.
            /// </summary>
            public string PeaceOfMindCheckList
            {
                get
                {
                    return mInstance.PeaceOfMindCheckList;
                }
                set
                {
                    mInstance.PeaceOfMindCheckList = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Contact" /> class.
        /// </summary>
        public Contact() : base(CLASS_NAME)
        {
            mFields = new ContactFields(this);
        }

        #endregion
    }
}