//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using ETG.Core.PageTypes;

[assembly: RegisterDocumentType(CTAIcon.CLASS_NAME, typeof(CTAIcon))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type CTAIcon.
    /// </summary>
    public partial class CTAIcon : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.CTAIcon";


        /// <summary>
        /// The instance of the class that provides extended API for working with CTAIcon fields.
        /// </summary>
        private readonly CTAIconFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// CTAIconID.
        /// </summary>
        [DatabaseIDField]
        public int CTAIconID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("CTAIconID"), 0);
            }
            set
            {
                SetValue("CTAIconID", value);
            }
        }


        /// <summary>
        /// Label.
        /// </summary>
        [DatabaseField]
        public string CTAIconLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CTAIconLabel"), @"");
            }
            set
            {
                SetValue("CTAIconLabel", value);
            }
        }


        /// <summary>
        /// Icon.
        /// </summary>
        [DatabaseField]
        public string CTAIconIcon
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CTAIconIcon"), @"");
            }
            set
            {
                SetValue("CTAIconIcon", value);
            }
        }


        /// <summary>
        /// Url.
        /// </summary>
        [DatabaseField]
        public string CTAIconUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CTAIconUrl"), @"");
            }
            set
            {
                SetValue("CTAIconUrl", value);
            }
        }


        /// <summary>
        /// Svg Icon.
        /// </summary>
        [DatabaseField]
        public string CtaSvgIcon
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CtaSvgIcon"), @"");
            }
            set
            {
                SetValue("CtaSvgIcon", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CTAIcon fields.
        /// </summary>
        [RegisterProperty]
        public CTAIconFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CTAIcon fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CTAIconFields : AbstractHierarchicalObject<CTAIconFields>
        {
            /// <summary>
            /// The content item of type CTAIcon that is a target of the extended API.
            /// </summary>
            private readonly CTAIcon mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CTAIconFields" /> class with the specified content item of type CTAIcon.
            /// </summary>
            /// <param name="instance">The content item of type CTAIcon that is a target of the extended API.</param>
            public CTAIconFields(CTAIcon instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// CTAIconID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.CTAIconID;
                }
                set
                {
                    mInstance.CTAIconID = value;
                }
            }


            /// <summary>
            /// Label.
            /// </summary>
            public string Label
            {
                get
                {
                    return mInstance.CTAIconLabel;
                }
                set
                {
                    mInstance.CTAIconLabel = value;
                }
            }


            /// <summary>
            /// Icon.
            /// </summary>
            public string Icon
            {
                get
                {
                    return mInstance.CTAIconIcon;
                }
                set
                {
                    mInstance.CTAIconIcon = value;
                }
            }


            /// <summary>
            /// Url.
            /// </summary>
            public string Url
            {
                get
                {
                    return mInstance.CTAIconUrl;
                }
                set
                {
                    mInstance.CTAIconUrl = value;
                }
            }


            /// <summary>
            /// Svg Icon.
            /// </summary>
            public string CtaSvgIcon
            {
                get
                {
                    return mInstance.CtaSvgIcon;
                }
                set
                {
                    mInstance.CtaSvgIcon = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CTAIcon" /> class.
        /// </summary>
        public CTAIcon() : base(CLASS_NAME)
        {
            mFields = new CTAIconFields(this);
        }

        #endregion
    }
}