//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CTAImage.CLASS_NAME, typeof(CTAImage))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type CTAImage.
    /// </summary>
    public partial class CTAImage : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.CTAImage";


        /// <summary>
        /// The instance of the class that provides extended API for working with CTAImage fields.
        /// </summary>
        private readonly CTAImageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// CTAIconID.
        /// </summary>
        [DatabaseIDField]
        public int CTAImageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("CTAImageID"), 0);
            }
            set
            {
                SetValue("CTAImageID", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string CTAImageImagePath
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CTAImageImagePath"), @"");
            }
            set
            {
                SetValue("CTAImageImagePath", value);
            }
        }


        /// <summary>
        /// Image Alt Text.
        /// </summary>
        [DatabaseField]
        public string CTAImageImageAltText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CTAImageImageAltText"), @"");
            }
            set
            {
                SetValue("CTAImageImageAltText", value);
            }
        }


        /// <summary>
        /// Url.
        /// </summary>
        [DatabaseField]
        public string CTAImageUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CTAImageUrl"), @"");
            }
            set
            {
                SetValue("CTAImageUrl", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CTAImage fields.
        /// </summary>
        [RegisterProperty]
        public CTAImageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CTAImage fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CTAImageFields : AbstractHierarchicalObject<CTAImageFields>
        {
            /// <summary>
            /// The content item of type CTAImage that is a target of the extended API.
            /// </summary>
            private readonly CTAImage mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CTAImageFields" /> class with the specified content item of type CTAImage.
            /// </summary>
            /// <param name="instance">The content item of type CTAImage that is a target of the extended API.</param>
            public CTAImageFields(CTAImage instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// CTAIconID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.CTAImageID;
                }
                set
                {
                    mInstance.CTAImageID = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string ImagePath
            {
                get
                {
                    return mInstance.CTAImageImagePath;
                }
                set
                {
                    mInstance.CTAImageImagePath = value;
                }
            }


            /// <summary>
            /// Image Alt Text.
            /// </summary>
            public string ImageAltText
            {
                get
                {
                    return mInstance.CTAImageImageAltText;
                }
                set
                {
                    mInstance.CTAImageImageAltText = value;
                }
            }


            /// <summary>
            /// Url.
            /// </summary>
            public string Url
            {
                get
                {
                    return mInstance.CTAImageUrl;
                }
                set
                {
                    mInstance.CTAImageUrl = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CTAImage" /> class.
        /// </summary>
        public CTAImage() : base(CLASS_NAME)
        {
            mFields = new CTAImageFields(this);
        }

        #endregion
    }
}