//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using ETG.Core.PageTypes;

[assembly: RegisterDocumentType(Destination.CLASS_NAME, typeof(Destination))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Destination.
    /// </summary>
    public partial class Destination : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.Destination";


        /// <summary>
        /// The instance of the class that provides extended API for working with Destination fields.
        /// </summary>
        private readonly DestinationFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// DestinationID.
        /// </summary>
        [DatabaseIDField]
        public int DestinationID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("DestinationID"), 0);
            }
            set
            {
                SetValue("DestinationID", value);
            }
        }


        /// <summary>
        /// Name.
        /// </summary>
        [DatabaseField]
        public string DestinationName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationName"), @"");
            }
            set
            {
                SetValue("DestinationName", value);
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string DestinationHeroImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationHeroImage"), @"");
            }
            set
            {
                SetValue("DestinationHeroImage", value);
            }
        }


        /// <summary>
        /// Hero Foreground Image.
        /// </summary>
        [DatabaseField]
        public string DestinationHeroForegroundImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationHeroForegroundImage"), @"");
            }
            set
            {
                SetValue("DestinationHeroForegroundImage", value);
            }
        }


        /// <summary>
        /// Hero Disable Overlay.
        /// </summary>
        [DatabaseField]
        public bool DestinationHeroDisableOverlay
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("DestinationHeroDisableOverlay"), false);
            }
            set
            {
                SetValue("DestinationHeroDisableOverlay", value);
            }
        }


        /// <summary>
        /// Hero alt tag.
        /// </summary>
        [DatabaseField]
        public string DestinationHeroImageAltTag
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationHeroImageAltTag"), @"");
            }
            set
            {
                SetValue("DestinationHeroImageAltTag", value);
            }
        }


        /// <summary>
        /// Campaign Title.
        /// </summary>
        [DatabaseField]
        public string DestinationCampaignTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationCampaignTitle"), @"");
            }
            set
            {
                SetValue("DestinationCampaignTitle", value);
            }
        }


        /// <summary>
        /// Heading.
        /// </summary>
        [DatabaseField]
        public string DestinationHeading
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationHeading"), @"");
            }
            set
            {
                SetValue("DestinationHeading", value);
            }
        }


        /// <summary>
        /// Summary.
        /// </summary>
        [DatabaseField]
        public string DestinationSummary
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationSummary"), @"");
            }
            set
            {
                SetValue("DestinationSummary", value);
            }
        }


        /// <summary>
        /// Detail.
        /// </summary>
        [DatabaseField]
        public string DestinationDetail
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationDetail"), @"");
            }
            set
            {
                SetValue("DestinationDetail", value);
            }
        }


        /// <summary>
        /// When to Visit.
        /// </summary>
        [DatabaseField]
        public string DestinationWhenToVisit
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationWhenToVisit"), @"");
            }
            set
            {
                SetValue("DestinationWhenToVisit", value);
            }
        }


        /// <summary>
        /// Ethnic group.
        /// </summary>
        [DatabaseField]
        public string DestinationEthnicGroup
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationEthnicGroup"), @"");
            }
            set
            {
                SetValue("DestinationEthnicGroup", value);
            }
        }


        /// <summary>
        /// Official Languages.
        /// </summary>
        [DatabaseField]
        public string DestinationOfficialLanguages
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationOfficialLanguages"), @"");
            }
            set
            {
                SetValue("DestinationOfficialLanguages", value);
            }
        }


        /// <summary>
        /// Currency.
        /// </summary>
        [DatabaseField]
        public string DestinationCurrency
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationCurrency"), @"");
            }
            set
            {
                SetValue("DestinationCurrency", value);
            }
        }


        /// <summary>
        /// Culture.
        /// </summary>
        [DatabaseField]
        public string DestinationCulture
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationCulture"), @"");
            }
            set
            {
                SetValue("DestinationCulture", value);
            }
        }


        /// <summary>
        /// Geography.
        /// </summary>
        [DatabaseField]
        public string DestinationGeography
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationGeography"), @"");
            }
            set
            {
                SetValue("DestinationGeography", value);
            }
        }


        /// <summary>
        /// View Packages Button Label.
        /// </summary>
        [DatabaseField]
        public string DestinationViewPackagesLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationViewPackagesLabel"), @"");
            }
            set
            {
                SetValue("DestinationViewPackagesLabel", value);
            }
        }


        /// <summary>
        /// Feature Tours.
        /// </summary>
        [DatabaseField]
        public string DestinationFeatureTours
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationFeatureTours"), @"");
            }
            set
            {
                SetValue("DestinationFeatureTours", value);
            }
        }


        /// <summary>
        /// Feature Cruise.
        /// </summary>
        [DatabaseField]
        public string DestinationFeatureCruises
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationFeatureCruises"), @"");
            }
            set
            {
                SetValue("DestinationFeatureCruises", value);
            }
        }


        /// <summary>
        /// Enquiry Notification Email.
        /// </summary>
        [DatabaseField]
        public string DestinationEnquiryNotificationEmail
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationEnquiryNotificationEmail"), @"");
            }
            set
            {
                SetValue("DestinationEnquiryNotificationEmail", value);
            }
        }


        /// <summary>
        /// Related Articles Header.
        /// </summary>
        [DatabaseField]
        public string DestinationRelatedArticlesHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationRelatedArticlesHeader"), @"");
            }
            set
            {
                SetValue("DestinationRelatedArticlesHeader", value);
            }
        }


        /// <summary>
        /// Hide Google Reviews?.
        /// </summary>
        [DatabaseField]
        public bool HideGoogleReviews
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("HideGoogleReviews"), false);
            }
            set
            {
                SetValue("HideGoogleReviews", value);
            }
        }


        /// <summary>
        /// Latitude.
        /// </summary>
        [DatabaseField]
        public double DestinationLatitude
        {
            get
            {
                return ValidationHelper.GetDouble(GetValue("DestinationLatitude"), 0);
            }
            set
            {
                SetValue("DestinationLatitude", value);
            }
        }


        /// <summary>
        /// Longitude.
        /// </summary>
        [DatabaseField]
        public double DestinationLongitude
        {
            get
            {
                return ValidationHelper.GetDouble(GetValue("DestinationLongitude"), 0);
            }
            set
            {
                SetValue("DestinationLongitude", value);
            }
        }


        /// <summary>
        /// Map SVG.
        /// </summary>
        [DatabaseField]
        public string DestinationMapSVG
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationMapSVG"), @"");
            }
            set
            {
                SetValue("DestinationMapSVG", value);
            }
        }


        /// <summary>
        /// Map ID (For region only).
        /// </summary>
        [DatabaseField]
        public string DestinationMapID
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationMapID"), @"");
            }
            set
            {
                SetValue("DestinationMapID", value);
            }
        }


        /// <summary>
        /// Json Schema.
        /// </summary>
        [DatabaseField]
        public string DestinationJsonSchema
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationJsonSchema"), @"");
            }
            set
            {
                SetValue("DestinationJsonSchema", value);
            }
        }


        /// <summary>
        /// Display campaign-specific sticky.
        /// </summary>
        [DatabaseField]
        public bool DisplaySticky
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("DisplaySticky"), false);
            }
            set
            {
                SetValue("DisplaySticky", value);
            }
        }


        /// <summary>
        /// Campaign detail 1.
        /// </summary>
        [DatabaseField]
        public string CampaignDetail1
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CampaignDetail1"), @"");
            }
            set
            {
                SetValue("CampaignDetail1", value);
            }
        }


        /// <summary>
        /// Campaign detail 2.
        /// </summary>
        [DatabaseField]
        public string CampaignDetail2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CampaignDetail2"), @"");
            }
            set
            {
                SetValue("CampaignDetail2", value);
            }
        }


        /// <summary>
        /// Campaign detail 3.
        /// </summary>
        [DatabaseField]
        public string CampaignDetail3
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CampaignDetail3"), @"");
            }
            set
            {
                SetValue("CampaignDetail3", value);
            }
        }


        /// <summary>
        /// Countdown label.
        /// </summary>
        [DatabaseField]
        public string CountdownLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CountdownLabel"), @"");
            }
            set
            {
                SetValue("CountdownLabel", value);
            }
        }


        /// <summary>
        /// End of campaign.
        /// </summary>
        [DatabaseField]
        public DateTime EndOfCampaign
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("EndOfCampaign"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("EndOfCampaign", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Destination fields.
        /// </summary>
        [RegisterProperty]
        public DestinationFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Destination fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class DestinationFields : AbstractHierarchicalObject<DestinationFields>
        {
            /// <summary>
            /// The content item of type Destination that is a target of the extended API.
            /// </summary>
            private readonly Destination mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="DestinationFields" /> class with the specified content item of type Destination.
            /// </summary>
            /// <param name="instance">The content item of type Destination that is a target of the extended API.</param>
            public DestinationFields(Destination instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// DestinationID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.DestinationID;
                }
                set
                {
                    mInstance.DestinationID = value;
                }
            }


            /// <summary>
            /// Name.
            /// </summary>
            public string Name
            {
                get
                {
                    return mInstance.DestinationName;
                }
                set
                {
                    mInstance.DestinationName = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.DestinationHeroImage;
                }
                set
                {
                    mInstance.DestinationHeroImage = value;
                }
            }


            /// <summary>
            /// Hero Foreground Image.
            /// </summary>
            public string HeroForegroundImage
            {
                get
                {
                    return mInstance.DestinationHeroForegroundImage;
                }
                set
                {
                    mInstance.DestinationHeroForegroundImage = value;
                }
            }


            /// <summary>
            /// Hero Disable Overlay.
            /// </summary>
            public bool HeroDisableOverlay
            {
                get
                {
                    return mInstance.DestinationHeroDisableOverlay;
                }
                set
                {
                    mInstance.DestinationHeroDisableOverlay = value;
                }
            }


            /// <summary>
            /// Hero alt tag.
            /// </summary>
            public string HeroImageAltTag
            {
                get
                {
                    return mInstance.DestinationHeroImageAltTag;
                }
                set
                {
                    mInstance.DestinationHeroImageAltTag = value;
                }
            }


            /// <summary>
            /// Campaign Title.
            /// </summary>
            public string CampaignTitle
            {
                get
                {
                    return mInstance.DestinationCampaignTitle;
                }
                set
                {
                    mInstance.DestinationCampaignTitle = value;
                }
            }


            /// <summary>
            /// Heading.
            /// </summary>
            public string Heading
            {
                get
                {
                    return mInstance.DestinationHeading;
                }
                set
                {
                    mInstance.DestinationHeading = value;
                }
            }


            /// <summary>
            /// Summary.
            /// </summary>
            public string Summary
            {
                get
                {
                    return mInstance.DestinationSummary;
                }
                set
                {
                    mInstance.DestinationSummary = value;
                }
            }


            /// <summary>
            /// Detail.
            /// </summary>
            public string Detail
            {
                get
                {
                    return mInstance.DestinationDetail;
                }
                set
                {
                    mInstance.DestinationDetail = value;
                }
            }


            /// <summary>
            /// When to Visit.
            /// </summary>
            public string WhenToVisit
            {
                get
                {
                    return mInstance.DestinationWhenToVisit;
                }
                set
                {
                    mInstance.DestinationWhenToVisit = value;
                }
            }


            /// <summary>
            /// Ethnic group.
            /// </summary>
            public string EthnicGroup
            {
                get
                {
                    return mInstance.DestinationEthnicGroup;
                }
                set
                {
                    mInstance.DestinationEthnicGroup = value;
                }
            }


            /// <summary>
            /// Official Languages.
            /// </summary>
            public string OfficialLanguages
            {
                get
                {
                    return mInstance.DestinationOfficialLanguages;
                }
                set
                {
                    mInstance.DestinationOfficialLanguages = value;
                }
            }


            /// <summary>
            /// Currency.
            /// </summary>
            public string Currency
            {
                get
                {
                    return mInstance.DestinationCurrency;
                }
                set
                {
                    mInstance.DestinationCurrency = value;
                }
            }


            /// <summary>
            /// Culture.
            /// </summary>
            public string Culture
            {
                get
                {
                    return mInstance.DestinationCulture;
                }
                set
                {
                    mInstance.DestinationCulture = value;
                }
            }


            /// <summary>
            /// Geography.
            /// </summary>
            public string Geography
            {
                get
                {
                    return mInstance.DestinationGeography;
                }
                set
                {
                    mInstance.DestinationGeography = value;
                }
            }


            /// <summary>
            /// View Packages Button Label.
            /// </summary>
            public string ViewPackagesLabel
            {
                get
                {
                    return mInstance.DestinationViewPackagesLabel;
                }
                set
                {
                    mInstance.DestinationViewPackagesLabel = value;
                }
            }


            /// <summary>
            /// Feature Tours.
            /// </summary>
            public string FeatureTours
            {
                get
                {
                    return mInstance.DestinationFeatureTours;
                }
                set
                {
                    mInstance.DestinationFeatureTours = value;
                }
            }


            /// <summary>
            /// Feature Cruise.
            /// </summary>
            public string FeatureCruises
            {
                get
                {
                    return mInstance.DestinationFeatureCruises;
                }
                set
                {
                    mInstance.DestinationFeatureCruises = value;
                }
            }


            /// <summary>
            /// Enquiry Notification Email.
            /// </summary>
            public string EnquiryNotificationEmail
            {
                get
                {
                    return mInstance.DestinationEnquiryNotificationEmail;
                }
                set
                {
                    mInstance.DestinationEnquiryNotificationEmail = value;
                }
            }


            /// <summary>
            /// Related Articles Header.
            /// </summary>
            public string RelatedArticlesHeader
            {
                get
                {
                    return mInstance.DestinationRelatedArticlesHeader;
                }
                set
                {
                    mInstance.DestinationRelatedArticlesHeader = value;
                }
            }


            /// <summary>
            /// Hide Google Reviews?.
            /// </summary>
            public bool HideGoogleReviews
            {
                get
                {
                    return mInstance.HideGoogleReviews;
                }
                set
                {
                    mInstance.HideGoogleReviews = value;
                }
            }


            /// <summary>
            /// Latitude.
            /// </summary>
            public double Latitude
            {
                get
                {
                    return mInstance.DestinationLatitude;
                }
                set
                {
                    mInstance.DestinationLatitude = value;
                }
            }


            /// <summary>
            /// Longitude.
            /// </summary>
            public double Longitude
            {
                get
                {
                    return mInstance.DestinationLongitude;
                }
                set
                {
                    mInstance.DestinationLongitude = value;
                }
            }


            /// <summary>
            /// Map SVG.
            /// </summary>
            public string MapSVG
            {
                get
                {
                    return mInstance.DestinationMapSVG;
                }
                set
                {
                    mInstance.DestinationMapSVG = value;
                }
            }


            /// <summary>
            /// Map ID (For region only).
            /// </summary>
            public string MapID
            {
                get
                {
                    return mInstance.DestinationMapID;
                }
                set
                {
                    mInstance.DestinationMapID = value;
                }
            }


            /// <summary>
            /// Json Schema.
            /// </summary>
            public string JsonSchema
            {
                get
                {
                    return mInstance.DestinationJsonSchema;
                }
                set
                {
                    mInstance.DestinationJsonSchema = value;
                }
            }


            /// <summary>
            /// Display campaign-specific sticky.
            /// </summary>
            public bool DisplaySticky
            {
                get
                {
                    return mInstance.DisplaySticky;
                }
                set
                {
                    mInstance.DisplaySticky = value;
                }
            }


            /// <summary>
            /// Campaign detail 1.
            /// </summary>
            public string CampaignDetail1
            {
                get
                {
                    return mInstance.CampaignDetail1;
                }
                set
                {
                    mInstance.CampaignDetail1 = value;
                }
            }


            /// <summary>
            /// Campaign detail 2.
            /// </summary>
            public string CampaignDetail2
            {
                get
                {
                    return mInstance.CampaignDetail2;
                }
                set
                {
                    mInstance.CampaignDetail2 = value;
                }
            }


            /// <summary>
            /// Campaign detail 3.
            /// </summary>
            public string CampaignDetail3
            {
                get
                {
                    return mInstance.CampaignDetail3;
                }
                set
                {
                    mInstance.CampaignDetail3 = value;
                }
            }


            /// <summary>
            /// Countdown label.
            /// </summary>
            public string CountdownLabel
            {
                get
                {
                    return mInstance.CountdownLabel;
                }
                set
                {
                    mInstance.CountdownLabel = value;
                }
            }


            /// <summary>
            /// End of campaign.
            /// </summary>
            public DateTime EndOfCampaign
            {
                get
                {
                    return mInstance.EndOfCampaign;
                }
                set
                {
                    mInstance.EndOfCampaign = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Destination" /> class.
        /// </summary>
        public Destination() : base(CLASS_NAME)
        {
            mFields = new DestinationFields(this);
        }

        #endregion
    }
}