//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(DestinationExpertTeam.CLASS_NAME, typeof(DestinationExpertTeam))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type DestinationExpertTeam.
    /// </summary>
    public partial class DestinationExpertTeam : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.DestinationExpertTeam";


        /// <summary>
        /// The instance of the class that provides extended API for working with DestinationExpertTeam fields.
        /// </summary>
        private readonly DestinationExpertTeamFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// DestinationExpertTeamID.
        /// </summary>
        [DatabaseIDField]
        public int DestinationExpertTeamID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("DestinationExpertTeamID"), 0);
            }
            set
            {
                SetValue("DestinationExpertTeamID", value);
            }
        }


        /// <summary>
        /// Name.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamName"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamName", value);
            }
        }


        /// <summary>
        /// Summary.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamSummary
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamSummary"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamSummary", value);
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamHeroImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamHeroImage"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamHeroImage", value);
            }
        }


        /// <summary>
        /// Hero Alt Text.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamHeroImageAltTag
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamHeroImageAltTag"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamHeroImageAltTag", value);
            }
        }


        /// <summary>
        /// Phone.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamPhone
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamPhone"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamPhone", value);
            }
        }


        /// <summary>
        /// Destinations.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamDestinations
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamDestinations"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamDestinations", value);
            }
        }


        /// <summary>
        /// Ex.
        /// Most number of plates consumed at tapas|24
        /// Accumulated siesta minutes|2.643
        /// .
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamGoals
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamGoals"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamGoals", value);
            }
        }


        /// <summary>
        /// Objective Statement.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamObjectiveStatement
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamObjectiveStatement"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamObjectiveStatement", value);
            }
        }


        /// <summary>
        /// Team Profile.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamProfile
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamProfile"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamProfile", value);
            }
        }


        /// <summary>
        /// Favourite tour code.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamFavouriteTourCode
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamFavouriteTourCode"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamFavouriteTourCode", value);
            }
        }


        /// <summary>
        /// Feature Tours.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamFeatureTours
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamFeatureTours"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamFeatureTours", value);
            }
        }


        /// <summary>
        /// Feature Cruises.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamFeatureCruises
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamFeatureCruises"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamFeatureCruises", value);
            }
        }


        /// <summary>
        /// Contact Wdget Description.
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamContactDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamContactDescription"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamContactDescription", value);
            }
        }


        /// <summary>
        /// Contact Widget RHS Text (Above Phone).
        /// </summary>
        [DatabaseField]
        public string DestinationExpertTeamContactRHSText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DestinationExpertTeamContactRHSText"), @"");
            }
            set
            {
                SetValue("DestinationExpertTeamContactRHSText", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with DestinationExpertTeam fields.
        /// </summary>
        [RegisterProperty]
        public DestinationExpertTeamFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with DestinationExpertTeam fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class DestinationExpertTeamFields : AbstractHierarchicalObject<DestinationExpertTeamFields>
        {
            /// <summary>
            /// The content item of type DestinationExpertTeam that is a target of the extended API.
            /// </summary>
            private readonly DestinationExpertTeam mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="DestinationExpertTeamFields" /> class with the specified content item of type DestinationExpertTeam.
            /// </summary>
            /// <param name="instance">The content item of type DestinationExpertTeam that is a target of the extended API.</param>
            public DestinationExpertTeamFields(DestinationExpertTeam instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// DestinationExpertTeamID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.DestinationExpertTeamID;
                }
                set
                {
                    mInstance.DestinationExpertTeamID = value;
                }
            }


            /// <summary>
            /// Name.
            /// </summary>
            public string Name
            {
                get
                {
                    return mInstance.DestinationExpertTeamName;
                }
                set
                {
                    mInstance.DestinationExpertTeamName = value;
                }
            }


            /// <summary>
            /// Summary.
            /// </summary>
            public string Summary
            {
                get
                {
                    return mInstance.DestinationExpertTeamSummary;
                }
                set
                {
                    mInstance.DestinationExpertTeamSummary = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.DestinationExpertTeamHeroImage;
                }
                set
                {
                    mInstance.DestinationExpertTeamHeroImage = value;
                }
            }


            /// <summary>
            /// Hero Alt Text.
            /// </summary>
            public string HeroImageAltTag
            {
                get
                {
                    return mInstance.DestinationExpertTeamHeroImageAltTag;
                }
                set
                {
                    mInstance.DestinationExpertTeamHeroImageAltTag = value;
                }
            }


            /// <summary>
            /// Phone.
            /// </summary>
            public string Phone
            {
                get
                {
                    return mInstance.DestinationExpertTeamPhone;
                }
                set
                {
                    mInstance.DestinationExpertTeamPhone = value;
                }
            }


            /// <summary>
            /// Destinations.
            /// </summary>
            public string Destinations
            {
                get
                {
                    return mInstance.DestinationExpertTeamDestinations;
                }
                set
                {
                    mInstance.DestinationExpertTeamDestinations = value;
                }
            }


            /// <summary>
            /// Ex.
            /// Most number of plates consumed at tapas|24
            /// Accumulated siesta minutes|2.643
            /// .
            /// </summary>
            public string Goals
            {
                get
                {
                    return mInstance.DestinationExpertTeamGoals;
                }
                set
                {
                    mInstance.DestinationExpertTeamGoals = value;
                }
            }


            /// <summary>
            /// Objective Statement.
            /// </summary>
            public string ObjectiveStatement
            {
                get
                {
                    return mInstance.DestinationExpertTeamObjectiveStatement;
                }
                set
                {
                    mInstance.DestinationExpertTeamObjectiveStatement = value;
                }
            }


            /// <summary>
            /// Team Profile.
            /// </summary>
            public string Profile
            {
                get
                {
                    return mInstance.DestinationExpertTeamProfile;
                }
                set
                {
                    mInstance.DestinationExpertTeamProfile = value;
                }
            }


            /// <summary>
            /// Favourite tour code.
            /// </summary>
            public string FavouriteTourCode
            {
                get
                {
                    return mInstance.DestinationExpertTeamFavouriteTourCode;
                }
                set
                {
                    mInstance.DestinationExpertTeamFavouriteTourCode = value;
                }
            }


            /// <summary>
            /// Feature Tours.
            /// </summary>
            public string FeatureTours
            {
                get
                {
                    return mInstance.DestinationExpertTeamFeatureTours;
                }
                set
                {
                    mInstance.DestinationExpertTeamFeatureTours = value;
                }
            }


            /// <summary>
            /// Feature Cruises.
            /// </summary>
            public string FeatureCruises
            {
                get
                {
                    return mInstance.DestinationExpertTeamFeatureCruises;
                }
                set
                {
                    mInstance.DestinationExpertTeamFeatureCruises = value;
                }
            }


            /// <summary>
            /// Contact Wdget Description.
            /// </summary>
            public string ContactDescription
            {
                get
                {
                    return mInstance.DestinationExpertTeamContactDescription;
                }
                set
                {
                    mInstance.DestinationExpertTeamContactDescription = value;
                }
            }


            /// <summary>
            /// Contact Widget RHS Text (Above Phone).
            /// </summary>
            public string ContactRHSText
            {
                get
                {
                    return mInstance.DestinationExpertTeamContactRHSText;
                }
                set
                {
                    mInstance.DestinationExpertTeamContactRHSText = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="DestinationExpertTeam" /> class.
        /// </summary>
        public DestinationExpertTeam() : base(CLASS_NAME)
        {
            mFields = new DestinationExpertTeamFields(this);
        }

        #endregion
    }
}