//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(DocumentLink.CLASS_NAME, typeof(DocumentLink))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type DocumentLink.
	/// </summary>
	public partial class DocumentLink : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "etg.DocumentLink";


		/// <summary>
		/// The instance of the class that provides extended API for working with DocumentLink fields.
		/// </summary>
		private readonly DocumentLinkFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DocumentLinkID.
		/// </summary>
		[DatabaseIDField]
		public int DocumentLinkID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DocumentLinkID"), 0);
			}
			set
			{
				SetValue("DocumentLinkID", value);
			}
		}


		/// <summary>
		/// Linked Document.
		/// </summary>
		[DatabaseField]
		public Guid LinkDocumentGuid
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("LinkDocumentGuid"), Guid.Empty);
			}
			set
			{
				SetValue("LinkDocumentGuid", value);
			}
		}


		/// <summary>
		/// Is Main Hotel.
		/// </summary>
		[DatabaseField]
		public bool LinkDocumentIsMain
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("LinkDocumentIsMain"), false);
			}
			set
			{
				SetValue("LinkDocumentIsMain", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DocumentLink fields.
		/// </summary>
		[RegisterProperty]
		public DocumentLinkFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DocumentLink fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DocumentLinkFields : AbstractHierarchicalObject<DocumentLinkFields>
		{
			/// <summary>
			/// The content item of type DocumentLink that is a target of the extended API.
			/// </summary>
			private readonly DocumentLink mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DocumentLinkFields" /> class with the specified content item of type DocumentLink.
			/// </summary>
			/// <param name="instance">The content item of type DocumentLink that is a target of the extended API.</param>
			public DocumentLinkFields(DocumentLink instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DocumentLinkID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.DocumentLinkID;
				}
				set
				{
					mInstance.DocumentLinkID = value;
				}
			}


			/// <summary>
			/// Linked Document.
			/// </summary>
			public Guid LinkDocumentGuid
			{
				get
				{
					return mInstance.LinkDocumentGuid;
				}
				set
				{
					mInstance.LinkDocumentGuid = value;
				}
			}


			/// <summary>
			/// Is Main Hotel.
			/// </summary>
			public bool LinkDocumentIsMain
			{
				get
				{
					return mInstance.LinkDocumentIsMain;
				}
				set
				{
					mInstance.LinkDocumentIsMain = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DocumentLink" /> class.
		/// </summary>
		public DocumentLink() : base(CLASS_NAME)
		{
			mFields = new DocumentLinkFields(this);
		}

		#endregion
	}
}