//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(FAQ.CLASS_NAME, typeof(FAQ))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type FAQ.
	/// </summary>
	public partial class FAQ : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.FAQ";


		/// <summary>
		/// The instance of the class that provides extended API for working with FAQ fields.
		/// </summary>
		private readonly FAQFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FAQID.
		/// </summary>
		[DatabaseIDField]
		public int FAQID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FAQID"), 0);
			}
			set
			{
				SetValue("FAQID", value);
			}
		}


		/// <summary>
		/// Question.
		/// </summary>
		[DatabaseField]
		public string FAQQuestion
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FAQQuestion"), @"");
			}
			set
			{
				SetValue("FAQQuestion", value);
			}
		}


		/// <summary>
		/// Answer.
		/// </summary>
		[DatabaseField]
		public string FAQAnswer
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FAQAnswer"), @"");
			}
			set
			{
				SetValue("FAQAnswer", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FAQ fields.
		/// </summary>
		[RegisterProperty]
		public FAQFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FAQ fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FAQFields : AbstractHierarchicalObject<FAQFields>
		{
			/// <summary>
			/// The content item of type FAQ that is a target of the extended API.
			/// </summary>
			private readonly FAQ mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FAQFields" /> class with the specified content item of type FAQ.
			/// </summary>
			/// <param name="instance">The content item of type FAQ that is a target of the extended API.</param>
			public FAQFields(FAQ instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FAQID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FAQID;
				}
				set
				{
					mInstance.FAQID = value;
				}
			}


			/// <summary>
			/// Question.
			/// </summary>
			public string Question
			{
				get
				{
					return mInstance.FAQQuestion;
				}
				set
				{
					mInstance.FAQQuestion = value;
				}
			}


			/// <summary>
			/// Answer.
			/// </summary>
			public string Answer
			{
				get
				{
					return mInstance.FAQAnswer;
				}
				set
				{
					mInstance.FAQAnswer = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FAQ" /> class.
		/// </summary>
		public FAQ() : base(CLASS_NAME)
		{
			mFields = new FAQFields(this);
		}

		#endregion
	}
}