//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(FeatureTile.CLASS_NAME, typeof(FeatureTile))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type FeatureTile.
    /// </summary>
    public partial class FeatureTile : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.FeatureTile";


        /// <summary>
        /// The instance of the class that provides extended API for working with FeatureTile fields.
        /// </summary>
        private readonly FeatureTileFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// FeatureTileID.
        /// </summary>
        [DatabaseIDField]
        public int FeatureTileID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("FeatureTileID"), 0);
            }
            set
            {
                SetValue("FeatureTileID", value);
            }
        }


        /// <summary>
        /// Name.
        /// </summary>
        [DatabaseField]
        public string FeatureTileName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureTileName"), @"");
            }
            set
            {
                SetValue("FeatureTileName", value);
            }
        }


        /// <summary>
        /// Large Text.
        /// </summary>
        [DatabaseField]
        public string FeatureTileLargeText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureTileLargeText"), @"");
            }
            set
            {
                SetValue("FeatureTileLargeText", value);
            }
        }


        /// <summary>
        /// Small text.
        /// </summary>
        [DatabaseField]
        public string FeatureTileSmallText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureTileSmallText"), @"");
            }
            set
            {
                SetValue("FeatureTileSmallText", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string FeatureTileImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureTileImage"), @"");
            }
            set
            {
                SetValue("FeatureTileImage", value);
            }
        }


        /// <summary>
        /// Is Offer?.
        /// </summary>
        [DatabaseField]
        public bool FeatureTileIsOffer
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("FeatureTileIsOffer"), false);
            }
            set
            {
                SetValue("FeatureTileIsOffer", value);
            }
        }


        /// <summary>
        /// CTA Label.
        /// </summary>
        [DatabaseField]
        public string FeatureTileCTALabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureTileCTALabel"), @"");
            }
            set
            {
                SetValue("FeatureTileCTALabel", value);
            }
        }


        /// <summary>
        /// CTA Url.
        /// </summary>
        [DatabaseField]
        public string FeatureTileCTAUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureTileCTAUrl"), @"");
            }
            set
            {
                SetValue("FeatureTileCTAUrl", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with FeatureTile fields.
        /// </summary>
        [RegisterProperty]
        public FeatureTileFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with FeatureTile fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class FeatureTileFields : AbstractHierarchicalObject<FeatureTileFields>
        {
            /// <summary>
            /// The content item of type FeatureTile that is a target of the extended API.
            /// </summary>
            private readonly FeatureTile mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="FeatureTileFields" /> class with the specified content item of type FeatureTile.
            /// </summary>
            /// <param name="instance">The content item of type FeatureTile that is a target of the extended API.</param>
            public FeatureTileFields(FeatureTile instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// FeatureTileID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.FeatureTileID;
                }
                set
                {
                    mInstance.FeatureTileID = value;
                }
            }


            /// <summary>
            /// Name.
            /// </summary>
            public string Name
            {
                get
                {
                    return mInstance.FeatureTileName;
                }
                set
                {
                    mInstance.FeatureTileName = value;
                }
            }


            /// <summary>
            /// Large Text.
            /// </summary>
            public string LargeText
            {
                get
                {
                    return mInstance.FeatureTileLargeText;
                }
                set
                {
                    mInstance.FeatureTileLargeText = value;
                }
            }


            /// <summary>
            /// Small text.
            /// </summary>
            public string SmallText
            {
                get
                {
                    return mInstance.FeatureTileSmallText;
                }
                set
                {
                    mInstance.FeatureTileSmallText = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.FeatureTileImage;
                }
                set
                {
                    mInstance.FeatureTileImage = value;
                }
            }


            /// <summary>
            /// Is Offer?.
            /// </summary>
            public bool IsOffer
            {
                get
                {
                    return mInstance.FeatureTileIsOffer;
                }
                set
                {
                    mInstance.FeatureTileIsOffer = value;
                }
            }


            /// <summary>
            /// CTA Label.
            /// </summary>
            public string CTALabel
            {
                get
                {
                    return mInstance.FeatureTileCTALabel;
                }
                set
                {
                    mInstance.FeatureTileCTALabel = value;
                }
            }


            /// <summary>
            /// CTA Url.
            /// </summary>
            public string CTAUrl
            {
                get
                {
                    return mInstance.FeatureTileCTAUrl;
                }
                set
                {
                    mInstance.FeatureTileCTAUrl = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureTile" /> class.
        /// </summary>
        public FeatureTile() : base(CLASS_NAME)
        {
            mFields = new FeatureTileFields(this);
        }

        #endregion
    }
}