//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(FreedomOfChoiceOption.CLASS_NAME, typeof(FreedomOfChoiceOption))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type FreedomOfChoiceOption.
	/// </summary>
	public partial class FreedomOfChoiceOption : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.FreedomOfChoiceOption";


		/// <summary>
		/// The instance of the class that provides extended API for working with FreedomOfChoiceOption fields.
		/// </summary>
		private readonly FreedomOfChoiceOptionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FreedomOfChoiceOptionID.
		/// </summary>
		[DatabaseIDField]
		public int FreedomOfChoiceOptionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FreedomOfChoiceOptionID"), 0);
			}
			set
			{
				SetValue("FreedomOfChoiceOptionID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string OptionName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionName"), @"");
			}
			set
			{
				SetValue("OptionName", value);
			}
		}


		/// <summary>
		/// Option Description.
		/// </summary>
		[DatabaseField]
		public string OptionDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionDescription"), @"");
			}
			set
			{
				SetValue("OptionDescription", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FreedomOfChoiceOption fields.
		/// </summary>
		[RegisterProperty]
		public FreedomOfChoiceOptionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FreedomOfChoiceOption fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FreedomOfChoiceOptionFields : AbstractHierarchicalObject<FreedomOfChoiceOptionFields>
		{
			/// <summary>
			/// The content item of type FreedomOfChoiceOption that is a target of the extended API.
			/// </summary>
			private readonly FreedomOfChoiceOption mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FreedomOfChoiceOptionFields" /> class with the specified content item of type FreedomOfChoiceOption.
			/// </summary>
			/// <param name="instance">The content item of type FreedomOfChoiceOption that is a target of the extended API.</param>
			public FreedomOfChoiceOptionFields(FreedomOfChoiceOption instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FreedomOfChoiceOptionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FreedomOfChoiceOptionID;
				}
				set
				{
					mInstance.FreedomOfChoiceOptionID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string OptionName
			{
				get
				{
					return mInstance.OptionName;
				}
				set
				{
					mInstance.OptionName = value;
				}
			}


			/// <summary>
			/// Option Description.
			/// </summary>
			public string OptionDescription
			{
				get
				{
					return mInstance.OptionDescription;
				}
				set
				{
					mInstance.OptionDescription = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FreedomOfChoiceOption" /> class.
		/// </summary>
		public FreedomOfChoiceOption() : base(CLASS_NAME)
		{
			mFields = new FreedomOfChoiceOptionFields(this);
		}

		#endregion
	}
}