//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(GenericTourTile.CLASS_NAME, typeof(GenericTourTile))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type GenericTourTile.
	/// </summary>
	public partial class GenericTourTile : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.GenericTourTile";


		/// <summary>
		/// The instance of the class that provides extended API for working with GenericTourTile fields.
		/// </summary>
		private readonly GenericTourTileFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// GenericTourTileID.
		/// </summary>
		[DatabaseIDField]
		public int GenericTourTileID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("GenericTourTileID"), 0);
			}
			set
			{
				SetValue("GenericTourTileID", value);
			}
		}


		/// <summary>
		/// Tile Heading.
		/// </summary>
		[DatabaseField]
		public string TileHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TileHeading"), @"");
			}
			set
			{
				SetValue("TileHeading", value);
			}
		}


		/// <summary>
		/// Tour.
		/// </summary>
		[DatabaseField]
		public string TourTileTourCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TourTileTourCode"), @"");
			}
			set
			{
				SetValue("TourTileTourCode", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with GenericTourTile fields.
		/// </summary>
		[RegisterProperty]
		public GenericTourTileFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with GenericTourTile fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GenericTourTileFields : AbstractHierarchicalObject<GenericTourTileFields>
		{
			/// <summary>
			/// The content item of type GenericTourTile that is a target of the extended API.
			/// </summary>
			private readonly GenericTourTile mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GenericTourTileFields" /> class with the specified content item of type GenericTourTile.
			/// </summary>
			/// <param name="instance">The content item of type GenericTourTile that is a target of the extended API.</param>
			public GenericTourTileFields(GenericTourTile instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// GenericTourTileID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.GenericTourTileID;
				}
				set
				{
					mInstance.GenericTourTileID = value;
				}
			}


			/// <summary>
			/// Tile Heading.
			/// </summary>
			public string TileHeading
			{
				get
				{
					return mInstance.TileHeading;
				}
				set
				{
					mInstance.TileHeading = value;
				}
			}


			/// <summary>
			/// Tour.
			/// </summary>
			public string TourTileTourCode
			{
				get
				{
					return mInstance.TourTileTourCode;
				}
				set
				{
					mInstance.TourTileTourCode = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="GenericTourTile" /> class.
		/// </summary>
		public GenericTourTile() : base(CLASS_NAME)
		{
			mFields = new GenericTourTileFields(this);
		}

		#endregion
	}
}