//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using ETG.Core.PageTypes;

[assembly: RegisterDocumentType(Homepage.CLASS_NAME, typeof(Homepage))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Homepage.
    /// </summary>
    public partial class Homepage : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.Homepage";


        /// <summary>
        /// The instance of the class that provides extended API for working with Homepage fields.
        /// </summary>
        private readonly HomepageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// HomepageID.
        /// </summary>
        [DatabaseIDField]
        public int HomepageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("HomepageID"), 0);
            }
            set
            {
                SetValue("HomepageID", value);
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string HomepageHeroImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageHeroImage"), @"");
            }
            set
            {
                SetValue("HomepageHeroImage", value);
            }
        }


        /// <summary>
        /// Hero Caption.
        /// </summary>
        [DatabaseField]
        public string HomepageHeroCaption
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageHeroCaption"), @"");
            }
            set
            {
                SetValue("HomepageHeroCaption", value);
            }
        }


        /// <summary>
        /// Hero Sub Caption.
        /// </summary>
        [DatabaseField]
        public string HomepageHeroSubCaption
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageHeroSubCaption"), @"");
            }
            set
            {
                SetValue("HomepageHeroSubCaption", value);
            }
        }


        /// <summary>
        /// Hero Video.
        /// </summary>
        [DatabaseField]
        public string HomepageHeroVideo
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageHeroVideo"), @"");
            }
            set
            {
                SetValue("HomepageHeroVideo", value);
            }
        }


        /// <summary>
        /// Video Image.
        /// </summary>
        [DatabaseField]
        public string HomepageHeroVideoImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageHeroVideoImage"), @"");
            }
            set
            {
                SetValue("HomepageHeroVideoImage", value);
            }
        }


        /// <summary>
        /// Hero Slide Show Folder.
        /// </summary>
        [DatabaseField]
        public string HomepageHeroSlideShowFolder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageHeroSlideShowFolder"), @"");
            }
            set
            {
                SetValue("HomepageHeroSlideShowFolder", value);
            }
        }


        /// <summary>
        /// Experiences.
        /// </summary>
        [DatabaseField]
        public string HomepageExperiences
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageExperiences"), @"");
            }
            set
            {
                SetValue("HomepageExperiences", value);
            }
        }


        /// <summary>
        /// Destination Expert.
        /// </summary>
        [DatabaseField]
        public Guid HomepageDestinationExpertGuid
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("HomepageDestinationExpertGuid"), Guid.Empty);
            }
            set
            {
                SetValue("HomepageDestinationExpertGuid", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string HomepageFeaturedTilesTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeaturedTilesTitle"), @"");
            }
            set
            {
                SetValue("HomepageFeaturedTilesTitle", value);
            }
        }


        /// <summary>
        /// Featured Tiles Folder.
        /// </summary>
        [DatabaseField]
        public string HomepageFeaturedTilesFolder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeaturedTilesFolder"), @"");
            }
            set
            {
                SetValue("HomepageFeaturedTilesFolder", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string HomepageProofPointsTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageProofPointsTitle"), @"");
            }
            set
            {
                SetValue("HomepageProofPointsTitle", value);
            }
        }


        /// <summary>
        /// Proof Points Folder.
        /// </summary>
        [DatabaseField]
        public string HomepageProofPointsFolder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageProofPointsFolder"), @"");
            }
            set
            {
                SetValue("HomepageProofPointsFolder", value);
            }
        }


        /// <summary>
        /// Destinations Section Title.
        /// </summary>
        [DatabaseField]
        public string HomepageDestinationsSectionTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageDestinationsSectionTitle"), @"");
            }
            set
            {
                SetValue("HomepageDestinationsSectionTitle", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string HomepageFeatureToursSectionTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeatureToursSectionTitle"), @"");
            }
            set
            {
                SetValue("HomepageFeatureToursSectionTitle", value);
            }
        }


        /// <summary>
        /// Feature Tours.
        /// </summary>
        [DatabaseField]
        public string HomepageFeatureTours
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeatureTours"), @"");
            }
            set
            {
                SetValue("HomepageFeatureTours", value);
            }
        }


        /// <summary>
        /// View all url.
        /// </summary>
        [DatabaseField]
        public string HomepageFeatureToursViewAllUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeatureToursViewAllUrl"), @"");
            }
            set
            {
                SetValue("HomepageFeatureToursViewAllUrl", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string HomepageFeatureToursSectionTitle2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeatureToursSectionTitle2"), @"");
            }
            set
            {
                SetValue("HomepageFeatureToursSectionTitle2", value);
            }
        }


        /// <summary>
        /// Feature Tours.
        /// </summary>
        [DatabaseField]
        public string HomepageFeatureTours2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeatureTours2"), @"");
            }
            set
            {
                SetValue("HomepageFeatureTours2", value);
            }
        }


        /// <summary>
        /// View all label.
        /// </summary>
        [DatabaseField]
        public string HomepageFeatureToursViewAllLabel2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeatureToursViewAllLabel2"), @"");
            }
            set
            {
                SetValue("HomepageFeatureToursViewAllLabel2", value);
            }
        }


        /// <summary>
        /// View all url.
        /// </summary>
        [DatabaseField]
        public string HomepageFeatureToursViewAllUrl2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageFeatureToursViewAllUrl2"), @"");
            }
            set
            {
                SetValue("HomepageFeatureToursViewAllUrl2", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string HomepageTravelBlogsSectionTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageTravelBlogsSectionTitle"), @"");
            }
            set
            {
                SetValue("HomepageTravelBlogsSectionTitle", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string HomepageTravelBlogsSectionDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageTravelBlogsSectionDescription"), @"");
            }
            set
            {
                SetValue("HomepageTravelBlogsSectionDescription", value);
            }
        }


        /// <summary>
        /// View All URL.
        /// </summary>
        [DatabaseField]
        public string HomepageTravelBlogsSectionViewAllUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageTravelBlogsSectionViewAllUrl"), @"");
            }
            set
            {
                SetValue("HomepageTravelBlogsSectionViewAllUrl", value);
            }
        }


        /// <summary>
        /// Json Schema.
        /// </summary>
        [DatabaseField]
        public string HomepageJsonSchema
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageJsonSchema"), @"");
            }
            set
            {
                SetValue("HomepageJsonSchema", value);
            }
        }


        /// <summary>
        /// Show Competition Popup.
        /// </summary>
        [DatabaseField]
        public bool HomepageShowCompetitionPopup
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("HomepageShowCompetitionPopup"), false);
            }
            set
            {
                SetValue("HomepageShowCompetitionPopup", value);
            }
        }


        /// <summary>
        /// Competition Unique Cookie Name.
        /// </summary>
        [DatabaseField]
        public string HomepageCompetitionCookieName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageCompetitionCookieName"), @"");
            }
            set
            {
                SetValue("HomepageCompetitionCookieName", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string HomepagePopupTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepagePopupTitle"), @"");
            }
            set
            {
                SetValue("HomepagePopupTitle", value);
            }
        }


        /// <summary>
        /// Sub Title.
        /// </summary>
        [DatabaseField]
        public string HomepagePopupSubTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepagePopupSubTitle"), @"");
            }
            set
            {
                SetValue("HomepagePopupSubTitle", value);
            }
        }


        /// <summary>
        /// Terms url.
        /// </summary>
        [DatabaseField]
        public string HomepageCompetitionTermsUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageCompetitionTermsUrl"), @"");
            }
            set
            {
                SetValue("HomepageCompetitionTermsUrl", value);
            }
        }


        /// <summary>
        /// Popup Thank You.
        /// </summary>
        [DatabaseField]
        public string HomepageCompetitionPopupThankYou
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomepageCompetitionPopupThankYou"), @"");
            }
            set
            {
                SetValue("HomepageCompetitionPopupThankYou", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Homepage fields.
        /// </summary>
        [RegisterProperty]
        public HomepageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Homepage fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class HomepageFields : AbstractHierarchicalObject<HomepageFields>
        {
            /// <summary>
            /// The content item of type Homepage that is a target of the extended API.
            /// </summary>
            private readonly Homepage mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="HomepageFields" /> class with the specified content item of type Homepage.
            /// </summary>
            /// <param name="instance">The content item of type Homepage that is a target of the extended API.</param>
            public HomepageFields(Homepage instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// HomepageID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.HomepageID;
                }
                set
                {
                    mInstance.HomepageID = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.HomepageHeroImage;
                }
                set
                {
                    mInstance.HomepageHeroImage = value;
                }
            }


            /// <summary>
            /// Hero Caption.
            /// </summary>
            public string HeroCaption
            {
                get
                {
                    return mInstance.HomepageHeroCaption;
                }
                set
                {
                    mInstance.HomepageHeroCaption = value;
                }
            }


            /// <summary>
            /// Hero Sub Caption.
            /// </summary>
            public string HeroSubCaption
            {
                get
                {
                    return mInstance.HomepageHeroSubCaption;
                }
                set
                {
                    mInstance.HomepageHeroSubCaption = value;
                }
            }


            /// <summary>
            /// Hero Video.
            /// </summary>
            public string HeroVideo
            {
                get
                {
                    return mInstance.HomepageHeroVideo;
                }
                set
                {
                    mInstance.HomepageHeroVideo = value;
                }
            }


            /// <summary>
            /// Video Image.
            /// </summary>
            public string HeroVideoImage
            {
                get
                {
                    return mInstance.HomepageHeroVideoImage;
                }
                set
                {
                    mInstance.HomepageHeroVideoImage = value;
                }
            }


            /// <summary>
            /// Hero Slide Show Folder.
            /// </summary>
            public string HeroSlideShowFolder
            {
                get
                {
                    return mInstance.HomepageHeroSlideShowFolder;
                }
                set
                {
                    mInstance.HomepageHeroSlideShowFolder = value;
                }
            }


            /// <summary>
            /// Experiences.
            /// </summary>
            public string Experiences
            {
                get
                {
                    return mInstance.HomepageExperiences;
                }
                set
                {
                    mInstance.HomepageExperiences = value;
                }
            }


            /// <summary>
            /// Destination Expert.
            /// </summary>
            public Guid DestinationExpertGuid
            {
                get
                {
                    return mInstance.HomepageDestinationExpertGuid;
                }
                set
                {
                    mInstance.HomepageDestinationExpertGuid = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string FeaturedTilesTitle
            {
                get
                {
                    return mInstance.HomepageFeaturedTilesTitle;
                }
                set
                {
                    mInstance.HomepageFeaturedTilesTitle = value;
                }
            }


            /// <summary>
            /// Featured Tiles Folder.
            /// </summary>
            public string FeaturedTilesFolder
            {
                get
                {
                    return mInstance.HomepageFeaturedTilesFolder;
                }
                set
                {
                    mInstance.HomepageFeaturedTilesFolder = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string ProofPointsTitle
            {
                get
                {
                    return mInstance.HomepageProofPointsTitle;
                }
                set
                {
                    mInstance.HomepageProofPointsTitle = value;
                }
            }


            /// <summary>
            /// Proof Points Folder.
            /// </summary>
            public string ProofPointsFolder
            {
                get
                {
                    return mInstance.HomepageProofPointsFolder;
                }
                set
                {
                    mInstance.HomepageProofPointsFolder = value;
                }
            }


            /// <summary>
            /// Destinations Section Title.
            /// </summary>
            public string DestinationsSectionTitle
            {
                get
                {
                    return mInstance.HomepageDestinationsSectionTitle;
                }
                set
                {
                    mInstance.HomepageDestinationsSectionTitle = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string FeatureToursSectionTitle
            {
                get
                {
                    return mInstance.HomepageFeatureToursSectionTitle;
                }
                set
                {
                    mInstance.HomepageFeatureToursSectionTitle = value;
                }
            }


            /// <summary>
            /// Feature Tours.
            /// </summary>
            public string FeatureTours
            {
                get
                {
                    return mInstance.HomepageFeatureTours;
                }
                set
                {
                    mInstance.HomepageFeatureTours = value;
                }
            }


            /// <summary>
            /// View all url.
            /// </summary>
            public string FeatureToursViewAllUrl
            {
                get
                {
                    return mInstance.HomepageFeatureToursViewAllUrl;
                }
                set
                {
                    mInstance.HomepageFeatureToursViewAllUrl = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string FeatureToursSectionTitle2
            {
                get
                {
                    return mInstance.HomepageFeatureToursSectionTitle2;
                }
                set
                {
                    mInstance.HomepageFeatureToursSectionTitle2 = value;
                }
            }


            /// <summary>
            /// Feature Tours.
            /// </summary>
            public string FeatureTours2
            {
                get
                {
                    return mInstance.HomepageFeatureTours2;
                }
                set
                {
                    mInstance.HomepageFeatureTours2 = value;
                }
            }


            /// <summary>
            /// View all label.
            /// </summary>
            public string FeatureToursViewAllLabel2
            {
                get
                {
                    return mInstance.HomepageFeatureToursViewAllLabel2;
                }
                set
                {
                    mInstance.HomepageFeatureToursViewAllLabel2 = value;
                }
            }


            /// <summary>
            /// View all url.
            /// </summary>
            public string FeatureToursViewAllUrl2
            {
                get
                {
                    return mInstance.HomepageFeatureToursViewAllUrl2;
                }
                set
                {
                    mInstance.HomepageFeatureToursViewAllUrl2 = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string TravelBlogsSectionTitle
            {
                get
                {
                    return mInstance.HomepageTravelBlogsSectionTitle;
                }
                set
                {
                    mInstance.HomepageTravelBlogsSectionTitle = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string TravelBlogsSectionDescription
            {
                get
                {
                    return mInstance.HomepageTravelBlogsSectionDescription;
                }
                set
                {
                    mInstance.HomepageTravelBlogsSectionDescription = value;
                }
            }


            /// <summary>
            /// View All URL.
            /// </summary>
            public string TravelBlogsSectionViewAllUrl
            {
                get
                {
                    return mInstance.HomepageTravelBlogsSectionViewAllUrl;
                }
                set
                {
                    mInstance.HomepageTravelBlogsSectionViewAllUrl = value;
                }
            }


            /// <summary>
            /// Json Schema.
            /// </summary>
            public string JsonSchema
            {
                get
                {
                    return mInstance.HomepageJsonSchema;
                }
                set
                {
                    mInstance.HomepageJsonSchema = value;
                }
            }


            /// <summary>
            /// Show Competition Popup.
            /// </summary>
            public bool ShowCompetitionPopup
            {
                get
                {
                    return mInstance.HomepageShowCompetitionPopup;
                }
                set
                {
                    mInstance.HomepageShowCompetitionPopup = value;
                }
            }


            /// <summary>
            /// Competition Unique Cookie Name.
            /// </summary>
            public string CompetitionCookieName
            {
                get
                {
                    return mInstance.HomepageCompetitionCookieName;
                }
                set
                {
                    mInstance.HomepageCompetitionCookieName = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string PopupTitle
            {
                get
                {
                    return mInstance.HomepagePopupTitle;
                }
                set
                {
                    mInstance.HomepagePopupTitle = value;
                }
            }


            /// <summary>
            /// Sub Title.
            /// </summary>
            public string PopupSubTitle
            {
                get
                {
                    return mInstance.HomepagePopupSubTitle;
                }
                set
                {
                    mInstance.HomepagePopupSubTitle = value;
                }
            }


            /// <summary>
            /// Terms url.
            /// </summary>
            public string CompetitionTermsUrl
            {
                get
                {
                    return mInstance.HomepageCompetitionTermsUrl;
                }
                set
                {
                    mInstance.HomepageCompetitionTermsUrl = value;
                }
            }


            /// <summary>
            /// Popup Thank You.
            /// </summary>
            public string CompetitionPopupThankYou
            {
                get
                {
                    return mInstance.HomepageCompetitionPopupThankYou;
                }
                set
                {
                    mInstance.HomepageCompetitionPopupThankYou = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Homepage" /> class.
        /// </summary>
        public Homepage() : base(CLASS_NAME)
        {
            mFields = new HomepageFields(this);
        }

        #endregion
    }
}