//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Hotel.CLASS_NAME, typeof(Hotel))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type Hotel.
	/// </summary>
	public partial class Hotel : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.Hotel";


		/// <summary>
		/// The instance of the class that provides extended API for working with Hotel fields.
		/// </summary>
		private readonly HotelFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HotelID.
		/// </summary>
		[DatabaseIDField]
		public int HotelID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HotelID"), 0);
			}
			set
			{
				SetValue("HotelID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string HotelName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelName"), @"");
			}
			set
			{
				SetValue("HotelName", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public string HotelImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelImage"), @"");
			}
			set
			{
				SetValue("HotelImage", value);
			}
		}


		/// <summary>
		/// Caption 1.
		/// </summary>
		[DatabaseField]
		public string HotelCaption
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelCaption"), @"");
			}
			set
			{
				SetValue("HotelCaption", value);
			}
		}


		/// <summary>
		/// Image 2.
		/// </summary>
		[DatabaseField]
		public string HotelImage2
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelImage2"), @"");
			}
			set
			{
				SetValue("HotelImage2", value);
			}
		}


		/// <summary>
		/// Caption 2.
		/// </summary>
		[DatabaseField]
		public string HotelCaption2
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelCaption2"), @"");
			}
			set
			{
				SetValue("HotelCaption2", value);
			}
		}


		/// <summary>
		/// Image 3.
		/// </summary>
		[DatabaseField]
		public string HotelImage3
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelImage3"), @"");
			}
			set
			{
				SetValue("HotelImage3", value);
			}
		}


		/// <summary>
		/// Caption 3.
		/// </summary>
		[DatabaseField]
		public string HotelCaption3
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelCaption3"), @"");
			}
			set
			{
				SetValue("HotelCaption3", value);
			}
		}


		/// <summary>
		/// Image 4.
		/// </summary>
		[DatabaseField]
		public string HotelImage4
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelImage4"), @"");
			}
			set
			{
				SetValue("HotelImage4", value);
			}
		}


		/// <summary>
		/// Caption 4.
		/// </summary>
		[DatabaseField]
		public string HotelCaption4
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelCaption4"), @"");
			}
			set
			{
				SetValue("HotelCaption4", value);
			}
		}


		/// <summary>
		/// Review (starts).
		/// </summary>
		[DatabaseField]
		public double HotelReview
		{
			get
			{
				return ValidationHelper.GetDouble(GetValue("HotelReview"), 0);
			}
			set
			{
				SetValue("HotelReview", value);
			}
		}


		/// <summary>
		/// Detail.
		/// </summary>
		[DatabaseField]
		public string HotelDetail
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelDetail"), @"");
			}
			set
			{
				SetValue("HotelDetail", value);
			}
		}


		/// <summary>
		/// Facilities.
		/// </summary>
		[DatabaseField]
		public string HotelFacilities
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelFacilities"), @"");
			}
			set
			{
				SetValue("HotelFacilities", value);
			}
		}


		/// <summary>
		/// Stats.
		/// </summary>
		[DatabaseField]
		public string HotelStats
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HotelStats"), @"");
			}
			set
			{
				SetValue("HotelStats", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Hotel fields.
		/// </summary>
		[RegisterProperty]
		public HotelFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Hotel fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HotelFields : AbstractHierarchicalObject<HotelFields>
		{
			/// <summary>
			/// The content item of type Hotel that is a target of the extended API.
			/// </summary>
			private readonly Hotel mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HotelFields" /> class with the specified content item of type Hotel.
			/// </summary>
			/// <param name="instance">The content item of type Hotel that is a target of the extended API.</param>
			public HotelFields(Hotel instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HotelID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.HotelID;
				}
				set
				{
					mInstance.HotelID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.HotelName;
				}
				set
				{
					mInstance.HotelName = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.HotelImage;
				}
				set
				{
					mInstance.HotelImage = value;
				}
			}


			/// <summary>
			/// Caption 1.
			/// </summary>
			public string Caption
			{
				get
				{
					return mInstance.HotelCaption;
				}
				set
				{
					mInstance.HotelCaption = value;
				}
			}


			/// <summary>
			/// Image 2.
			/// </summary>
			public string Image2
			{
				get
				{
					return mInstance.HotelImage2;
				}
				set
				{
					mInstance.HotelImage2 = value;
				}
			}


			/// <summary>
			/// Caption 2.
			/// </summary>
			public string Caption2
			{
				get
				{
					return mInstance.HotelCaption2;
				}
				set
				{
					mInstance.HotelCaption2 = value;
				}
			}


			/// <summary>
			/// Image 3.
			/// </summary>
			public string Image3
			{
				get
				{
					return mInstance.HotelImage3;
				}
				set
				{
					mInstance.HotelImage3 = value;
				}
			}


			/// <summary>
			/// Caption 3.
			/// </summary>
			public string Caption3
			{
				get
				{
					return mInstance.HotelCaption3;
				}
				set
				{
					mInstance.HotelCaption3 = value;
				}
			}


			/// <summary>
			/// Image 4.
			/// </summary>
			public string Image4
			{
				get
				{
					return mInstance.HotelImage4;
				}
				set
				{
					mInstance.HotelImage4 = value;
				}
			}


			/// <summary>
			/// Caption 4.
			/// </summary>
			public string Caption4
			{
				get
				{
					return mInstance.HotelCaption4;
				}
				set
				{
					mInstance.HotelCaption4 = value;
				}
			}


			/// <summary>
			/// Review (starts).
			/// </summary>
			public double Review
			{
				get
				{
					return mInstance.HotelReview;
				}
				set
				{
					mInstance.HotelReview = value;
				}
			}


			/// <summary>
			/// Detail.
			/// </summary>
			public string Detail
			{
				get
				{
					return mInstance.HotelDetail;
				}
				set
				{
					mInstance.HotelDetail = value;
				}
			}


			/// <summary>
			/// Facilities.
			/// </summary>
			public string Facilities
			{
				get
				{
					return mInstance.HotelFacilities;
				}
				set
				{
					mInstance.HotelFacilities = value;
				}
			}


			/// <summary>
			/// Stats.
			/// </summary>
			public string Stats
			{
				get
				{
					return mInstance.HotelStats;
				}
				set
				{
					mInstance.HotelStats = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Hotel" /> class.
		/// </summary>
		public Hotel() : base(CLASS_NAME)
		{
			mFields = new HotelFields(this);
		}

		#endregion
	}
}