//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(HotelFolder.CLASS_NAME, typeof(HotelFolder))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type HotelFolder.
	/// </summary>
	public partial class HotelFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.HotelFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with HotelFolder fields.
		/// </summary>
		private readonly HotelFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with HotelFolder fields.
		/// </summary>
		[RegisterProperty]
		public HotelFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with HotelFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HotelFolderFields : AbstractHierarchicalObject<HotelFolderFields>
		{
			/// <summary>
			/// The content item of type HotelFolder that is a target of the extended API.
			/// </summary>
			private readonly HotelFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HotelFolderFields" /> class with the specified content item of type HotelFolder.
			/// </summary>
			/// <param name="instance">The content item of type HotelFolder that is a target of the extended API.</param>
			public HotelFolderFields(HotelFolder instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="HotelFolder" /> class.
		/// </summary>
		public HotelFolder() : base(CLASS_NAME)
		{
			mFields = new HotelFolderFields(this);
		}

		#endregion
	}
}