//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using ETG.Core.PageTypes;

[assembly: RegisterDocumentType(ImageTileCta.CLASS_NAME, typeof(ImageTileCta))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type ImageTileCta.
    /// </summary>
    public partial class ImageTileCta : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.ImageTileCta";


        /// <summary>
        /// The instance of the class that provides extended API for working with ImageTileCta fields.
        /// </summary>
        private readonly ImageTileCtaFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ImageTileCtaID.
        /// </summary>
        [DatabaseIDField]
        public int ImageTileCtaID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ImageTileCtaID"), 0);
            }
            set
            {
                SetValue("ImageTileCtaID", value);
            }
        }


        /// <summary>
        /// Caption.
        /// </summary>
        [DatabaseField]
        public string Caption
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Caption"), @"");
            }
            set
            {
                SetValue("Caption", value);
            }
        }


        /// <summary>
        /// Sub caption.
        /// </summary>
        [DatabaseField]
        public string SubCaption
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SubCaption"), @"");
            }
            set
            {
                SetValue("SubCaption", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string Image
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Image"), @"");
            }
            set
            {
                SetValue("Image", value);
            }
        }


        /// <summary>
        /// Url (Optional).
        /// </summary>
        [DatabaseField]
        public string CtaUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CtaUrl"), @"");
            }
            set
            {
                SetValue("CtaUrl", value);
            }
        }


        /// <summary>
        /// Label (optional).
        /// </summary>
        [DatabaseField]
        public string CtaLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CtaLabel"), @"");
            }
            set
            {
                SetValue("CtaLabel", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with ImageTileCta fields.
        /// </summary>
        [RegisterProperty]
        public ImageTileCtaFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with ImageTileCta fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ImageTileCtaFields : AbstractHierarchicalObject<ImageTileCtaFields>
        {
            /// <summary>
            /// The content item of type ImageTileCta that is a target of the extended API.
            /// </summary>
            private readonly ImageTileCta mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ImageTileCtaFields" /> class with the specified content item of type ImageTileCta.
            /// </summary>
            /// <param name="instance">The content item of type ImageTileCta that is a target of the extended API.</param>
            public ImageTileCtaFields(ImageTileCta instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ImageTileCtaID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ImageTileCtaID;
                }
                set
                {
                    mInstance.ImageTileCtaID = value;
                }
            }


            /// <summary>
            /// Caption.
            /// </summary>
            public string Caption
            {
                get
                {
                    return mInstance.Caption;
                }
                set
                {
                    mInstance.Caption = value;
                }
            }


            /// <summary>
            /// Sub caption.
            /// </summary>
            public string SubCaption
            {
                get
                {
                    return mInstance.SubCaption;
                }
                set
                {
                    mInstance.SubCaption = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.Image;
                }
                set
                {
                    mInstance.Image = value;
                }
            }


            /// <summary>
            /// Url (Optional).
            /// </summary>
            public string CtaUrl
            {
                get
                {
                    return mInstance.CtaUrl;
                }
                set
                {
                    mInstance.CtaUrl = value;
                }
            }


            /// <summary>
            /// Label (optional).
            /// </summary>
            public string CtaLabel
            {
                get
                {
                    return mInstance.CtaLabel;
                }
                set
                {
                    mInstance.CtaLabel = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="ImageTileCta" /> class.
        /// </summary>
        public ImageTileCta() : base(CLASS_NAME)
        {
            mFields = new ImageTileCtaFields(this);
        }

        #endregion
    }
}