//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Image.CLASS_NAME, typeof(Image))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Image.
    /// </summary>
    public partial class Image : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.Image";


        /// <summary>
        /// The instance of the class that provides extended API for working with Image fields.
        /// </summary>
        private readonly ImageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ImageID.
        /// </summary>
        [DatabaseIDField]
        public int ImageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ImageID"), 0);
            }
            set
            {
                SetValue("ImageID", value);
            }
        }


        /// <summary>
        /// Image Path.
        /// </summary>
        [DatabaseField]
        public string ImageFilePath
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ImageFilePath"), @"");
            }
            set
            {
                SetValue("ImageFilePath", value);
            }
        }


        /// <summary>
        /// AltText.
        /// </summary>
        [DatabaseField]
        public string ImageAltText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ImageAltText"), @"");
            }
            set
            {
                SetValue("ImageAltText", value);
            }
        }


        /// <summary>
        /// Caption.
        /// </summary>
        [DatabaseField]
        public string ImageCaption
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ImageCaption"), @"");
            }
            set
            {
                SetValue("ImageCaption", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Image fields.
        /// </summary>
        [RegisterProperty]
        public ImageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Image fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ImageFields : AbstractHierarchicalObject<ImageFields>
        {
            /// <summary>
            /// The content item of type Image that is a target of the extended API.
            /// </summary>
            private readonly Image mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ImageFields" /> class with the specified content item of type Image.
            /// </summary>
            /// <param name="instance">The content item of type Image that is a target of the extended API.</param>
            public ImageFields(Image instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ImageID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ImageID;
                }
                set
                {
                    mInstance.ImageID = value;
                }
            }


            /// <summary>
            /// Image Path.
            /// </summary>
            public string FilePath
            {
                get
                {
                    return mInstance.ImageFilePath;
                }
                set
                {
                    mInstance.ImageFilePath = value;
                }
            }


            /// <summary>
            /// AltText.
            /// </summary>
            public string AltText
            {
                get
                {
                    return mInstance.ImageAltText;
                }
                set
                {
                    mInstance.ImageAltText = value;
                }
            }


            /// <summary>
            /// Caption.
            /// </summary>
            public string Caption
            {
                get
                {
                    return mInstance.ImageCaption;
                }
                set
                {
                    mInstance.ImageCaption = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Image" /> class.
        /// </summary>
        public Image() : base(CLASS_NAME)
        {
            mFields = new ImageFields(this);
        }

        #endregion
    }
}