//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Incentive.CLASS_NAME, typeof(Incentive))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Incentive.
    /// </summary>
    public partial class Incentive : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.Incentive";


        /// <summary>
        /// The instance of the class that provides extended API for working with Incentive fields.
        /// </summary>
        private readonly IncentiveFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// IncentiveID.
        /// </summary>
        [DatabaseIDField]
        public int IncentiveID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("IncentiveID"), 0);
            }
            set
            {
                SetValue("IncentiveID", value);
            }
        }


        /// <summary>
        /// Name.
        /// </summary>
        [DatabaseField]
        public string IncentiveName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("IncentiveName"), @"");
            }
            set
            {
                SetValue("IncentiveName", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string IncentiveDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("IncentiveDescription"), @"");
            }
            set
            {
                SetValue("IncentiveDescription", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string IncentiveImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("IncentiveImage"), @"");
            }
            set
            {
                SetValue("IncentiveImage", value);
            }
        }


        /// <summary>
        /// Destination.
        /// </summary>
        [DatabaseField]
        public string IncentiveDestination
        {
            get
            {
                return ValidationHelper.GetString(GetValue("IncentiveDestination"), @"");
            }
            set
            {
                SetValue("IncentiveDestination", value);
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string IncentiveHeroImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("IncentiveHeroImage"), @"");
            }
            set
            {
                SetValue("IncentiveHeroImage", value);
            }
        }


        /// <summary>
        /// Hero Image Accreditation.
        /// </summary>
        [DatabaseField]
        public string IncentiveHeroImageAccreditation
        {
            get
            {
                return ValidationHelper.GetString(GetValue("IncentiveHeroImageAccreditation"), @"");
            }
            set
            {
                SetValue("IncentiveHeroImageAccreditation", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Incentive fields.
        /// </summary>
        [RegisterProperty]
        public IncentiveFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Incentive fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class IncentiveFields : AbstractHierarchicalObject<IncentiveFields>
        {
            /// <summary>
            /// The content item of type Incentive that is a target of the extended API.
            /// </summary>
            private readonly Incentive mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="IncentiveFields" /> class with the specified content item of type Incentive.
            /// </summary>
            /// <param name="instance">The content item of type Incentive that is a target of the extended API.</param>
            public IncentiveFields(Incentive instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// IncentiveID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.IncentiveID;
                }
                set
                {
                    mInstance.IncentiveID = value;
                }
            }


            /// <summary>
            /// Name.
            /// </summary>
            public string Name
            {
                get
                {
                    return mInstance.IncentiveName;
                }
                set
                {
                    mInstance.IncentiveName = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.IncentiveDescription;
                }
                set
                {
                    mInstance.IncentiveDescription = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.IncentiveImage;
                }
                set
                {
                    mInstance.IncentiveImage = value;
                }
            }


            /// <summary>
            /// Destination.
            /// </summary>
            public string Destination
            {
                get
                {
                    return mInstance.IncentiveDestination;
                }
                set
                {
                    mInstance.IncentiveDestination = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.IncentiveHeroImage;
                }
                set
                {
                    mInstance.IncentiveHeroImage = value;
                }
            }


            /// <summary>
            /// Hero Image Accreditation.
            /// </summary>
            public string HeroImageAccreditation
            {
                get
                {
                    return mInstance.IncentiveHeroImageAccreditation;
                }
                set
                {
                    mInstance.IncentiveHeroImageAccreditation = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Incentive" /> class.
        /// </summary>
        public Incentive() : base(CLASS_NAME)
        {
            mFields = new IncentiveFields(this);
        }

        #endregion
    }
}