//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Link.CLASS_NAME, typeof(Link))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type Link.
	/// </summary>
	public partial class Link : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.Link";


		/// <summary>
		/// The instance of the class that provides extended API for working with Link fields.
		/// </summary>
		private readonly LinkFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// LinkID.
		/// </summary>
		[DatabaseIDField]
		public int LinkID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LinkID"), 0);
			}
			set
			{
				SetValue("LinkID", value);
			}
		}


		/// <summary>
		/// Label.
		/// </summary>
		[DatabaseField]
		public string LinkLabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkLabel"), @"");
			}
			set
			{
				SetValue("LinkLabel", value);
			}
		}


		/// <summary>
		/// Path.
		/// </summary>
		[DatabaseField]
		public string LinkPath
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkPath"), @"");
			}
			set
			{
				SetValue("LinkPath", value);
			}
		}


		/// <summary>
		/// Icon.
		/// </summary>
		[DatabaseField]
		public string LinkIconClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkIconClass"), @"");
			}
			set
			{
				SetValue("LinkIconClass", value);
			}
		}


		/// <summary>
		/// SVG Icon.
		/// </summary>
		[DatabaseField]
		public string LinkSVGIcon
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkSVGIcon"), @"");
			}
			set
			{
				SetValue("LinkSVGIcon", value);
			}
		}


		/// <summary>
		/// Link Group Type.
		/// </summary>
		[DatabaseField]
		public string LinkGroupType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkGroupType"), @"");
			}
			set
			{
				SetValue("LinkGroupType", value);
			}
		}


		/// <summary>
		/// Common Link Caption (View All).
		/// </summary>
		[DatabaseField]
		public string LinkCommonCaption
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkCommonCaption"), @"");
			}
			set
			{
				SetValue("LinkCommonCaption", value);
			}
		}


		/// <summary>
		/// Link Common Url.
		/// </summary>
		[DatabaseField]
		public string LinkCommonUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkCommonUrl"), @"");
			}
			set
			{
				SetValue("LinkCommonUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Link fields.
		/// </summary>
		[RegisterProperty]
		public LinkFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Link fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class LinkFields : AbstractHierarchicalObject<LinkFields>
		{
			/// <summary>
			/// The content item of type Link that is a target of the extended API.
			/// </summary>
			private readonly Link mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="LinkFields" /> class with the specified content item of type Link.
			/// </summary>
			/// <param name="instance">The content item of type Link that is a target of the extended API.</param>
			public LinkFields(Link instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// LinkID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.LinkID;
				}
				set
				{
					mInstance.LinkID = value;
				}
			}


			/// <summary>
			/// Label.
			/// </summary>
			public string Label
			{
				get
				{
					return mInstance.LinkLabel;
				}
				set
				{
					mInstance.LinkLabel = value;
				}
			}


			/// <summary>
			/// Path.
			/// </summary>
			public string Path
			{
				get
				{
					return mInstance.LinkPath;
				}
				set
				{
					mInstance.LinkPath = value;
				}
			}


			/// <summary>
			/// Icon.
			/// </summary>
			public string IconClass
			{
				get
				{
					return mInstance.LinkIconClass;
				}
				set
				{
					mInstance.LinkIconClass = value;
				}
			}


			/// <summary>
			/// SVG Icon.
			/// </summary>
			public string SVGIcon
			{
				get
				{
					return mInstance.LinkSVGIcon;
				}
				set
				{
					mInstance.LinkSVGIcon = value;
				}
			}


			/// <summary>
			/// Link Group Type.
			/// </summary>
			public string GroupType
			{
				get
				{
					return mInstance.LinkGroupType;
				}
				set
				{
					mInstance.LinkGroupType = value;
				}
			}


			/// <summary>
			/// Common Link Caption (View All).
			/// </summary>
			public string CommonCaption
			{
				get
				{
					return mInstance.LinkCommonCaption;
				}
				set
				{
					mInstance.LinkCommonCaption = value;
				}
			}


			/// <summary>
			/// Link Common Url.
			/// </summary>
			public string CommonUrl
			{
				get
				{
					return mInstance.LinkCommonUrl;
				}
				set
				{
					mInstance.LinkCommonUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Link" /> class.
		/// </summary>
		public Link() : base(CLASS_NAME)
		{
			mFields = new LinkFields(this);
		}

		#endregion
	}
}