//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(OptionalExtras.CLASS_NAME, typeof(OptionalExtras))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type OptionalExtras.
	/// </summary>
	public partial class OptionalExtras : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.OptionalExtras";


		/// <summary>
		/// The instance of the class that provides extended API for working with OptionalExtras fields.
		/// </summary>
		private readonly OptionalExtrasFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// OptionalExtrasID.
		/// </summary>
		[DatabaseIDField]
		public int OptionalExtrasID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("OptionalExtrasID"), 0);
			}
			set
			{
				SetValue("OptionalExtrasID", value);
			}
		}


		/// <summary>
		/// Number.
		/// </summary>
		[DatabaseField]
		public int OptionalExtrasNumber
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("OptionalExtrasNumber"), 0);
			}
			set
			{
				SetValue("OptionalExtrasNumber", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string OptionalExtrasTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionalExtrasTitle"), @"");
			}
			set
			{
				SetValue("OptionalExtrasTitle", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public string OptionalExtrasImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionalExtrasImage"), @"");
			}
			set
			{
				SetValue("OptionalExtrasImage", value);
			}
		}


		/// <summary>
		/// Image Caption.
		/// </summary>
		[DatabaseField]
		public string OptionalExtrasImageCaption
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionalExtrasImageCaption"), @"");
			}
			set
			{
				SetValue("OptionalExtrasImageCaption", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string OptionalExtrasDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionalExtrasDescription"), @"");
			}
			set
			{
				SetValue("OptionalExtrasDescription", value);
			}
		}


		/// <summary>
		/// Duration.
		/// </summary>
		[DatabaseField]
		public string OptionalExtrasDuration
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionalExtrasDuration"), @"");
			}
			set
			{
				SetValue("OptionalExtrasDuration", value);
			}
		}


		/// <summary>
		/// Price Statement.
		/// </summary>
		[DatabaseField]
		public string OptionalExtrasPriceStatement
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionalExtrasPriceStatement"), @"");
			}
			set
			{
				SetValue("OptionalExtrasPriceStatement", value);
			}
		}


		/// <summary>
		/// Available on days.
		/// </summary>
		[DatabaseField]
		public string OptionalExtrasDaysOfWeek
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionalExtrasDaysOfWeek"), @"");
			}
			set
			{
				SetValue("OptionalExtrasDaysOfWeek", value);
			}
		}


		/// <summary>
		/// From date.
		/// </summary>
		[DatabaseField]
		public DateTime OptionalExtrasFromDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("OptionalExtrasFromDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("OptionalExtrasFromDate", value);
			}
		}


		/// <summary>
		/// To date.
		/// </summary>
		[DatabaseField]
		public DateTime OptionalExtrasToDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("OptionalExtrasToDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("OptionalExtrasToDate", value);
			}
		}


		/// <summary>
		/// Per person cost.
		/// </summary>
		[DatabaseField]
		public string OptionalExtrasPerPersonCost
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OptionalExtrasPerPersonCost"), @"");
			}
			set
			{
				SetValue("OptionalExtrasPerPersonCost", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with OptionalExtras fields.
		/// </summary>
		[RegisterProperty]
		public OptionalExtrasFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with OptionalExtras fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class OptionalExtrasFields : AbstractHierarchicalObject<OptionalExtrasFields>
		{
			/// <summary>
			/// The content item of type OptionalExtras that is a target of the extended API.
			/// </summary>
			private readonly OptionalExtras mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="OptionalExtrasFields" /> class with the specified content item of type OptionalExtras.
			/// </summary>
			/// <param name="instance">The content item of type OptionalExtras that is a target of the extended API.</param>
			public OptionalExtrasFields(OptionalExtras instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// OptionalExtrasID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.OptionalExtrasID;
				}
				set
				{
					mInstance.OptionalExtrasID = value;
				}
			}


			/// <summary>
			/// Number.
			/// </summary>
			public int Number
			{
				get
				{
					return mInstance.OptionalExtrasNumber;
				}
				set
				{
					mInstance.OptionalExtrasNumber = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.OptionalExtrasTitle;
				}
				set
				{
					mInstance.OptionalExtrasTitle = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.OptionalExtrasImage;
				}
				set
				{
					mInstance.OptionalExtrasImage = value;
				}
			}


			/// <summary>
			/// Image Caption.
			/// </summary>
			public string ImageCaption
			{
				get
				{
					return mInstance.OptionalExtrasImageCaption;
				}
				set
				{
					mInstance.OptionalExtrasImageCaption = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.OptionalExtrasDescription;
				}
				set
				{
					mInstance.OptionalExtrasDescription = value;
				}
			}


			/// <summary>
			/// Duration.
			/// </summary>
			public string Duration
			{
				get
				{
					return mInstance.OptionalExtrasDuration;
				}
				set
				{
					mInstance.OptionalExtrasDuration = value;
				}
			}


			/// <summary>
			/// Price Statement.
			/// </summary>
			public string PriceStatement
			{
				get
				{
					return mInstance.OptionalExtrasPriceStatement;
				}
				set
				{
					mInstance.OptionalExtrasPriceStatement = value;
				}
			}


			/// <summary>
			/// Available on days.
			/// </summary>
			public string DaysOfWeek
			{
				get
				{
					return mInstance.OptionalExtrasDaysOfWeek;
				}
				set
				{
					mInstance.OptionalExtrasDaysOfWeek = value;
				}
			}


			/// <summary>
			/// From date.
			/// </summary>
			public DateTime FromDate
			{
				get
				{
					return mInstance.OptionalExtrasFromDate;
				}
				set
				{
					mInstance.OptionalExtrasFromDate = value;
				}
			}


			/// <summary>
			/// To date.
			/// </summary>
			public DateTime ToDate
			{
				get
				{
					return mInstance.OptionalExtrasToDate;
				}
				set
				{
					mInstance.OptionalExtrasToDate = value;
				}
			}


			/// <summary>
			/// Per person cost.
			/// </summary>
			public string PerPersonCost
			{
				get
				{
					return mInstance.OptionalExtrasPerPersonCost;
				}
				set
				{
					mInstance.OptionalExtrasPerPersonCost = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="OptionalExtras" /> class.
		/// </summary>
		public OptionalExtras() : base(CLASS_NAME)
		{
			mFields = new OptionalExtrasFields(this);
		}

		#endregion
	}
}