//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Page.CLASS_NAME, typeof(Page))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Page.
    /// </summary>
    public partial class Page : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.Page";


        /// <summary>
        /// The instance of the class that provides extended API for working with Page fields.
        /// </summary>
        private readonly PageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageID.
        /// </summary>
        [DatabaseIDField]
        public int PageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageID"), 0);
            }
            set
            {
                SetValue("PageID", value);
            }
        }


        /// <summary>
        /// Heading.
        /// </summary>
        [DatabaseField]
        public string PageHeading
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageHeading"), @"");
            }
            set
            {
                SetValue("PageHeading", value);
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string PageHeroImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageHeroImage"), @"");
            }
            set
            {
                SetValue("PageHeroImage", value);
            }
        }


        /// <summary>
        /// Hero Alt Text.
        /// </summary>
        [DatabaseField]
        public string PageHeroImageAltTag
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageHeroImageAltTag"), @"");
            }
            set
            {
                SetValue("PageHeroImageAltTag", value);
            }
        }


        /// <summary>
        /// Hero Caption.
        /// </summary>
        [DatabaseField]
        public string PageHeroCaption
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageHeroCaption"), @"");
            }
            set
            {
                SetValue("PageHeroCaption", value);
            }
        }


        /// <summary>
        /// Content.
        /// </summary>
        [DatabaseField]
        public string PageContent
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageContent"), @"");
            }
            set
            {
                SetValue("PageContent", value);
            }
        }


        /// <summary>
        /// Hide Share Button.
        /// </summary>
        [DatabaseField]
        public bool PageHideShareButton
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("PageHideShareButton"), false);
            }
            set
            {
                SetValue("PageHideShareButton", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Page fields.
        /// </summary>
        [RegisterProperty]
        public PageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Page fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageFields : AbstractHierarchicalObject<PageFields>
        {
            /// <summary>
            /// The content item of type Page that is a target of the extended API.
            /// </summary>
            private readonly Page mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageFields" /> class with the specified content item of type Page.
            /// </summary>
            /// <param name="instance">The content item of type Page that is a target of the extended API.</param>
            public PageFields(Page instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PageID;
                }
                set
                {
                    mInstance.PageID = value;
                }
            }


            /// <summary>
            /// Heading.
            /// </summary>
            public string Heading
            {
                get
                {
                    return mInstance.PageHeading;
                }
                set
                {
                    mInstance.PageHeading = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.PageHeroImage;
                }
                set
                {
                    mInstance.PageHeroImage = value;
                }
            }


            /// <summary>
            /// Hero Alt Text.
            /// </summary>
            public string HeroImageAltTag
            {
                get
                {
                    return mInstance.PageHeroImageAltTag;
                }
                set
                {
                    mInstance.PageHeroImageAltTag = value;
                }
            }


            /// <summary>
            /// Hero Caption.
            /// </summary>
            public string HeroCaption
            {
                get
                {
                    return mInstance.PageHeroCaption;
                }
                set
                {
                    mInstance.PageHeroCaption = value;
                }
            }


            /// <summary>
            /// Content.
            /// </summary>
            public string Content
            {
                get
                {
                    return mInstance.PageContent;
                }
                set
                {
                    mInstance.PageContent = value;
                }
            }


            /// <summary>
            /// Hide Share Button.
            /// </summary>
            public bool HideShareButton
            {
                get
                {
                    return mInstance.PageHideShareButton;
                }
                set
                {
                    mInstance.PageHideShareButton = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Page" /> class.
        /// </summary>
        public Page() : base(CLASS_NAME)
        {
            mFields = new PageFields(this);
        }

        #endregion
    }
}