//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PaymentPage.CLASS_NAME, typeof(PaymentPage))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type PaymentPage.
	/// </summary>
	public partial class PaymentPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.PaymentPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with PaymentPage fields.
		/// </summary>
		private readonly PaymentPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PaymentPageID.
		/// </summary>
		[DatabaseIDField]
		public int PaymentPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PaymentPageID"), 0);
			}
			set
			{
				SetValue("PaymentPageID", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string Heading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Heading"), @"");
			}
			set
			{
				SetValue("Heading", value);
			}
		}


		/// <summary>
		/// Content.
		/// </summary>
		[DatabaseField]
		public string PaymentPageContent
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PaymentPageContent"), @"");
			}
			set
			{
				SetValue("PaymentPageContent", value);
			}
		}


		/// <summary>
		/// Thank you page Content.
		/// </summary>
		[DatabaseField]
		public string PaymentThankyoupageContent
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PaymentThankyoupageContent"), @"");
			}
			set
			{
				SetValue("PaymentThankyoupageContent", value);
			}
		}


		/// <summary>
		/// Thank you page hero image.
		/// </summary>
		[DatabaseField]
		public string PaymentThankyouPageHeroImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PaymentThankyouPageHeroImage"), @"");
			}
			set
			{
				SetValue("PaymentThankyouPageHeroImage", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PaymentPage fields.
		/// </summary>
		[RegisterProperty]
		public PaymentPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PaymentPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PaymentPageFields : AbstractHierarchicalObject<PaymentPageFields>
		{
			/// <summary>
			/// The content item of type PaymentPage that is a target of the extended API.
			/// </summary>
			private readonly PaymentPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PaymentPageFields" /> class with the specified content item of type PaymentPage.
			/// </summary>
			/// <param name="instance">The content item of type PaymentPage that is a target of the extended API.</param>
			public PaymentPageFields(PaymentPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PaymentPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PaymentPageID;
				}
				set
				{
					mInstance.PaymentPageID = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.Heading;
				}
				set
				{
					mInstance.Heading = value;
				}
			}


			/// <summary>
			/// Content.
			/// </summary>
			public string Content
			{
				get
				{
					return mInstance.PaymentPageContent;
				}
				set
				{
					mInstance.PaymentPageContent = value;
				}
			}


			/// <summary>
			/// Thank you page Content.
			/// </summary>
			public string PaymentThankyoupageContent
			{
				get
				{
					return mInstance.PaymentThankyoupageContent;
				}
				set
				{
					mInstance.PaymentThankyoupageContent = value;
				}
			}


			/// <summary>
			/// Thank you page hero image.
			/// </summary>
			public string PaymentThankyouPageHeroImage
			{
				get
				{
					return mInstance.PaymentThankyouPageHeroImage;
				}
				set
				{
					mInstance.PaymentThankyouPageHeroImage = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PaymentPage" /> class.
		/// </summary>
		public PaymentPage() : base(CLASS_NAME)
		{
			mFields = new PaymentPageFields(this);
		}

		#endregion
	}
}