//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(QuickLinkItem.CLASS_NAME, typeof(QuickLinkItem))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type QuickLinkItem.
	/// </summary>
	public partial class QuickLinkItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.QuickLinkItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with QuickLinkItem fields.
		/// </summary>
		private readonly QuickLinkItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// QuickLinksItemID.
		/// </summary>
		[DatabaseIDField]
		public int QuickLinksItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("QuickLinksItemID"), 0);
			}
			set
			{
				SetValue("QuickLinksItemID", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string Heading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Heading"), @"");
			}
			set
			{
				SetValue("Heading", value);
			}
		}


		/// <summary>
		/// Section Id Name.
		/// </summary>
		[DatabaseField]
		public string SectionIdName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SectionIdName"), @"");
			}
			set
			{
				SetValue("SectionIdName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with QuickLinkItem fields.
		/// </summary>
		[RegisterProperty]
		public QuickLinkItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with QuickLinkItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class QuickLinkItemFields : AbstractHierarchicalObject<QuickLinkItemFields>
		{
			/// <summary>
			/// The content item of type QuickLinkItem that is a target of the extended API.
			/// </summary>
			private readonly QuickLinkItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="QuickLinkItemFields" /> class with the specified content item of type QuickLinkItem.
			/// </summary>
			/// <param name="instance">The content item of type QuickLinkItem that is a target of the extended API.</param>
			public QuickLinkItemFields(QuickLinkItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// QuickLinksItemID.
			/// </summary>
			public int QuickLinksItemID
			{
				get
				{
					return mInstance.QuickLinksItemID;
				}
				set
				{
					mInstance.QuickLinksItemID = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.Heading;
				}
				set
				{
					mInstance.Heading = value;
				}
			}


			/// <summary>
			/// Section Id Name.
			/// </summary>
			public string SectionIdName
			{
				get
				{
					return mInstance.SectionIdName;
				}
				set
				{
					mInstance.SectionIdName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="QuickLinkItem" /> class.
		/// </summary>
		public QuickLinkItem() : base(CLASS_NAME)
		{
			mFields = new QuickLinkItemFields(this);
		}

		#endregion
	}
}