//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Robot.CLASS_NAME, typeof(Robot))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Robot.
    /// </summary>
    public partial class Robot : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "etg.robot";


        /// <summary>
        /// The instance of the class that provides extended API for working with Robot fields.
        /// </summary>
        private readonly RobotFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// RobotID.
        /// </summary>
        [DatabaseIDField]
        public int RobotID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("RobotID"), 0);
            }
            set
            {
                SetValue("RobotID", value);
            }
        }


        /// <summary>
        /// Content.
        /// </summary>
        [DatabaseField]
        public string RobotContent
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RobotContent"), @"");
            }
            set
            {
                SetValue("RobotContent", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Robot fields.
        /// </summary>
        [RegisterProperty]
        public RobotFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Robot fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class RobotFields : AbstractHierarchicalObject<RobotFields>
        {
            /// <summary>
            /// The content item of type Robot that is a target of the extended API.
            /// </summary>
            private readonly Robot mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="RobotFields" /> class with the specified content item of type Robot.
            /// </summary>
            /// <param name="instance">The content item of type Robot that is a target of the extended API.</param>
            public RobotFields(Robot instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// RobotID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.RobotID;
                }
                set
                {
                    mInstance.RobotID = value;
                }
            }


            /// <summary>
            /// Content.
            /// </summary>
            public string Content
            {
                get
                {
                    return mInstance.RobotContent;
                }
                set
                {
                    mInstance.RobotContent = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Robot" /> class.
        /// </summary>
        public Robot() : base(CLASS_NAME)
        {
            mFields = new RobotFields(this);
        }

        #endregion
    }
}