//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(RoomUpgrade.CLASS_NAME, typeof(RoomUpgrade))]

namespace ETG.Core.PageTypes
{
		/// <summary>
	/// Represents a content item of type RoomUpgrade.
	/// </summary>
	public partial class RoomUpgrade : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.RoomUpgrade";


		/// <summary>
		/// The instance of the class that provides extended API for working with RoomUpgrade fields.
		/// </summary>
		private readonly RoomUpgradeFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// RoomUpgradeID.
		/// </summary>
		[DatabaseIDField]
		public int RoomUpgradeID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("RoomUpgradeID"), 0);
			}
			set
			{
				SetValue("RoomUpgradeID", value);
			}
		}


		/// <summary>
		/// Number.
		/// </summary>
		[DatabaseField]
		public int RoomUpgradeNumber
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("RoomUpgradeNumber"), 0);
			}
			set
			{
				SetValue("RoomUpgradeNumber", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string RoomUpgradeTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RoomUpgradeTitle"), @"");
			}
			set
			{
				SetValue("RoomUpgradeTitle", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public string RoomUpgradeImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RoomUpgradeImage"), @"");
			}
			set
			{
				SetValue("RoomUpgradeImage", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string RoomUpgradeDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RoomUpgradeDescription"), @"");
			}
			set
			{
				SetValue("RoomUpgradeDescription", value);
			}
		}


		/// <summary>
		/// Hotel.
		/// </summary>
		[DatabaseField]
		public Guid RoomUpgradeHotelGuid
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("RoomUpgradeHotelGuid"), Guid.Empty);
			}
			set
			{
				SetValue("RoomUpgradeHotelGuid", value);
			}
		}


		/// <summary>
		/// Price Statement.
		/// </summary>
		[DatabaseField]
		public string RoomUpgradePriceStatement
		{
			get
			{
				return ValidationHelper.GetString(GetValue("RoomUpgradePriceStatement"), @"");
			}
			set
			{
				SetValue("RoomUpgradePriceStatement", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with RoomUpgrade fields.
		/// </summary>
		[RegisterProperty]
		public RoomUpgradeFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with RoomUpgrade fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class RoomUpgradeFields : AbstractHierarchicalObject<RoomUpgradeFields>
		{
			/// <summary>
			/// The content item of type RoomUpgrade that is a target of the extended API.
			/// </summary>
			private readonly RoomUpgrade mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="RoomUpgradeFields" /> class with the specified content item of type RoomUpgrade.
			/// </summary>
			/// <param name="instance">The content item of type RoomUpgrade that is a target of the extended API.</param>
			public RoomUpgradeFields(RoomUpgrade instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// RoomUpgradeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.RoomUpgradeID;
				}
				set
				{
					mInstance.RoomUpgradeID = value;
				}
			}


			/// <summary>
			/// Number.
			/// </summary>
			public int Number
			{
				get
				{
					return mInstance.RoomUpgradeNumber;
				}
				set
				{
					mInstance.RoomUpgradeNumber = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.RoomUpgradeTitle;
				}
				set
				{
					mInstance.RoomUpgradeTitle = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.RoomUpgradeImage;
				}
				set
				{
					mInstance.RoomUpgradeImage = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.RoomUpgradeDescription;
				}
				set
				{
					mInstance.RoomUpgradeDescription = value;
				}
			}


			/// <summary>
			/// Hotel.
			/// </summary>
			public Guid HotelGuid
			{
				get
				{
					return mInstance.RoomUpgradeHotelGuid;
				}
				set
				{
					mInstance.RoomUpgradeHotelGuid = value;
				}
			}


			/// <summary>
			/// Price Statement.
			/// </summary>
			public string PriceStatement
			{
				get
				{
					return mInstance.RoomUpgradePriceStatement;
				}
				set
				{
					mInstance.RoomUpgradePriceStatement = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="RoomUpgrade" /> class.
		/// </summary>
		public RoomUpgrade() : base(CLASS_NAME)
		{
			mFields = new RoomUpgradeFields(this);
		}

		#endregion
	}
}