//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using ETG.Core.PageTypes;

[assembly: RegisterDocumentType(ThemedPackage.CLASS_NAME, typeof(ThemedPackage))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type ThemedPackage.
	/// </summary>
	public partial class ThemedPackage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.ThemedPackage";


		/// <summary>
		/// The instance of the class that provides extended API for working with ThemedPackage fields.
		/// </summary>
		private readonly ThemedPackageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ThemedPackageID.
		/// </summary>
		[DatabaseIDField]
		public int ThemedPackageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ThemedPackageID"), 0);
			}
			set
			{
				SetValue("ThemedPackageID", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string ThemedPackageHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ThemedPackageHeading"), @"");
			}
			set
			{
				SetValue("ThemedPackageHeading", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string ThemedPackageDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ThemedPackageDescription"), @"");
			}
			set
			{
				SetValue("ThemedPackageDescription", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public string ThemedPackageImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ThemedPackageImage"), @"");
			}
			set
			{
				SetValue("ThemedPackageImage", value);
			}
		}


		/// <summary>
		/// CTA Label.
		/// </summary>
		[DatabaseField]
		public string ThemedPackageCTALabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ThemedPackageCTALabel"), @"");
			}
			set
			{
				SetValue("ThemedPackageCTALabel", value);
			}
		}


		/// <summary>
		/// CTA Url.
		/// </summary>
		[DatabaseField]
		public string ThemedPackageCTAUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ThemedPackageCTAUrl"), @"");
			}
			set
			{
				SetValue("ThemedPackageCTAUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ThemedPackage fields.
		/// </summary>
		[RegisterProperty]
		public ThemedPackageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ThemedPackage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ThemedPackageFields : AbstractHierarchicalObject<ThemedPackageFields>
		{
			/// <summary>
			/// The content item of type ThemedPackage that is a target of the extended API.
			/// </summary>
			private readonly ThemedPackage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ThemedPackageFields" /> class with the specified content item of type ThemedPackage.
			/// </summary>
			/// <param name="instance">The content item of type ThemedPackage that is a target of the extended API.</param>
			public ThemedPackageFields(ThemedPackage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ThemedPackageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ThemedPackageID;
				}
				set
				{
					mInstance.ThemedPackageID = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.ThemedPackageHeading;
				}
				set
				{
					mInstance.ThemedPackageHeading = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.ThemedPackageDescription;
				}
				set
				{
					mInstance.ThemedPackageDescription = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.ThemedPackageImage;
				}
				set
				{
					mInstance.ThemedPackageImage = value;
				}
			}


			/// <summary>
			/// CTA Label.
			/// </summary>
			public string CTALabel
			{
				get
				{
					return mInstance.ThemedPackageCTALabel;
				}
				set
				{
					mInstance.ThemedPackageCTALabel = value;
				}
			}


			/// <summary>
			/// CTA Url.
			/// </summary>
			public string CTAUrl
			{
				get
				{
					return mInstance.ThemedPackageCTAUrl;
				}
				set
				{
					mInstance.ThemedPackageCTAUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ThemedPackage" /> class.
		/// </summary>
		public ThemedPackage() : base(CLASS_NAME)
		{
			mFields = new ThemedPackageFields(this);
		}

		#endregion
	}
}