//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Toolkit.CLASS_NAME, typeof(Toolkit))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Toolkit.
    /// </summary>
    public partial class Toolkit : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.Toolkit";


        /// <summary>
        /// The instance of the class that provides extended API for working with Toolkit fields.
        /// </summary>
        private readonly ToolkitFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ToolkitID.
        /// </summary>
        [DatabaseIDField]
        public int ToolkitID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ToolkitID"), 0);
            }
            set
            {
                SetValue("ToolkitID", value);
            }
        }


        /// <summary>
        /// Name.
        /// </summary>
        [DatabaseField]
        public string ToolkitName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ToolkitName"), @"");
            }
            set
            {
                SetValue("ToolkitName", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string ToolkitImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ToolkitImage"), @"");
            }
            set
            {
                SetValue("ToolkitImage", value);
            }
        }


        /// <summary>
        /// Url.
        /// </summary>
        [DatabaseField]
        public string ToolkitUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ToolkitUrl"), @"");
            }
            set
            {
                SetValue("ToolkitUrl", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Toolkit fields.
        /// </summary>
        [RegisterProperty]
        public ToolkitFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Toolkit fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ToolkitFields : AbstractHierarchicalObject<ToolkitFields>
        {
            /// <summary>
            /// The content item of type Toolkit that is a target of the extended API.
            /// </summary>
            private readonly Toolkit mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ToolkitFields" /> class with the specified content item of type Toolkit.
            /// </summary>
            /// <param name="instance">The content item of type Toolkit that is a target of the extended API.</param>
            public ToolkitFields(Toolkit instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ToolkitID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ToolkitID;
                }
                set
                {
                    mInstance.ToolkitID = value;
                }
            }


            /// <summary>
            /// Name.
            /// </summary>
            public string Name
            {
                get
                {
                    return mInstance.ToolkitName;
                }
                set
                {
                    mInstance.ToolkitName = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.ToolkitImage;
                }
                set
                {
                    mInstance.ToolkitImage = value;
                }
            }


            /// <summary>
            /// Url.
            /// </summary>
            public string Url
            {
                get
                {
                    return mInstance.ToolkitUrl;
                }
                set
                {
                    mInstance.ToolkitUrl = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Toolkit" /> class.
        /// </summary>
        public Toolkit() : base(CLASS_NAME)
        {
            mFields = new ToolkitFields(this);
        }

        #endregion
    }
}