//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TourUpdateLinkedDocument.CLASS_NAME, typeof(TourUpdateLinkedDocument))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type TourUpdateLinkedDocument.
	/// </summary>
	public partial class TourUpdateLinkedDocument : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.TourUpdateLinkedDocument";


		/// <summary>
		/// The instance of the class that provides extended API for working with TourUpdateLinkedDocument fields.
		/// </summary>
		private readonly TourUpdateLinkedDocumentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TourUpdateLinkedDocumentID.
		/// </summary>
		[DatabaseIDField]
		public int TourUpdateLinkedDocumentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TourUpdateLinkedDocumentID"), 0);
			}
			set
			{
				SetValue("TourUpdateLinkedDocumentID", value);
			}
		}


		/// <summary>
		/// Upgraded tour.
		/// </summary>
		[DatabaseField]
		public string TourUpgradesTourCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TourUpgradesTourCode"), @"");
			}
			set
			{
				SetValue("TourUpgradesTourCode", value);
			}
		}


		/// <summary>
		/// Label.
		/// </summary>
		[DatabaseField]
		public string TourUpgradesLabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TourUpgradesLabel"), @"");
			}
			set
			{
				SetValue("TourUpgradesLabel", value);
			}
		}


		/// <summary>
		/// Icon.
		/// </summary>
		[DatabaseField]
		public string TourUpgradesIconClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TourUpgradesIconClass"), @"");
			}
			set
			{
				SetValue("TourUpgradesIconClass", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TourUpdateLinkedDocument fields.
		/// </summary>
		[RegisterProperty]
		public TourUpdateLinkedDocumentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TourUpdateLinkedDocument fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TourUpdateLinkedDocumentFields : AbstractHierarchicalObject<TourUpdateLinkedDocumentFields>
		{
			/// <summary>
			/// The content item of type TourUpdateLinkedDocument that is a target of the extended API.
			/// </summary>
			private readonly TourUpdateLinkedDocument mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TourUpdateLinkedDocumentFields" /> class with the specified content item of type TourUpdateLinkedDocument.
			/// </summary>
			/// <param name="instance">The content item of type TourUpdateLinkedDocument that is a target of the extended API.</param>
			public TourUpdateLinkedDocumentFields(TourUpdateLinkedDocument instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TourUpdateLinkedDocumentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TourUpdateLinkedDocumentID;
				}
				set
				{
					mInstance.TourUpdateLinkedDocumentID = value;
				}
			}


			/// <summary>
			/// Upgraded tour.
			/// </summary>
			public string TourUpgradesTourCode
			{
				get
				{
					return mInstance.TourUpgradesTourCode;
				}
				set
				{
					mInstance.TourUpgradesTourCode = value;
				}
			}


			/// <summary>
			/// Label.
			/// </summary>
			public string TourUpgradesLabel
			{
				get
				{
					return mInstance.TourUpgradesLabel;
				}
				set
				{
					mInstance.TourUpgradesLabel = value;
				}
			}


			/// <summary>
			/// Icon.
			/// </summary>
			public string TourUpgradesIconClass
			{
				get
				{
					return mInstance.TourUpgradesIconClass;
				}
				set
				{
					mInstance.TourUpgradesIconClass = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TourUpdateLinkedDocument" /> class.
		/// </summary>
		public TourUpdateLinkedDocument() : base(CLASS_NAME)
		{
			mFields = new TourUpdateLinkedDocumentFields(this);
		}

		#endregion
	}
}