//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TourInclusion.CLASS_NAME, typeof(TourInclusion))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type TourInclusion.
	/// </summary>
	public partial class TourInclusion : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.TourInclusion";


		/// <summary>
		/// The instance of the class that provides extended API for working with TourInclusion fields.
		/// </summary>
		private readonly TourInclusionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TourInclusionID.
		/// </summary>
		[DatabaseIDField]
		public int TourInclusionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TourInclusionID"), 0);
			}
			set
			{
				SetValue("TourInclusionID", value);
			}
		}


		/// <summary>
		/// Label.
		/// </summary>
		[DatabaseField]
		public string TourInclusionLabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TourInclusionLabel"), @"");
			}
			set
			{
				SetValue("TourInclusionLabel", value);
			}
		}


		/// <summary>
		/// Icon.
		/// </summary>
		[DatabaseField]
		public string TourInclusionIcon
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TourInclusionIcon"), @"");
			}
			set
			{
				SetValue("TourInclusionIcon", value);
			}
		}


		/// <summary>
		/// Highlight this inclusion?.
		/// </summary>
		[DatabaseField]
		public bool TourInclusionHighlight
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("TourInclusionHighlight"), false);
			}
			set
			{
				SetValue("TourInclusionHighlight", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TourInclusion fields.
		/// </summary>
		[RegisterProperty]
		public TourInclusionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TourInclusion fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TourInclusionFields : AbstractHierarchicalObject<TourInclusionFields>
		{
			/// <summary>
			/// The content item of type TourInclusion that is a target of the extended API.
			/// </summary>
			private readonly TourInclusion mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TourInclusionFields" /> class with the specified content item of type TourInclusion.
			/// </summary>
			/// <param name="instance">The content item of type TourInclusion that is a target of the extended API.</param>
			public TourInclusionFields(TourInclusion instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TourInclusionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TourInclusionID;
				}
				set
				{
					mInstance.TourInclusionID = value;
				}
			}


			/// <summary>
			/// Label.
			/// </summary>
			public string Label
			{
				get
				{
					return mInstance.TourInclusionLabel;
				}
				set
				{
					mInstance.TourInclusionLabel = value;
				}
			}


			/// <summary>
			/// Icon.
			/// </summary>
			public string Icon
			{
				get
				{
					return mInstance.TourInclusionIcon;
				}
				set
				{
					mInstance.TourInclusionIcon = value;
				}
			}


			/// <summary>
			/// Highlight this inclusion?.
			/// </summary>
			public bool Highlight
			{
				get
				{
					return mInstance.TourInclusionHighlight;
				}
				set
				{
					mInstance.TourInclusionHighlight = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TourInclusion" /> class.
		/// </summary>
		public TourInclusion() : base(CLASS_NAME)
		{
			mFields = new TourInclusionFields(this);
		}

		#endregion
	}
}