//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TourPricing.CLASS_NAME, typeof(TourPricing))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type TourPricing.
    /// </summary>
    public partial class TourPricing : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.TourPricing";


        /// <summary>
        /// The instance of the class that provides extended API for working with TourPricing fields.
        /// </summary>
        private readonly TourPricingFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// TourPricingID.
        /// </summary>
        [DatabaseIDField]
        public int TourPricingID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingID"), 0);
            }
            set
            {
                SetValue("TourPricingID", value);
            }
        }


        /// <summary>
        /// Tour Date.
        /// </summary>
        [DatabaseField]
        public string TourPricingDate
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TourPricingDate"), @"");
            }
            set
            {
                SetValue("TourPricingDate", value);
            }
        }


        /// <summary>
        /// Override Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingOverridePrice
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingOverridePrice"), 0);
            }
            set
            {
                SetValue("TourPricingOverridePrice", value);
            }
        }


        /// <summary>
        /// Departure Cities.
        /// </summary>
        [DatabaseField]
        public string TourPricingDepartureCities1
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TourPricingDepartureCities1"), @"");
            }
            set
            {
                SetValue("TourPricingDepartureCities1", value);
            }
        }


        /// <summary>
        /// Economy Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingEconomyPrice1
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingEconomyPrice1"), 0);
            }
            set
            {
                SetValue("TourPricingEconomyPrice1", value);
            }
        }


        /// <summary>
        /// Premium Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingPremiumPrice1
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingPremiumPrice1"), 0);
            }
            set
            {
                SetValue("TourPricingPremiumPrice1", value);
            }
        }


        /// <summary>
        /// Business Class Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingBusinessPrice1
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingBusinessPrice1"), 0);
            }
            set
            {
                SetValue("TourPricingBusinessPrice1", value);
            }
        }


        /// <summary>
        /// First Class Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingFirstClassPrice1
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingFirstClassPrice1"), 0);
            }
            set
            {
                SetValue("TourPricingFirstClassPrice1", value);
            }
        }


        /// <summary>
        /// Departure Cities.
        /// </summary>
        [DatabaseField]
        public string TourPricingDepartureCities2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TourPricingDepartureCities2"), @"");
            }
            set
            {
                SetValue("TourPricingDepartureCities2", value);
            }
        }


        /// <summary>
        /// Economy Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingEconomyPrice2
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingEconomyPrice2"), 0);
            }
            set
            {
                SetValue("TourPricingEconomyPrice2", value);
            }
        }


        /// <summary>
        /// Premium Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingPremiumPrice2
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingPremiumPrice2"), 0);
            }
            set
            {
                SetValue("TourPricingPremiumPrice2", value);
            }
        }


        /// <summary>
        /// Business Class Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingBusinessPrice2
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingBusinessPrice2"), 0);
            }
            set
            {
                SetValue("TourPricingBusinessPrice2", value);
            }
        }


        /// <summary>
        /// First Class Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingFirstClassPrice2
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingFirstClassPrice2"), 0);
            }
            set
            {
                SetValue("TourPricingFirstClassPrice2", value);
            }
        }


        /// <summary>
        /// DepartureCities.
        /// </summary>
        [DatabaseField]
        public string TourPricingDepartureCities3
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TourPricingDepartureCities3"), @"");
            }
            set
            {
                SetValue("TourPricingDepartureCities3", value);
            }
        }


        /// <summary>
        /// Economy Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingEconomyPrice3
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingEconomyPrice3"), 0);
            }
            set
            {
                SetValue("TourPricingEconomyPrice3", value);
            }
        }


        /// <summary>
        /// Premium Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingPremiumPrice3
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingPremiumPrice3"), 0);
            }
            set
            {
                SetValue("TourPricingPremiumPrice3", value);
            }
        }


        /// <summary>
        /// Business Class Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingBusinessPrice3
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingBusinessPrice3"), 0);
            }
            set
            {
                SetValue("TourPricingBusinessPrice3", value);
            }
        }


        /// <summary>
        /// First Class Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingFirstClassPrice3
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingFirstClassPrice3"), 0);
            }
            set
            {
                SetValue("TourPricingFirstClassPrice3", value);
            }
        }


        /// <summary>
        /// Departure Cities.
        /// </summary>
        [DatabaseField]
        public string TourPricingDepartureCities4
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TourPricingDepartureCities4"), @"");
            }
            set
            {
                SetValue("TourPricingDepartureCities4", value);
            }
        }


        /// <summary>
        /// Economy Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingEconomyPrice4
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingEconomyPrice4"), 0);
            }
            set
            {
                SetValue("TourPricingEconomyPrice4", value);
            }
        }


        /// <summary>
        /// Premium Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingPremiumPrice4
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingPremiumPrice4"), 0);
            }
            set
            {
                SetValue("TourPricingPremiumPrice4", value);
            }
        }


        /// <summary>
        /// Business Class Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingBusinessPrice4
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingBusinessPrice4"), 0);
            }
            set
            {
                SetValue("TourPricingBusinessPrice4", value);
            }
        }


        /// <summary>
        /// First Class Price.
        /// </summary>
        [DatabaseField]
        public int TourPricingFirstClassPrice4
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourPricingFirstClassPrice4"), 0);
            }
            set
            {
                SetValue("TourPricingFirstClassPrice4", value);
            }
        }


        /// <summary>
        /// Tour.
        /// </summary>
        [DatabaseField]
        public Guid TourPricingTourGuid
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("TourPricingTourGuid"), Guid.Empty);
            }
            set
            {
                SetValue("TourPricingTourGuid", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with TourPricing fields.
        /// </summary>
        [RegisterProperty]
        public TourPricingFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with TourPricing fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class TourPricingFields : AbstractHierarchicalObject<TourPricingFields>
        {
            /// <summary>
            /// The content item of type TourPricing that is a target of the extended API.
            /// </summary>
            private readonly TourPricing mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="TourPricingFields" /> class with the specified content item of type TourPricing.
            /// </summary>
            /// <param name="instance">The content item of type TourPricing that is a target of the extended API.</param>
            public TourPricingFields(TourPricing instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// TourPricingID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.TourPricingID;
                }
                set
                {
                    mInstance.TourPricingID = value;
                }
            }


            /// <summary>
            /// Tour Date.
            /// </summary>
            public string Date
            {
                get
                {
                    return mInstance.TourPricingDate;
                }
                set
                {
                    mInstance.TourPricingDate = value;
                }
            }


            /// <summary>
            /// Override Price.
            /// </summary>
            public int OverridePrice
            {
                get
                {
                    return mInstance.TourPricingOverridePrice;
                }
                set
                {
                    mInstance.TourPricingOverridePrice = value;
                }
            }


            /// <summary>
            /// Departure Cities.
            /// </summary>
            public string DepartureCities1
            {
                get
                {
                    return mInstance.TourPricingDepartureCities1;
                }
                set
                {
                    mInstance.TourPricingDepartureCities1 = value;
                }
            }


            /// <summary>
            /// Economy Price.
            /// </summary>
            public int EconomyPrice1
            {
                get
                {
                    return mInstance.TourPricingEconomyPrice1;
                }
                set
                {
                    mInstance.TourPricingEconomyPrice1 = value;
                }
            }


            /// <summary>
            /// Premium Price.
            /// </summary>
            public int PremiumPrice1
            {
                get
                {
                    return mInstance.TourPricingPremiumPrice1;
                }
                set
                {
                    mInstance.TourPricingPremiumPrice1 = value;
                }
            }


            /// <summary>
            /// Business Class Price.
            /// </summary>
            public int BusinessPrice1
            {
                get
                {
                    return mInstance.TourPricingBusinessPrice1;
                }
                set
                {
                    mInstance.TourPricingBusinessPrice1 = value;
                }
            }


            /// <summary>
            /// First Class Price.
            /// </summary>
            public int FirstClassPrice1
            {
                get
                {
                    return mInstance.TourPricingFirstClassPrice1;
                }
                set
                {
                    mInstance.TourPricingFirstClassPrice1 = value;
                }
            }


            /// <summary>
            /// Departure Cities.
            /// </summary>
            public string DepartureCities2
            {
                get
                {
                    return mInstance.TourPricingDepartureCities2;
                }
                set
                {
                    mInstance.TourPricingDepartureCities2 = value;
                }
            }


            /// <summary>
            /// Economy Price.
            /// </summary>
            public int EconomyPrice2
            {
                get
                {
                    return mInstance.TourPricingEconomyPrice2;
                }
                set
                {
                    mInstance.TourPricingEconomyPrice2 = value;
                }
            }


            /// <summary>
            /// Premium Price.
            /// </summary>
            public int PremiumPrice2
            {
                get
                {
                    return mInstance.TourPricingPremiumPrice2;
                }
                set
                {
                    mInstance.TourPricingPremiumPrice2 = value;
                }
            }


            /// <summary>
            /// Business Class Price.
            /// </summary>
            public int BusinessPrice2
            {
                get
                {
                    return mInstance.TourPricingBusinessPrice2;
                }
                set
                {
                    mInstance.TourPricingBusinessPrice2 = value;
                }
            }


            /// <summary>
            /// First Class Price.
            /// </summary>
            public int FirstClassPrice2
            {
                get
                {
                    return mInstance.TourPricingFirstClassPrice2;
                }
                set
                {
                    mInstance.TourPricingFirstClassPrice2 = value;
                }
            }


            /// <summary>
            /// DepartureCities.
            /// </summary>
            public string DepartureCities3
            {
                get
                {
                    return mInstance.TourPricingDepartureCities3;
                }
                set
                {
                    mInstance.TourPricingDepartureCities3 = value;
                }
            }


            /// <summary>
            /// Economy Price.
            /// </summary>
            public int EconomyPrice3
            {
                get
                {
                    return mInstance.TourPricingEconomyPrice3;
                }
                set
                {
                    mInstance.TourPricingEconomyPrice3 = value;
                }
            }


            /// <summary>
            /// Premium Price.
            /// </summary>
            public int PremiumPrice3
            {
                get
                {
                    return mInstance.TourPricingPremiumPrice3;
                }
                set
                {
                    mInstance.TourPricingPremiumPrice3 = value;
                }
            }


            /// <summary>
            /// Business Class Price.
            /// </summary>
            public int BusinessPrice3
            {
                get
                {
                    return mInstance.TourPricingBusinessPrice3;
                }
                set
                {
                    mInstance.TourPricingBusinessPrice3 = value;
                }
            }


            /// <summary>
            /// First Class Price.
            /// </summary>
            public int FirstClassPrice3
            {
                get
                {
                    return mInstance.TourPricingFirstClassPrice3;
                }
                set
                {
                    mInstance.TourPricingFirstClassPrice3 = value;
                }
            }


            /// <summary>
            /// Departure Cities.
            /// </summary>
            public string DepartureCities4
            {
                get
                {
                    return mInstance.TourPricingDepartureCities4;
                }
                set
                {
                    mInstance.TourPricingDepartureCities4 = value;
                }
            }


            /// <summary>
            /// Economy Price.
            /// </summary>
            public int EconomyPrice4
            {
                get
                {
                    return mInstance.TourPricingEconomyPrice4;
                }
                set
                {
                    mInstance.TourPricingEconomyPrice4 = value;
                }
            }


            /// <summary>
            /// Premium Price.
            /// </summary>
            public int PremiumPrice4
            {
                get
                {
                    return mInstance.TourPricingPremiumPrice4;
                }
                set
                {
                    mInstance.TourPricingPremiumPrice4 = value;
                }
            }


            /// <summary>
            /// Business Class Price.
            /// </summary>
            public int BusinessPrice4
            {
                get
                {
                    return mInstance.TourPricingBusinessPrice4;
                }
                set
                {
                    mInstance.TourPricingBusinessPrice4 = value;
                }
            }


            /// <summary>
            /// First Class Price.
            /// </summary>
            public int FirstClassPrice4
            {
                get
                {
                    return mInstance.TourPricingFirstClassPrice4;
                }
                set
                {
                    mInstance.TourPricingFirstClassPrice4 = value;
                }
            }


            /// <summary>
            /// Tour.
            /// </summary>
            public Guid TourGuid
            {
                get
                {
                    return mInstance.TourPricingTourGuid;
                }
                set
                {
                    mInstance.TourPricingTourGuid = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="TourPricing" /> class.
        /// </summary>
        public TourPricing() : base(CLASS_NAME)
        {
            mFields = new TourPricingFields(this);
        }

        #endregion
    }
}