//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TourBonus.CLASS_NAME, typeof(TourBonus))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type TourBonus.
	/// </summary>
	public partial class TourBonus : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.TourBonus";


		/// <summary>
		/// The instance of the class that provides extended API for working with TourBonus fields.
		/// </summary>
		private readonly TourBonusFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TourHighlilghtID.
		/// </summary>
		[DatabaseIDField]
		public int TourBonusID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TourBonusID"), 0);
			}
			set
			{
				SetValue("TourBonusID", value);
			}
		}


		/// <summary>
		/// Highlight Label.
		/// </summary>
		[DatabaseField]
		public string TourHighlightLabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TourHighlightLabel"), @"");
			}
			set
			{
				SetValue("TourHighlightLabel", value);
			}
		}


		/// <summary>
		/// Icon.
		/// </summary>
		[DatabaseField]
		public string TourHighlightIcon
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TourHighlightIcon"), @"");
			}
			set
			{
				SetValue("TourHighlightIcon", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TourBonus fields.
		/// </summary>
		[RegisterProperty]
		public TourBonusFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TourBonus fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TourBonusFields : AbstractHierarchicalObject<TourBonusFields>
		{
			/// <summary>
			/// The content item of type TourBonus that is a target of the extended API.
			/// </summary>
			private readonly TourBonus mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TourBonusFields" /> class with the specified content item of type TourBonus.
			/// </summary>
			/// <param name="instance">The content item of type TourBonus that is a target of the extended API.</param>
			public TourBonusFields(TourBonus instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TourHighlilghtID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TourBonusID;
				}
				set
				{
					mInstance.TourBonusID = value;
				}
			}


			/// <summary>
			/// Highlight Label.
			/// </summary>
			public string TourHighlightLabel
			{
				get
				{
					return mInstance.TourHighlightLabel;
				}
				set
				{
					mInstance.TourHighlightLabel = value;
				}
			}


			/// <summary>
			/// Icon.
			/// </summary>
			public string TourHighlightIcon
			{
				get
				{
					return mInstance.TourHighlightIcon;
				}
				set
				{
					mInstance.TourHighlightIcon = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TourBonus" /> class.
		/// </summary>
		public TourBonus() : base(CLASS_NAME)
		{
			mFields = new TourBonusFields(this);
		}

		#endregion
	}
}