//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TourHighlilght.CLASS_NAME, typeof(TourHighlilght))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type TourHighlilght.
    /// </summary>
    public partial class TourHighlilght : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.TourHighlilght";


        /// <summary>
        /// The instance of the class that provides extended API for working with TourHighlilght fields.
        /// </summary>
        private readonly TourHighlilghtFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// TourHighlilghtID.
        /// </summary>
        [DatabaseIDField]
        public int TourHighlilghtID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TourHighlilghtID"), 0);
            }
            set
            {
                SetValue("TourHighlilghtID", value);
            }
        }


        /// <summary>
        /// Highlight Label.
        /// </summary>
        [DatabaseField]
        public string TourHighlightLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TourHighlightLabel"), @"");
            }
            set
            {
                SetValue("TourHighlightLabel", value);
            }
        }


        /// <summary>
        /// Icon.
        /// </summary>
        [DatabaseField]
        public string TourHighlightIcon
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TourHighlightIcon"), @"");
            }
            set
            {
                SetValue("TourHighlightIcon", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with TourHighlilght fields.
        /// </summary>
        [RegisterProperty]
        public TourHighlilghtFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with TourHighlilght fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class TourHighlilghtFields : AbstractHierarchicalObject<TourHighlilghtFields>
        {
            /// <summary>
            /// The content item of type TourHighlilght that is a target of the extended API.
            /// </summary>
            private readonly TourHighlilght mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="TourHighlilghtFields" /> class with the specified content item of type TourHighlilght.
            /// </summary>
            /// <param name="instance">The content item of type TourHighlilght that is a target of the extended API.</param>
            public TourHighlilghtFields(TourHighlilght instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// TourHighlilghtID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.TourHighlilghtID;
                }
                set
                {
                    mInstance.TourHighlilghtID = value;
                }
            }


            /// <summary>
            /// Highlight Label.
            /// </summary>
            public string TourHighlightLabel
            {
                get
                {
                    return mInstance.TourHighlightLabel;
                }
                set
                {
                    mInstance.TourHighlightLabel = value;
                }
            }


            /// <summary>
            /// Icon.
            /// </summary>
            public string TourHighlightIcon
            {
                get
                {
                    return mInstance.TourHighlightIcon;
                }
                set
                {
                    mInstance.TourHighlightIcon = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="TourHighlilght" /> class.
        /// </summary>
        public TourHighlilght() : base(CLASS_NAME)
        {
            mFields = new TourHighlilghtFields(this);
        }

        #endregion
    }
}