//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using ETG.Core.PageTypes;

[assembly: RegisterDocumentType(TravelTypeDetail.CLASS_NAME, typeof(TravelTypeDetail))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type TravelTypeDetail.
	/// </summary>
	public partial class TravelTypeDetail : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.TravelTypeDetail";


		/// <summary>
		/// The instance of the class that provides extended API for working with TravelTypeDetail fields.
		/// </summary>
		private readonly TravelTypeDetailFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TravelTypeDetailID.
		/// </summary>
		[DatabaseIDField]
		public int TravelTypeDetailID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TravelTypeDetailID"), 0);
			}
			set
			{
				SetValue("TravelTypeDetailID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string TravelTypeDetailName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeDetailName"), @"");
			}
			set
			{
				SetValue("TravelTypeDetailName", value);
			}
		}


		/// <summary>
		/// Hero Image.
		/// </summary>
		[DatabaseField]
		public string TravelTypeDetailHeroImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeDetailHeroImage"), @"");
			}
			set
			{
				SetValue("TravelTypeDetailHeroImage", value);
			}
		}


		/// <summary>
		/// Hero Image Alt Tag.
		/// </summary>
		[DatabaseField]
		public string TravelTypeDetailHeroImageAltTag
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeDetailHeroImageAltTag"), @"");
			}
			set
			{
				SetValue("TravelTypeDetailHeroImageAltTag", value);
			}
		}


		/// <summary>
		/// Hero Icon.
		/// </summary>
		[DatabaseField]
		public string TravelTypeDetailHeroIcon
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeDetailHeroIcon"), @"");
			}
			set
			{
				SetValue("TravelTypeDetailHeroIcon", value);
			}
		}


		/// <summary>
		/// SVG Icon.
		/// </summary>
		[DatabaseField]
		public string TravelTypeDetailHeroSVGIcon
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeDetailHeroSVGIcon"), @"");
			}
			set
			{
				SetValue("TravelTypeDetailHeroSVGIcon", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string TravelTypeDetailHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeDetailHeading"), @"");
			}
			set
			{
				SetValue("TravelTypeDetailHeading", value);
			}
		}


		/// <summary>
		/// Summary.
		/// </summary>
		[DatabaseField]
		public string TravelTypeDetailSummary
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeDetailSummary"), @"");
			}
			set
			{
				SetValue("TravelTypeDetailSummary", value);
			}
		}


		/// <summary>
		/// Detail.
		/// </summary>
		[DatabaseField]
		public string TravelTypeDetail1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeDetail"), @"");
			}
			set
			{
				SetValue("TravelTypeDetail", value);
			}
		}


		/// <summary>
		/// Themed Packages Heading.
		/// </summary>
		[DatabaseField]
		public string ThemedPackagesHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ThemedPackagesHeading"), @"");
			}
			set
			{
				SetValue("ThemedPackagesHeading", value);
			}
		}


		/// <summary>
		/// Themed Packages Folder.
		/// </summary>
		[DatabaseField]
		public string ThemedPackagesUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ThemedPackagesUrl"), @"");
			}
			set
			{
				SetValue("ThemedPackagesUrl", value);
			}
		}


		/// <summary>
		/// Hide Google Reviews?.
		/// </summary>
		[DatabaseField]
		public bool HideGoogleReviews
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("HideGoogleReviews"), false);
			}
			set
			{
				SetValue("HideGoogleReviews", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TravelTypeDetail fields.
		/// </summary>
		[RegisterProperty]
		public TravelTypeDetailFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TravelTypeDetail fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TravelTypeDetailFields : AbstractHierarchicalObject<TravelTypeDetailFields>
		{
			/// <summary>
			/// The content item of type TravelTypeDetail that is a target of the extended API.
			/// </summary>
			private readonly TravelTypeDetail mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TravelTypeDetailFields" /> class with the specified content item of type TravelTypeDetail.
			/// </summary>
			/// <param name="instance">The content item of type TravelTypeDetail that is a target of the extended API.</param>
			public TravelTypeDetailFields(TravelTypeDetail instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TravelTypeDetailID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TravelTypeDetailID;
				}
				set
				{
					mInstance.TravelTypeDetailID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.TravelTypeDetailName;
				}
				set
				{
					mInstance.TravelTypeDetailName = value;
				}
			}


			/// <summary>
			/// Hero Image.
			/// </summary>
			public string HeroImage
			{
				get
				{
					return mInstance.TravelTypeDetailHeroImage;
				}
				set
				{
					mInstance.TravelTypeDetailHeroImage = value;
				}
			}


			/// <summary>
			/// Hero Image Alt Tag.
			/// </summary>
			public string HeroImageAltTag
			{
				get
				{
					return mInstance.TravelTypeDetailHeroImageAltTag;
				}
				set
				{
					mInstance.TravelTypeDetailHeroImageAltTag = value;
				}
			}


			/// <summary>
			/// Hero Icon.
			/// </summary>
			public string HeroIcon
			{
				get
				{
					return mInstance.TravelTypeDetailHeroIcon;
				}
				set
				{
					mInstance.TravelTypeDetailHeroIcon = value;
				}
			}


			/// <summary>
			/// SVG Icon.
			/// </summary>
			public string HeroSVGIcon
			{
				get
				{
					return mInstance.TravelTypeDetailHeroSVGIcon;
				}
				set
				{
					mInstance.TravelTypeDetailHeroSVGIcon = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.TravelTypeDetailHeading;
				}
				set
				{
					mInstance.TravelTypeDetailHeading = value;
				}
			}


			/// <summary>
			/// Summary.
			/// </summary>
			public string Summary
			{
				get
				{
					return mInstance.TravelTypeDetailSummary;
				}
				set
				{
					mInstance.TravelTypeDetailSummary = value;
				}
			}


			/// <summary>
			/// Detail.
			/// </summary>
			public string TravelTypeDetail
			{
				get
				{
					return mInstance.TravelTypeDetail1;
				}
				set
				{
					mInstance.TravelTypeDetail1 = value;
				}
			}


			/// <summary>
			/// Themed Packages Heading.
			/// </summary>
			public string ThemedPackagesHeading
			{
				get
				{
					return mInstance.ThemedPackagesHeading;
				}
				set
				{
					mInstance.ThemedPackagesHeading = value;
				}
			}


			/// <summary>
			/// Themed Packages Folder.
			/// </summary>
			public string ThemedPackagesUrl
			{
				get
				{
					return mInstance.ThemedPackagesUrl;
				}
				set
				{
					mInstance.ThemedPackagesUrl = value;
				}
			}


			/// <summary>
			/// Hide Google Reviews?.
			/// </summary>
			public bool HideGoogleReviews
			{
				get
				{
					return mInstance.HideGoogleReviews;
				}
				set
				{
					mInstance.HideGoogleReviews = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TravelTypeDetail" /> class.
		/// </summary>
		public TravelTypeDetail() : base(CLASS_NAME)
		{
			mFields = new TravelTypeDetailFields(this);
		}

		#endregion
	}
}