//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using ETG.Core.PageTypes;

[assembly: RegisterDocumentType(TravelTypeLanding.CLASS_NAME, typeof(TravelTypeLanding))]

namespace ETG.Core.PageTypes
{
	/// <summary>
	/// Represents a content item of type TravelTypeLanding.
	/// </summary>
	public partial class TravelTypeLanding : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ETG.TravelTypeLanding";


		/// <summary>
		/// The instance of the class that provides extended API for working with TravelTypeLanding fields.
		/// </summary>
		private readonly TravelTypeLandingFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TravelTypeLandingID.
		/// </summary>
		[DatabaseIDField]
		public int TravelTypeLandingID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TravelTypeLandingID"), 0);
			}
			set
			{
				SetValue("TravelTypeLandingID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string TravelTypeName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeName"), @"");
			}
			set
			{
				SetValue("TravelTypeName", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string TravelTypeHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeHeading"), @"");
			}
			set
			{
				SetValue("TravelTypeHeading", value);
			}
		}


		/// <summary>
		/// Intro.
		/// </summary>
		[DatabaseField]
		public string TravelTypeIntro
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeIntro"), @"");
			}
			set
			{
				SetValue("TravelTypeIntro", value);
			}
		}


		/// <summary>
		/// Summary.
		/// </summary>
		[DatabaseField]
		public string TravelTypeSummary
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeSummary"), @"");
			}
			set
			{
				SetValue("TravelTypeSummary", value);
			}
		}


		/// <summary>
		/// Hero Image.
		/// </summary>
		[DatabaseField]
		public string TravelTypeHeroImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeHeroImage"), @"");
			}
			set
			{
				SetValue("TravelTypeHeroImage", value);
			}
		}


		/// <summary>
		/// Hero Image Alt Tag.
		/// </summary>
		[DatabaseField]
		public string TravelTypeHeroAltText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeHeroAltText"), @"");
			}
			set
			{
				SetValue("TravelTypeHeroAltText", value);
			}
		}


		/// <summary>
		/// Hero Icon.
		/// </summary>
		[DatabaseField]
		public string TravelTypeHeroIcon
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeHeroIcon"), @"");
			}
			set
			{
				SetValue("TravelTypeHeroIcon", value);
			}
		}


		/// <summary>
		/// SVG Icon.
		/// </summary>
		[DatabaseField]
		public string TravelTypeSVGIcon
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TravelTypeSVGIcon"), @"");
			}
			set
			{
				SetValue("TravelTypeSVGIcon", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TravelTypeLanding fields.
		/// </summary>
		[RegisterProperty]
		public TravelTypeLandingFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TravelTypeLanding fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TravelTypeLandingFields : AbstractHierarchicalObject<TravelTypeLandingFields>
		{
			/// <summary>
			/// The content item of type TravelTypeLanding that is a target of the extended API.
			/// </summary>
			private readonly TravelTypeLanding mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TravelTypeLandingFields" /> class with the specified content item of type TravelTypeLanding.
			/// </summary>
			/// <param name="instance">The content item of type TravelTypeLanding that is a target of the extended API.</param>
			public TravelTypeLandingFields(TravelTypeLanding instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TravelTypeLandingID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TravelTypeLandingID;
				}
				set
				{
					mInstance.TravelTypeLandingID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string TravelTypeName
			{
				get
				{
					return mInstance.TravelTypeName;
				}
				set
				{
					mInstance.TravelTypeName = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string TravelTypeHeading
			{
				get
				{
					return mInstance.TravelTypeHeading;
				}
				set
				{
					mInstance.TravelTypeHeading = value;
				}
			}


			/// <summary>
			/// Intro.
			/// </summary>
			public string TravelTypeIntro
			{
				get
				{
					return mInstance.TravelTypeIntro;
				}
				set
				{
					mInstance.TravelTypeIntro = value;
				}
			}


			/// <summary>
			/// Summary.
			/// </summary>
			public string TravelTypeSummary
			{
				get
				{
					return mInstance.TravelTypeSummary;
				}
				set
				{
					mInstance.TravelTypeSummary = value;
				}
			}


			/// <summary>
			/// Hero Image.
			/// </summary>
			public string TravelTypeHeroImage
			{
				get
				{
					return mInstance.TravelTypeHeroImage;
				}
				set
				{
					mInstance.TravelTypeHeroImage = value;
				}
			}


			/// <summary>
			/// Hero Image Alt Tag.
			/// </summary>
			public string TravelTypeHeroAltText
			{
				get
				{
					return mInstance.TravelTypeHeroAltText;
				}
				set
				{
					mInstance.TravelTypeHeroAltText = value;
				}
			}


			/// <summary>
			/// Hero Icon.
			/// </summary>
			public string TravelTypeHeroIcon
			{
				get
				{
					return mInstance.TravelTypeHeroIcon;
				}
				set
				{
					mInstance.TravelTypeHeroIcon = value;
				}
			}


			/// <summary>
			/// SVG Icon.
			/// </summary>
			public string TravelTypeSVGIcon
			{
				get
				{
					return mInstance.TravelTypeSVGIcon;
				}
				set
				{
					mInstance.TravelTypeSVGIcon = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TravelTypeLanding" /> class.
		/// </summary>
		public TravelTypeLanding() : base(CLASS_NAME)
		{
			mFields = new TravelTypeLandingFields(this);
		}

		#endregion
	}
}