//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using ETG.Core.PageTypes;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Webinar.CLASS_NAME, typeof(Webinar))]

namespace ETG.Core.PageTypes
{
    /// <summary>
    /// Represents a content item of type Webinar.
    /// </summary>
    public partial class Webinar : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ETG.Webinar";


        /// <summary>
        /// The instance of the class that provides extended API for working with Webinar fields.
        /// </summary>
        private readonly WebinarFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// WebinarID.
        /// </summary>
        [DatabaseIDField]
        public int WebinarID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("WebinarID"), 0);
            }
            set
            {
                SetValue("WebinarID", value);
            }
        }


        /// <summary>
        /// Name.
        /// </summary>
        [DatabaseField]
        public string WebinarName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("WebinarName"), @"");
            }
            set
            {
                SetValue("WebinarName", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string WebinarDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("WebinarDescription"), @"");
            }
            set
            {
                SetValue("WebinarDescription", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string WebinarImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("WebinarImage"), @"");
            }
            set
            {
                SetValue("WebinarImage", value);
            }
        }


        /// <summary>
        /// Recording Url.
        /// </summary>
        [DatabaseField]
        public string WebinarRecordingUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("WebinarRecordingUrl"), @"");
            }
            set
            {
                SetValue("WebinarRecordingUrl", value);
            }
        }


        /// <summary>
        /// Coming Soon Date.
        /// </summary>
        [DatabaseField]
        public DateTime WebinarComingSoon
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("WebinarComingSoon"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("WebinarComingSoon", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Webinar fields.
        /// </summary>
        [RegisterProperty]
        public WebinarFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Webinar fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class WebinarFields : AbstractHierarchicalObject<WebinarFields>
        {
            /// <summary>
            /// The content item of type Webinar that is a target of the extended API.
            /// </summary>
            private readonly Webinar mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="WebinarFields" /> class with the specified content item of type Webinar.
            /// </summary>
            /// <param name="instance">The content item of type Webinar that is a target of the extended API.</param>
            public WebinarFields(Webinar instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// WebinarID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.WebinarID;
                }
                set
                {
                    mInstance.WebinarID = value;
                }
            }


            /// <summary>
            /// Name.
            /// </summary>
            public string Name
            {
                get
                {
                    return mInstance.WebinarName;
                }
                set
                {
                    mInstance.WebinarName = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.WebinarDescription;
                }
                set
                {
                    mInstance.WebinarDescription = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.WebinarImage;
                }
                set
                {
                    mInstance.WebinarImage = value;
                }
            }


            /// <summary>
            /// Recording Url.
            /// </summary>
            public string RecordingUrl
            {
                get
                {
                    return mInstance.WebinarRecordingUrl;
                }
                set
                {
                    mInstance.WebinarRecordingUrl = value;
                }
            }


            /// <summary>
            /// Coming Soon Date.
            /// </summary>
            public DateTime ComingSoon
            {
                get
                {
                    return mInstance.WebinarComingSoon;
                }
                set
                {
                    mInstance.WebinarComingSoon = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Webinar" /> class.
        /// </summary>
        public Webinar() : base(CLASS_NAME)
        {
            mFields = new WebinarFields(this);
        }

        #endregion
    }
}